### ISSUE TITLE
Failed to ressuply fleet

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#10]
D:\sikuli>runScript -d 2 -r C:\Users\kevin\Desktop\kancolle-auto-master\kancolle
_auto.sikuli
+++ running this Java
java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b17)
Java HotSpot(TM) Client VM (build 23.25-b01, mixed mode)
+++ trying to start Sikuli Script
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
D:\sikuli\sikuli-script.jar -d 2 -r C:\Users\kevin\Desktop\kancolle-auto-master\
kancolle_auto.sikuli
[debug] Running on Java 7 (1.7.0_25-b17)
[debug] ResourceLoaderBasic: check: we are running on arch: x86
[debug] ResourceLoaderBasic: check: using Java at: C:/Program Files/Java/jre7/
[debug] Screen: initScreens: basic initialization (1 Screen(s) found)
←[94m[2015-09-20 12:17:58] Reading config file←[0m
←[92m[2015-09-20 12:17:58] Config loaded!←[0m
←[92m[2015-09-20 12:17:58] Starting kancolle_auto←[0m
←[94m[2015-09-20 12:17:58] Focus on KanColle!←[0m
[log] App.focus KanColleTool Viewer(0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-09-20 12:18:06] At Home!←[0m
←[94m[2015-09-20 12:18:06] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-20 12:18:10] No, no fleets to receive!←[0m
←[92m[2015-09-20 12:18:10] Refreshing Home!←[0m
[debug] waiting for supply_main.png to appear
[debug] supply_main.png has appeared.
[log] CLICK on L(412,351)@S(0)[0,0 1366x768]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(406,386)@S(0)[0,0 1366x768]
←[92m[2015-09-20 12:18:17] At Home!←[0m
←[94m[2015-09-20 12:18:17] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-20 12:18:21] No, no fleets to receive!←[0m
←[94m[2015-09-20 12:18:21] Navigating to Expedition menu!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(534,396)@S(0)[0,0 1366x768]
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[log] CLICK on L(1008,366)@S(0)[0,0 1366x768]
[debug] waiting for expedition_screen_ready.png to appear
[debug] expedition_screen_ready.png has appeared.
←[94m[2015-09-20 12:18:27] Let's send an expedition out!←[0m
[debug] waiting for ensei_area_05.png to appear
[debug] ensei_area_05.png has appeared.
[debug] waiting for ensei_area_05.png to appear
[debug] ensei_area_05.png has appeared.
[log] CLICK on L(702,564)@S(0)[0,0 1366x768]
[debug] waiting for ensei_name_38.png to appear
[debug] ensei_name_38.png has appeared.
[debug] waiting for ensei_name_38.png to appear
[debug] ensei_name_38.png has appeared.
[log] CLICK on L(631,451)@S(0)[0,0 1366x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(1012,571)@S(0)[0,0 1366x768]
←[94m[2015-09-20 12:18:35] Trying to send out fleet 3 for expedition 38←[0m
[debug] waiting for fleet_3.png to appear
[debug] fleet_3.png has appeared.
[debug] waiting for fleet_3.png to appear
[debug] fleet_3.png has appeared.
[log] CLICK on L(756,247)@S(0)[0,0 1366x768]
←[93m[2015-09-20 12:18:45] Fleet 3 needs resupply!←[0m
←[94m[2015-09-20 12:18:45] Lets resupply fleets!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for supply_screen.png to appear
[debug] supply_screen.png has not appeared.
[error] script stopped with error in line 299
[error] FindFailed ( can not find supply_screen.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement
135: main (  resupply )     kc_window.wait('supply_screen.png', WAITLONG)
214: main (  run_expedition )     resupply()
282: main (  init )     run_expedition(expedition)
[error] --- Traceback --- end --------------

well when the script found that the fleet is not ressuplied before sending to expedition it did not click the button to go to ressuply screen so it waited indefinitely

**Comment by mrmin123** [comment]
@kevin01523 Could you try replacing the image with this one and re-running?: 
![ensei_name_05](https://cloud.githubusercontent.com/assets/4326866/9979402/93b1bd24-5f1f-11e5-9eb1-655200524353.png)
I remember having similar issues before with another expedition, and updating the image seemed to help. I just tried exp 5 with the old image and the script crashed like you reported, but worked with this image.

**Comment by mrmin123** [comment]
I made it go to the resupply screen first! Should work now.

**Comment by kevin01523** [comment]
←[94m[2015-09-26 04:13:50] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-09-26 04:13:56] No, no fleets to receive!←[0m
←[94m[2015-09-26 04:13:56] Lets resupply fleets!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for supply_all.png to appear
[debug] supply_all.png has not appeared.
[error] script stopped with error in line 333
[error] FindFailed ( can not find supply_all.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement
161: main (  resupply_action )     kc_window.hover('supply_all.png')
147: main (  resupply )     resupply_action()
[error] --- Traceback --- end --------------

this is the resupply for the 3-2-a runner for main fleet

hmm now this happens 3x  within 1 hour
@mrmin123

**Comment by mrmin123** [comment]
@kevin01523 Happening consistently, or only once in a while? What screen did you end at? From the logs it looks like the script missed the check for `supply_screen.png` and went straight into looking for `supply_all.png`, but this should be checked for by [this block](https://github.com/mrmin123/kancolle-auto/blob/master/kancolle_auto.sikuli/kancolle_auto.py#L134)

**Comment by kevin01523** [comment]
it ends at the home screen i think its after 3-2 since all expedition are busy. yeah thats why im kinda confused why did that happen that was my last try on windows it stopped 3 times there, on the 2nd 3-2-a run after  starting the script

**Comment by mrmin123** [comment]
Make sure your codebase is up to date/not modified. I've been running 3-2A with all expeditions for around a week with no crashes, so I've not had this issue.

**Comment by kevin01523** [comment]
its up to date w/ your latest one it runs perfectly on my ubuntu vm but idk in my win7 vm well it happened jut recently so ill test it a bit more

**Comment by mrmin123** [comment]
Very strange behavior. Retracing the logs it looks like, despite being at the Home screen, the script determined that `supply_screen.png` exists, and then also determined that `Pattern('supply_all.png').exact()` exists while `Pattern('checked.png').exact()` does not. Maybe something with the VM?

**Comment by kevin01523** [comment]
i think its just a bug after i restarted the vm it got ok ill post again if i encounter it again
