### ISSUE TITLE
Troubleshooting error

### ISSUE THREAD

**Issue by Aftersky** [mrmin123/kancolle-auto#102]
The script crash every time an expedition fleet returns and I'm not sure what the cause is. 

```
[94m[2016-01-17 17:28:15] Focus on KanColle![0m
[log] App.focus Google Chrome(0) #0
[92m[2016-01-17 17:28:26] At Home![0m
[94m[2016-01-17 17:28:26] Checking for returning expeditions![0m
[94m[2016-01-17 17:28:26] Are there returning expeditions to receive?[0m
[log] CLICK on L(775,368)@S(0)[0,0 1366x768]
[log] CLICK on L(721,502)@S(0)[0,0 1366x768]
[error] script stopped with error in line 375
[error] UnboundLocalError ( local variable 'fleet_id' referenced before assignme
nt )
[error] --- Traceback --- error source first
line: module ( function ) statement
95: main (  check_expedition )     log_success("Yes, fleet %s has returned!" % f
leet_id)
66: main (  go_home )     if check_expedition():
194: main (  sortie_action )     go_home()
367: main (  init )     sortie_action()
367: main (  init )     sortie_action()
[error] --- Traceback --- end --------------
```

I've tried the script on 2 different machines with Win10/Jre8 and XP/Jre7, both get this error. The connection is stable and sleep time is default value. Any help would be appreciated!

**Comment by n0k0m3** [comment]
Can you post the screenshot at when the problem happens?

And btw, try to run the script with -d 2 option and post the result here

**Comment by mrmin123** [comment]
@Aftersky My guess is that you don't have the default names for your expedition fleets (第2艦隊, 第3艦隊, and 第4艦隊). If this is the case, you have two choices:
1. Rename your expedition fleets back to what's listed above
2. Update and replace `returned_fleet2.png`, `returned_fleet3.png`, and `returned_fleet4.png` in the base `kancolle_auto.sikuli` folder with updated screenshots from your own kancolle game. The region I recommend are here, outlined in red (you can use the existing images as a guide, if you're unsure):
   ![image](https://cloud.githubusercontent.com/assets/4326866/12377163/e6e79b02-bcc7-11e5-96fc-ef37300afa54.png)
   (random google image searched image...)

If your expedition fleets have the default names and kancolle auto is still crashing, please let me know.

**Comment by Aftersky** [comment]
Renaming the expedition fleets to default solved it, thank you!
