### ISSUE TITLE
Features request. 

### ISSUE THREAD

**Issue by Anhpossible** [mrmin123/kancolle-auto#108]
Hello, I'd like to request some new features for kc-auto if mrmin123 or someone with the knowledge would be able to find the time to implement them at some point: 
- Individual night attack toggles for each node, i.e: no NA on 1st, 2nd node. NA on 3rd. Useful for dailies/boss kills if the route is predictable.
- ~~Ability to rotate between fleet templates for each sortie to preserve morale and reduce bot-like behavior.~~
- ~~Separate formation/sortie map config for fleet templates if the above is implemented.~~

Thanks!

Edit: I'm blind, looks like the fleet template feature is already being worked on.

**Comment by mrmin123** [comment]
Hi @Anhpossible, your third request is already implemented via the `NightBattles` variable in the [Combat section](https://github.com/mrmin123/kancolle-auto/wiki/Setup-config.ini#combat) of the config.

Requests one and two should be relative simple in the sense that it won't require a ton of new code/features, assuming that the (personally untested) fleet switcher module I incorporated recently works, but will still take time to implement into the config + combat module logic.

**Comment by silfumus** [comment]
I think the examples are not intuitive enough. The first time I used it, I thought it meant either do or don't do yasen on _all_ nodes.

Perhaps using 4-2 (False, False, True) as map example might be better.

**Comment by mrmin123** [comment]
@silfumus Noted. What are your thoughts on moving the config help text out and just providing a link to the Config page in the wiki?

**Comment by n0k0m3** [comment]
Agree, we should keep the config concise enough anf move everything else to
wiki

**Comment by silfumus** [comment]
The current format is fine.
But I agree that some help text regarding advanced usage of kancolle-auto would be better served in the wiki.
