### ISSUE TITLE
Troubleshooting expedition script after cat bomb recovery

### ISSUE THREAD

**Issue by Aftersky** [mrmin123/kancolle-auto#109]
I noticed that KC3/Browser cat bomb recovery options have never worked for me since the F1-12 keys are suppressed if the cursor is still highlighting the game. F5 doesn't do anything in this case so I made a small adjustment to have kc-auto click the browser refresh button instead of typing F5:

```
if settings['recovery_method'] == 'Browser':
if kc_window.exists(Pattern('refresh.png').exact()):
rclick(kc_window, 'refresh.png')
sleep(1)
```

That seemed to work, but as soon as the game is refreshed & get to secretary screen, the script crash:

```
[94m[2016-02-03 15:46:04] Reading config file[0m
[92m[2016-02-03 15:46:04] Expeditions (fleet 2: 5, fleet 3: 21, fleet 4: 38) en
abled![0m
[92m[2016-02-03 15:46:04] Config loaded![0m
[94m[2016-02-03 15:46:04] Reading config file[0m
[92m[2016-02-03 15:46:04] Starting kancolle_auto[0m
[94m[2016-02-03 15:46:04] Finding window![0m
[94m[2016-02-03 15:46:04] Focus on KanColle![0m
[log] App.focus Google Chrome(0) #0
[log] CLICK on L(71,37)@S(0)[0,0 1366x768]  <---- browser refreshed
[log] CLICK on L(588,549)@S(0)[0,0 1366x768] 
[94m[2016-02-03 15:46:31] Initial checks and commands complete. Starting loop.
[0m
[error] script stopped with error in line 436
[error] AttributeError ( 'NoneType' object has no attribute 'running_expedition_
list' )
[error] --- Traceback --- error source first
line: module ( function ) statement
436: main (  <module> )     for expedition in expedition_item.running_expedition
_list:
[error] --- Traceback --- end --------------
```

Other than the refresh change above I didn't touch any other code and I doubt it affected the expedition module in anyway. So, help please?

**Comment by Aftersky** [comment]
Tested it again this error seem to popup when I started the script at the cat bomb screen to test the recovery part but not when the script is already running -> get cat bombed -> recover. I'll monitor it some more before closing this issue.

**Comment by mrmin123** [comment]
Hey @Aftersky I know you just closed this but I wanted to check in to make sure everything is working properly. For what it's worth, my testing of the F5 key in the kancolle screen indicates that the F5 key still works properly to reload the page.

**Comment by Aftersky** [comment]
Hi @mrmin123 The expedition script is working properly but the F5 key still doesn't in 3 different browsers I've tried. Did you try pressing F5 with the cursor still focused on the flash area? 

Or it could be one of the restrictions imposed on my client because I'm pretty sure I've triggered their anti-bot measures. This is the 2nd time it happened and the oddities are the same : catbomb every 5-10 mins with stable connection and on the first sortie after a refresh the combat start button cannot be clicked on unless I return to secretary screen and try again, even on mobile browser. The latter has caused my script to get stuck  and crash every time.

**Comment by mrmin123** [comment]
Yes, I've never had an issue with refreshing with the focus being in Flash. Have you tried Ctr+R? Can't comment on anti-bot/other restrictions personally...

**Comment by Aftersky** [comment]
Ctrl + R doesn't work either, unless I click on an area outside of the flash area first.

I tried it on pretty much every browser on 3 different PCs and the result were the same, idk what the issue is. The click refresh modification works fine though so I'm not too bothered about it.
