### ISSUE TITLE
Forgotten Expeditions

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#110]
While testing/developing #104 I noticed a number of expedition fleets would be 'forgotten' by kancolle-auto... as in, the fleets would be received, but would not be sent back out again. I _think_ that it has to do with expeditions received during the PvP phase, but further testing is required.

Perhaps try to disconnect the fleetname check on expedition return as well? This would make the expedition module more flexible, allowing it to work with custom fleet names.

**Comment by Aftersky** [comment]
This issue still occur in the lastest commit (12e395b).

**Comment by mrmin123** [comment]
Yea, I noticed this again last night. I'm just going to completely rework the whole Expedition module.
