### ISSUE TITLE
Formation selection issue

### ISSUE THREAD

**Issue by silfumus** [mrmin123/kancolle-auto#117]
It seems that the latest (03c44cbded875a04396ab74411da0b6580535dee) kancolle-auto has problem in the combat module (at least on my end). It said 'Selecting fleet formation!' but it doesn't click the button in the formation selection screen. It just waits until the battle ends (which is never).

The version at 168b3a85824eb23c750b534f7c1fbb0e4278aaab works normal though, so I guess the problem lies after this commit.

**Comment by mrmin123** [comment]
The current master branch is **incredibly unstable and buggy**. Huge refactorings and such happening... I really shouldn't have merged it in but oh well >_> Hopefully the issues will be resolved by tonight.

**Comment by silfumus** [comment]
I understand, just trying to inform.
At least it's a known issue rather than some shitty setting on my end.

**Comment by mrmin123** [comment]
I shouldn't be coding this late at night because bugs but [111_optimize_quests](https://github.com/mrmin123/kancolle-auto/tree/111_optimize_quests) seems pretty stable for what I've tested (Expeditions, Quests, PvP). Please try as a temporary stopgap if you don't want to deal with downgrading...

**Comment by mrmin123** [comment]
This comment is for tracking purposes: this issue is related to work being done on #111
