### ISSUE TITLE
Automate event sorties

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#118]
... because why not?

If anyone has them, could they provide screenshots of the sortie map selection area for the event maps? Thanks!

**Comment by silfumus** [comment]
![e-1bannerwinter2016](https://cloud.githubusercontent.com/assets/6127734/13025477/b3d538f2-d24b-11e5-9fb6-bda4b152aa85.png)
![e-2bannerwinter2016](https://cloud.githubusercontent.com/assets/6127734/13025475/b3a15fe6-d24b-11e5-8c8e-607e5cdf0e25.png)
![e-3bannerwinter2016](https://cloud.githubusercontent.com/assets/6127734/13025476/b3cd1ec4-d24b-11e5-9740-9d1ed885e2d1.png)

Taken from http://en.kancollewiki.net/wiki/Winter_2016_Event
Don't forget that gauge bar and 甲・乙・丙 difficulty selection may obscure the images.

Also, is kancolle-auto capable of choosing in the manual selection node?

**Comment by mrmin123** [comment]
@silfumus Thanks. Do you by any chance have a screenshot of the arrow that switches the Events sorties page from E1 and E2 to EO?

**Comment by silfumus** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/6127734/13026067/0f45159c-d25e-11e5-9ecb-cdfb8dcc4b52.png)

**Comment by mrmin123** [comment]
Thanks again! The E3 image on the wiki is compressed I believe so I didn't include it at the moment (still haven't unlocked it myself), but I've merged in rudimentary support for event automation 
as of 16729af.

Usage steps:
1. Set Combat Area to 'E'
2. Set Combat Subarea to 1-1 or 1-2 (first number dictates the 'page' the event map is on, and the second number dictates which map on that page; 2-1 (or should it be 2-3?) aka E-3 is not supported as of yet)

Limitations:
- ~~Still no support for automatic node selection~~
- Will probably crash if using kancolle-auto to clear an event map for the first time, as it doesn't know how to respond to the map rewards
- ~~No combined fleet support~~
- ~~Related to that, no support for E3 yet~~

Tangentially:
- Config and wiki needs to reflect new additions
