### ISSUE TITLE
stuck on air battle node on 1-6

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#121]
```
[2016-02-17 02:02:45] Commencing sortie!
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for P(combat_start.png) S: 0.8 T: 38,-10 to appear
[debug] P(combat_start.png) S: 0.8 T: 38,-10 has appeared.
[log] CLICK on L(1009,574)@S(0)[0,0 1360x768]
[debug] waiting for P(compass.png) S: 0.8 T: 281,-73 to appear
[debug] P(compass.png) S: 0.8 T: 281,-73 has appeared.
[log] CLICK on L(959,312)@S(0)[0,0 1360x768]
[2016-02-17 02:03:14] Spinning compass!
[debug] waiting for P(formation_line_abreast.png) S: 0.95 T: -6,-10 to appear
[debug] P(formation_line_abreast.png) S: 0.95 T: -6,-10 has appeared.
[log] CLICK on L(981,473)@S(0)[0,0 1360x768]
[2016-02-17 02:03:38] Selecting fleet formation!
[2016-02-17 02:04:57] Declining night battle!
[debug] waiting for P(combat_nb_retreat.png) S: 0.8 T: 30,9 to appear
[debug] P(combat_nb_retreat.png) S: 0.8 T: 30,9 has appeared.
[log] CLICK on L(657,389)@S(0)[0,0 1360x768]
[debug] waiting for P(next.png) S: 0.8 T: -230,-283 to appear
[debug] P(next.png) S: 0.8 T: -230,-283 has appeared.
[log] CLICK on L(864,288)@S(0)[0,0 1360x768]
[2016-02-17 02:05:15] Checking fleet condition...
[2016-02-17 02:05:24] Light damage: 1; moderate damage: 0; critical damage: 0
[debug] waiting for P(next.png) S: 0.8 T: -14,-304 to appear
[debug] P(next.png) S: 0.8 T: -14,-304 has appeared.
[log] CLICK on L(1080,267)@S(0)[0,0 1360x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for P(combat_nextnode.png) S: 0.8 T: -31,9 to appear
[debug] P(combat_nextnode.png) S: 0.8 T: -31,9 has appeared.
[log] CLICK on L(604,382)@S(0)[0,0 1360x768]
[debug] waiting for P(compass.png) S: 0.8 T: 32,69 to appear
[debug] P(compass.png) S: 0.8 T: 32,69 has appeared.
[log] CLICK on L(710,454)@S(0)[0,0 1360x768]
[2016-02-17 02:06:20] Spinning compass!

```

since there are no compass after a specific node

**Comment by mrmin123** [comment]
I haven't sortied to 1-6 in a while so my memory is a bit foggy. What screen is kancolle stuck on after the kancolle-auto spins the compass?

**Comment by kevin01523** [comment]
the fleet formation selection

**Comment by mrmin123** [comment]
If you're stuck on the fleet formation page that's not an inherent problem with sortieing to 1-6. What does your config for the formations look like? Is the formation you've specified for the particular node available when you get to it? No typos? It's also possible that the image being used for the formation doesn't have a good match with what's on screen, so it would help to see if re-generating the image helps.

**Comment by Theu04** [comment]
I've also got this issue for 1-5.
Been playing around, but pretty certain that the config is right.

[Combat]
Enabled: True
FleetComp: 0
Area: 1
Subarea: 5
CombinedFleet: False
Nodes: 4
NodeSelects:
Formations: line_ahead, line_abreast, line_abreast, line_abreast
NightBattles: True
RetreatLimit: 2
RepairLimit: 0
RepairTimeLimit: 0100
SubmarineSwitch: False
CheckFatigue = True
PortCheck = True
medalstop = False

The script somehow doesn't want to pick the formation. I think I've got it to pick the formation once, but only when it was simply one formation written in the config, so I know it isn't an image error.

**Comment by Theu04** [comment]
It also appears the script freezes there, and doesn't continue even after I've brought it home.

**Comment by silfumus** [comment]
In my case (5-4 subslaving), I extend the sleep duration from 3s to 5~10s on combat.py, line 288.

**Comment by mrmin123** [comment]
@Theu04 I'm testing the config you posted and it's worked for the past 4 or 5 loops. No freezing on formation select. If it freezes on one specific formation, try generating your own screencapture for it and replacing it in the `combat.sikuli` folder. Let me know if that helps.

**Comment by mrmin123** [comment]
Tested [r4.1](https://github.com/mrmin123/kancolle-auto/releases/tag/4.1) on 1-6 and had no issues. Closing.
