### ISSUE TITLE
Error navigating to world 3-2

### ISSUE THREAD

**Issue by Aftersky** [mrmin123/kancolle-auto#125]
kcauto keep clicking on extra operation button in world 3 and crash because it can't find combat panel 3-2.png there.

This happen in lastest commit (ecf5a51) and the events branch.

**Comment by mrmin123** [comment]
So it goes to the World 3 screen, them pushes the Extra Operations arrow? Does this happen consistently? What does your config for the Area and Subarea settings look like?

**Comment by Aftersky** [comment]
Yes that's what happened and it is consistent.

```
Area: 3
Subarea: 2
Nodes: 1
```

**Comment by mrmin123** [comment]
@Aftersky oh, I'm an idiot.

Change `if str(self.subarea_num) > 4:` in `combat.py` (line 104) to `if int(self.subarea_num) > 4:`

That should fix it. I'll fix this in my next merge to master but that won't be until the end of the day at the soonest.

**Comment by Aftersky** [comment]
@mrmin123 Thanks, that fixed it.

**Comment by mrmin123** [comment]
Cool. I'm going to re-open this ticket and close when I merge the fix in so I remember.
