### ISSUE TITLE
SubmarineSwitch Issue + Need Improvisation

### ISSUE THREAD

**Issue by n0k0m3** [mrmin123/kancolle-auto#136]
After SubmarineSwitch, the repairing submarine is switched, however, instead of continuing sortie (as sortie condition is met), the script take the submarine repairing time and postpone the sortie until the submarine is repaired. This is pretty frustrating for me who have 5+ dupes of each submarines with the lowest level of 62 (1->9 hours of repair time).

Some improvisations can be implemented to SubmarineSwitch:
- Instead of looking for submarine by using stats (to avoid Taigei - 潜水母艦 - AS), using the class name will make the process much faster (SS/SSV) (潜水艦 and 潜水空母). Using only 潜水(sensui) will include the chance that Taigei be chosen -> Use full class name will eliminate this chance -> No need stats check -> Less time replacing Submarine
- In regard of using 潜水艦 and 潜水空母 to find subs,we can add option to replace current ship with SS or SSV only (SS for low repair time and resupply cost, SSV for torp power, armor and ship kills for quests)
- Replace low-morale submarine (which will be feasible with Repair Damage Threshold 1) for more effective orelling

**Comment by mrmin123** [comment]
The sortie time being long after a successful sub switch is strange and unintended. Do you get the message 'All submarines successfully swapped out! Continuing sorties!' in console? If you do, `sub_switch()` returns `True`, which in turn calls `self.next_sortie_time_set(0, randint(1, 2))`, theoretically resetting the next sortie timer. That said, I've never actually tested the SubmarineSwitch capability to its fullest so there's that.

Regarding your other suggested improvements:
- Searching for two separate images negates the ability to use `findAll()`, requiring additional layers of logic and complexity to juggle the two flags and results, which I'm not interested in working on right now. Improving `sub_switch`'s performance is also very low on my list of priorities (if you're in that big of a rush for a script that automates sorties, repairs, and submarine switching for you, I suggest you spend more time playing the game yourself...). That said, I welcome any pull requests.
- I suppose that could be a value add, but again, this would require additional layers of logic and complexity, which I'm not interested in working on right now. Again, I welcome any pull requests.
- Again, a value add, but even more work on `sub_switch`. See above.

**Comment by Danielosama** [comment]
I've had 2 problems with the SubmarineSwitch mechanic:
1) If I launch the script and my fleet (3-2A fleet, so only 1 sub) has it's sub is being repaired, it'll not switch it, it'll wait until the repairing time is over to sortie.
2) the script is not able to recognize "fleetcomp_dmg_repair" when the damaged submarin has orange or red morale, giving me this error: FindFailed: can not find fleetcomp_dmg_repair.png on the screen.
  Line 1574, in file Region.java

**Comment by mrmin123** [comment]
The first issue has been reported above, although I need more details to be
able to pin down why this is happening.

For the second, could you provide screen caps of the fleet comp screen with
a sub with mid or high fatigue being repaired?

**Comment by mrmin123** [comment]
@Danielosama: @minh6a fixed the second issue you encountered here: fb75f50
