### ISSUE TITLE
function[util.rejigger_mouse] AttributeError ( 'NoneType' object has no attribute 'x' )

### ISSUE THREAD

**Issue by BeemoLin** [mrmin123/kancolle-auto#138]
OS: mac osx 10.11.3

======= error log ======
[error] script [ /Users/Beemo/Sites/kancolle-auto/kancolle_auto.sikuli ] stopped with error in line 431
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
[error] --- Traceback --- error source first
line: module ( function ) statement
120: util (  rejigger_mouse )     rand_x = kc_window.x + randint(x1, x2)
40: main (  focus_window )     rejigger_mouse(kc_window, 370, 770, 100, 400)
384: main (  init )     focus_window()
384: main (  init )     focus_window()
[error] --- Traceback --- end --------------

util.py line 114
`temp_game = kc_window.getLastMatch()`

replace back, it working
`temp_game = kc_window.find(Pattern('menu_main_home.png').exact())`

**Comment by mrmin123** [comment]
I don't think your crash and the proposed fix are related. The `temp_game` assignment doesn't happen unless a 6th parameter is passed to `rejigger_mouse()` (the `find_position` variable, which defaults to `False`), and the crashlog you provided says that it crashed trying to find `kc_window.x`, not from `temp_game`. That seems more like a transient Sikuli error where the game could not instantiate `kc_window` (`myApp.focusedWindow()`) for whatever reason. Is the crash consistent with the original code?

**Comment by BeemoLin** [comment]
running SikuliX: /Applications/SikuliX.app/Contents/Java/sikulix.jar -r /Users/Beemo/Sites/kancolle-auto/kancolle_auto.sikuli
[2016-02-29 00:47:12] Reading config file
[2016-02-29 00:47:13] Combat enabled!
[2016-02-29 00:47:13] Config loaded!
[2016-02-29 00:47:13] Reading config file
[2016-02-29 00:47:13] Starting kancolle_auto
[2016-02-29 00:47:13] Finding window!
[2016-02-29 00:47:13] Focus on KanColle!
[log] App.focus:  [0:Electron]
[error] script [ /Users/Beemo/Sites/kancolle-auto/kancolle_auto.sikuli ] stopped with error in line 431
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
[error] --- Traceback --- error source first
line: module ( function ) statement
115: util (  rejigger_mouse )     util_settings['game_x'] = temp_game.x - 99
57: main (  focus_window )     rejigger_mouse(kc_window, 370, 770, 100, 400, True)
384: main (  init )     focus_window()
384: main (  init )     focus_window()
[error] --- Traceback --- end --------------

**Comment by BeemoLin** [comment]
57: main ( focus_window ) rejigger_mouse(kc_window, 370, 770, 100, 400, True)
I think `kc_window.getLastMatch()` that is the crux of the problem.

`print dir(kc_window.getLastMatch())`
`['__class__', '__delattr__', '__doc__', '__ensure_finalizer__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__']`

**Comment by mrmin123** [comment]
When it's crashing, is window in question (Electronic Observer) actually in focus and selected?

**Comment by mrmin123** [comment]
I ask because I've not had a problem with Sikuli switching over to Chrome and moving forward. Not sure if there's an issue with switching over to EO, as I haven't used it before.

**Comment by BeemoLin** [comment]
Focus on KanColle is done.
It crash, when it find game zero position.

Ok. Maybe just my system have this problem.

---

OS: mac osx 10.11.3
Electronic Observer 0.36.2
sikuli 1.1.0 Build: 2015-10-15_17:07
Python 2.7.10
