### ISSUE TITLE
Define search regions for common click regions

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#143]
Intended to speed up overall speed performance of kancolle-auto. Faster matching = more responsive script.

Could help with #130.

**Comment by mintgreenrose** [comment]
Hey man just wanna say your latest version was light years better than the old one: less crashes, more leveling. :) Hope this makes it even better

**Comment by mrmin123** [comment]
@tanatej thanks! Glad you're liking the improvements. Still working on making it run faster and better!

**Comment by mrmin123** [comment]
Incorporated in as of 7f52434.
