### ISSUE TITLE
[error] ConfigParser.NoSectionError ( No section: 'General' )

### ISSUE THREAD

**Issue by Theu04** [mrmin123/kancolle-auto#151]
_If you are submitting a feature request or a non-bug report, please feel free to delete this template. Also feel free to delete sections of this template you do not find relevant when submitting a bug report. Thanks!_
#### Environment details
- kancolle-auto version (last modified date):
- Viewer/browser: chrome
- Operating system: windows 10
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [X] Consistent
- [ ] Transient

[description of issue here, along with any screenshots and/or videos]
#### Console log (if applicable)

```
[log goes here]
[error] ConfigParser.NoSectionError ( No section: 'General' )

I barely know what I'm doing, so if this is really just a version conflict, please tell me. I haven't had much luck with kancolleauto.
```

**Comment by mrmin123** [comment]
@Theu04 Are you by any chance using an incredibly old version of kancolle-auto? Or could you post your config here?

**Comment by silfumus** [comment]
I think he forgot to extract **config.ini**

**Comment by Theu04** [comment]
I've got my config.ini within the folder, unless it's location is supposed to change.

[General]
Program: Google Chrome
RecoveryMethod: KC3
JSTOffset = 15
SleepCycle = 22
Paranoia = 3
SleepModifier = 0
[ScheduledSleep]
Enabled = True
StartTime = 0000
SleepLength = 6

[Expeditions]
Enabled: True
Fleet2: 21
Fleet3: 
Fleet4: 
[PvP]
Enabled: True
FleetComp: 0

[Combat]
Enabled: True
FleetComp: 0
Area: 1
Subarea: 5
CombinedFleet: False
Nodes: 10
NodeSelects:
Formations: line_ahead
NightBattles: True
RetreatLimit: 2
RepairLimit: 0
RepairTimeLimit: 0100
SubmarineSwitch: True
CheckFatigue = True
PortCheck = True

**Comment by mrmin123** [comment]
@Theu04 OK, so assuming that your config file exists, is in the right place (`kancolle_auto` folder, not `kancolle_auto.sikuli` folder), and the config file isn't mangled somehow... What OS are you on?

Could you try this? Open up `kancolle_auto.py` in the `kancolle_auto.sikuli` directory and replace these two lines:

```
    os.chdir(getBundlePath())
    os.chdir('..')
```

with

```
    os.chdir('PATH TO DIRECTORY CONTAINING CONFIG.INI')
```

(replacing PATH TO DIRECTORY CONTAINING CONFIG.INI with... the path to the directory containing config.ini on your machine. Surround the path with 's).

**Comment by Theu04** [comment]
Okay, I've got it to read the confi.ini now, but now I'm getting

I'm on windows 10.

`[error] ConfigParser.NoOptionError ( No option 'starttime1' in section: 'ScheduledSleep' )`

**Comment by mrmin123** [comment]
If you're on the latest version of kancolle-auto, the config has changed slightly. I suggest re-downloading `config.ini` from the latest version and then re-editing as needed.

**Comment by mrmin123** [comment]
Also, may I ask what OS you're on? If the `os.chdir` fix I proposed above worked, I'm not sure why the previous `getBundlePath()` and `..` solution didn't work in your case.

**Comment by Theu04** [comment]
Windows 10, as stated above. It turns out there was a folder mishap when extracting from the rar file. The config.ini was also in the kancolle_auto.sikuli  folder instead of the kancolle-auto-r3 folder. Do you happen to have a config file I could base off of? I've based the aforementioned config file on the examples in the wiki.

**Comment by mrmin123** [comment]
Ah, missed that you stated the OS in the OP, sorry. OK, not sure how a `config.ini` ended up in `kancolle_auto.sikuli`, but if you're on r3 I suggest downloading master: https://github.com/mrmin123/kancolle-auto/archive/master.zip

There have been changes to both the config and master branch since r3 that would make mixing versions incompatible. Also, I'd delete/empty the kancolle-auto directory you're using first, before extracting the master zip file into it, just in case.

**Comment by Theu04** [comment]
Got the mouse to move, but then it does nothing and instead spits out this error.

`[error] script [ kancolle_auto ] stopped with error in line 486
[error] AttributeError ( 'NoneType' object has no attribute 'x' )
[error] --- Traceback --- error source first line: module ( function ) statement 124: util ( rejigger_mouse ) util_settings['game_x'] = temp_game.x - 99
57: main ( focus_window ) rejigger_mouse(kc_window, 370, 770, 100, 400, True)
423: main ( init ) focus_window()
423: main ( init ) focus_window()
[error] --- Traceback --- end --------------`

**Comment by Theu04** [comment]
Changing the paranoia setting didn't do much, nor did re-sizing the window.

**Comment by mrmin123** [comment]
Your game window needs to always be at 100% scale, otherwise kancolle-auto won't be able to find it. Judging from the logs kancolle-auto/Sikuli it seems like kancolle-auto/Sikuli can't find the program you've specified. When kancolle-auto first runs, does it actually switch focus and select Google Chrome?

**Comment by Theu04** [comment]
I assume you're talking about the standard kancolle size, which I have even tried playing it on the original DMM site, nothing changed. When you say "switch focus" do you mean does it automatically move it's mouse to Google Chrome? If you mean that, then yes it does. It moves the mouse over to the window and over many trials it has hovered the mouse over various buttons, but have not clicked them or done much else.

**Comment by mrmin123** [comment]
@Theu04 I still don't have my dev environment set up on my Win10 machine (upgraded over the weekend) so I won't be able to better debug this until later tonight, but it sounds like it might be an OS issue... Link: https://answers.launchpad.net/sikuli/+question/269810

Maybe installing a JDK might fix it?

**Comment by Theu04** [comment]
Installing JDK didn't change anything. Can an OS really make the code break? All the programs appear to work. (minus the actual script) Does the fact that I've had to install 1.1.0 Sikulix change anything? 1.0x does not work on windows 10.

**Comment by mrmin123** [comment]
It's completely possible that the OS, which apparently necessitated Sikuli 1.1.x instead of 1.0.x, could break kancolle-auto since it was developed for Sikuli 1.0.x. I won't know for certain until later tonight, however.

**Comment by Theu04** [comment]
I'll wait until then, thanks for your help so far.

**Comment by Theu04** [comment]
Tried it on another computer, still failed. I changed the resolution a couple times, nothing changed.

**Comment by n0k0m3** [comment]
Record the screen and upload it here so we can actually know what happened

**Comment by Theu04** [comment]
https://www.youtube.com/watch?v=IAx2ZF17bHc&feature=youtu.be

Those mouse movements after I've started the program is Kancolle-Auto until Sikuli reopens and states the error.

**Comment by n0k0m3** [comment]
It is because u use full expanded window. Try to compact them/fit the
window to only Kancolle swf with kc3kai.
Btw, IDE is not the best way to use this script

**Comment by mrmin123** [comment]
@Theu04 Holy crap, sikuli 1.1.x is a goddamn mess! Reading the docs/bug tracker, I can't even keep track of the points of failure where things from functionality from 1.0.1 worked/behaved one way and is broken/changed in 1.1.x!

You need to go back to sikuli 1.0.1!: https://launchpad.net/sikuli/sikulix/1.0.1/+download/sikuli-setup.jar

Note: you need JRE 7, not 8 for a smooth installation. I swear I managed to get 1.0.1 to work with JRE 8 previously, but I can't remember how... and if I didn't, I need to update the readme and wiki to reflect that you need JRE7. Either way, install JRE7, run `sikuli-setup.jar`, then run the extracted `runSetup.cmd` with options 2 and 4. Then in your command prompt, you can do `[path to java7 install]\java.exe -jar [path-to-sikuli-1.0.1]\sikuli-script.jar -r [path-to-kancolle-auto]\kancolle-auto.sikuli`.

If you want to make java easier to call, I did the following:

Make a copy of `java.exe` in the `jre7\bin` folder, renamed it `java7.exe`
![image](https://cloud.githubusercontent.com/assets/4326866/14133189/ea6d4556-f601-11e5-8b5d-34b67b372d7c.png)

and then add the path to the PATH list in Environment Variables:
1. Open System Properties:
   ![image](https://cloud.githubusercontent.com/assets/4326866/14133200/068c47b4-f602-11e5-9681-f34545b77ba0.png)
2. Click Environmental Variables button at bottom
   ![image](https://cloud.githubusercontent.com/assets/4326866/14133205/17156e26-f602-11e5-945e-af30ca093530.png)
3. Select the Path variable from the bottom list of System Variables, then hit Edit
   ![image](https://cloud.githubusercontent.com/assets/4326866/14133224/2e370eb6-f602-11e5-8e59-01f447e5cb30.png)
4. Press New and add the jre7\bin folder (or Browse to it)
   ![image](https://cloud.githubusercontent.com/assets/4326866/14133228/3ab0f7f6-f602-11e5-97d9-bf586183af66.png)
5. OK out of everything

Then open up a command prompt, and you can do `java7 -jar [path-to-sikuli-.1.0.1]\sikuli-script.jar -r [path-to-kancolle-auto]\kancolle-auto.sikuli`

Hope this helps.

**Comment by Theu04** [comment]
Problem is, runSetup.cmd doesn't open with options, instead opening for an microsecond and closing without any launcher.

**Comment by mrmin123** [comment]
If you run it in the command prompt you'll probably see an error message or
something.

**Comment by Theu04** [comment]
I've created the .bat file and linked it to the Sikuli folder and kancolle-auto folder, and it appears that sikuli has accepted it, but the script doesn't initiate.

**Comment by Theu04** [comment]
I've successfully installed JRE 7 and Sikuli 1.0.1, if wondering.

**Comment by Theu04** [comment]
Scratch that, mistype of the bat file. The script now works. Thanks for your help mates.
