### ISSUE TITLE
Resupply loop clicking bug

### ISSUE THREAD

**Issue by silfumus** [mrmin123/kancolle-auto#152]
#### Environment details
- kancolle-auto version (last modified date): fb75f50dd786daec97c4fe3f1025fbc0491bbb99
- Viewer/browser: KC3Kai/Google Chrome
- Operating system: Windows 7
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [x] Transient

It seems that kancolle-auto sometimes click outside the valid area for fleet numbers, thus failing to open and resupply said fleet. The second resupply run usually fix this, though.

**Comment by mrmin123** [comment]
Do you know if the issue is like the one reported in #129?

**Comment by silfumus** [comment]
Ah yes, that's it.
I guess I'll try what you suggests in #129.
