### ISSUE TITLE
Seeking help :(

### ISSUE THREAD

**Issue by meowsq** [mrmin123/kancolle-auto#156]
Pardon me, but I'm really not tech savvy. I've been trying to troubleshoot this, but this is the furthest I've got with the tool. Can a kind soul help me out? Thank you so much!
#### Environment details
- kancolle-auto version (last modified date): release r3 (2016-02-20)
- Viewer/browser: Chrome /  KC3 v 28.5
- Operating system: Windows 8.1 x64
#### Issue

Unable to run KC-auto
#### Console log (if applicable)

```
C:\Users\Yi Ren>java -jar "C:\Sik\sikuli-script.jar" -r "C:\KC3\kancolle-auto-r3
/kancolle_auto.sikuli" -d 2
[debug] Running on Java 8 (1.8.0_71-b15)
[debug] ResourceLoaderBasic: check: we are running on arch: amd64
[debug] ResourceLoaderBasic: check: using Java at: C:/Program Files/Java/jre1.8.
0_71/
[debug] Screen: initScreens: basic initialization (1 Screen(s) found)
←[94m[2016-04-06 11:19:36] Reading config file←[0m
←[92m[2016-04-06 11:19:36] Expeditions (fleet 2: 21, fleet 3: 2, fleet 4: 5) ena
bled!←[0m
←[92m[2016-04-06 11:19:36] Combat enabled!←[0m
←[92m[2016-04-06 11:19:36] Config loaded!←[0m
←[94m[2016-04-06 11:19:36] Reading config file←[0m
←[92m[2016-04-06 11:19:36] Starting kancolle_auto←[0m
←[94m[2016-04-06 11:19:36] Finding window!←[0m
←[94m[2016-04-06 11:19:36] Focus on KanColle!←[0m
[log] App.focus KC3(0) #0
[log] App.focus KC3(0) #0
[log] App.focus KC3(0) #0
[log] App.focus KC3(0) #0
[log] App.focus KC3(0) #0
[log] App.focus KC3(0) #0
[error] script stopped with error in line 431
[error] AttributeError ( 'NoneType' object has no attribute 'exists' )
[error] --- Traceback --- error source first
line: module ( function ) statement
44: main (  focus_window )     while not (kc_window.exists(Pattern('menu_main_ho
me.png').exact())
384: main (  init )     focus_window()
384: main (  init )     focus_window()
[error] --- Traceback --- end --------------

```

**Comment by meowsq** [comment]
When opening with -d 3, cmd shows a constant loop on robot desktop; keeps repeating one particular location

![image](https://cloud.githubusercontent.com/assets/18298304/14304538/91246824-fbee-11e5-97c2-115af3eea1b7.png)

**Comment by mrmin123** [comment]
@meowsq It looks like kancolle-auto is finding your game window (KC3) but can't find the `menu_main_home.png` in your game screen.

Could you check and confirm the following?:
1. When kancolle-auto runs, it does change focus to the Kantai Collection game window (selects it/brings it forward)
2. Kantai Collection is running at 100% windows scale, not scaled up or down
3. You're starting kancolle-auto with Kantai Collection after the 'Game Start' screen (home screen, or resupply screen, for instance)

**Comment by meowsq** [comment]
1) after running it in cmd, it brings up the KC game window

2) Not scaled up or down; but its innately not a full screen thing, isn't it?

3) Enters running file after entering home screen!

![image](https://cloud.githubusercontent.com/assets/18298304/14305089/edde4094-fbf3-11e5-94aa-da3a48eb7d6b.png)

This is exactly how my KC3 screen looks like - does resolution of my display matter? The problem persists whether the console is open or not!

If it helps, my config is attached below:

[General]
Program: Google Chrome
RecoveryMethod: KC3
JSTOffset = 0
SleepCycle = 20
Paranoia = 1
SleepModifier = 0

[ScheduledSleep]
Enabled = False
StartTime = 0030
SleepLength = 8.5

[Expeditions]
Enabled: True
Fleet2: 21
Fleet3: 2
Fleet4: 5

[PvP]
Enabled: False
FleetComp: 1

[Combat]
Enabled: True
FleetComp: 0
Area: 1
Subarea: 5
CombinedFleet: False
Nodes: 1
NodeSelects:
Formations: line_ahead
NightBattles: False
RetreatLimit: 2
RepairLimit: 1
RepairTimeLimit: 0100
SubmarineSwitch: False
CheckFatigue = True
PortCheck = False
MedalStop = False

[Quests]
Enabled: True
Quests: bd1, bd2, bd3, bd4, bd5, bd6, bd8, bw1, bw2, bw3, bw4, bw5, c2, c3, c4, c8, d2, d3, d4, d9, d11, e3, e4
CheckSchedule: 3

Console log as follows:

![image](https://cloud.githubusercontent.com/assets/18298304/14305455/8198de5e-fbf7-11e5-984e-6e7e9b156ee6.png)

**Comment by mrmin123** [comment]
Uhh.. your whole OS seems to be oversized. Your kantai collection game should be 800x480pixels large. I think you have increased scaling set somewhere at an OS level?

**Comment by meowsq** [comment]
I changed the scaling size back to 100%; it ran for a while, then the above error in the console appeared again. How curious.

![Uploading image.png…]()

**Comment by n0k0m3** [comment]
Record a session and post it here so we can actually know what happened.

**Comment by mrmin123** [comment]
If it's able to initialize and run through the main loop even once, kancolle-auto and the setup itself is stable and compatible. The only other suggestion I can make is to make the size of your Kantai Collection as small as possible with no unused space to minimize the amount of space Sikuli has to search for matches in.

**Comment by meowsq** [comment]
mrmin is right. After I changed the size, it worked fine. Many thanks... I wouldn't have guessed resolution would play a part :P

> close

**Comment by mrmin123** [comment]
@meowsq Sikuli operates via image matching, so if the images I and the others here generated do not match what you see on your screen, you're gonna have a bad time.

Glad you got it to work!
