### ISSUE TITLE
Issue "Not a valid Sikuli script". Please help

### ISSUE THREAD

**Issue by Galerians** [mrmin123/kancolle-auto#157]
Okay, I'm pretty new to this so I should just put one the screenshot of whatever the hell it says in the cmd window. 

![error](https://cloud.githubusercontent.com/assets/18311550/14330092/7491bd00-fc71-11e5-96b3-d8030a0ed1c6.jpg)

I don't understand why is this happening. Can someone help?

**Comment by mrmin123** [comment]
@Galerians The path to the script should be `D:\KanColle\kancolle-auto-r3\kancolle-auto.sikuli`. `kancolle-auto.sikuli`, not `kancolle.auto-sikuli`.
