### ISSUE TITLE
Repair Issue

### ISSUE THREAD

**Issue by goneclick** [mrmin123/kancolle-auto#159]
Not sure if I'm the only one who has this issue but when the bot tries to repair ships, it selects the wrong ship. For example, there is a submarine that needs to be repaired which is currently in the top-most slot of the repair list, but the bot clicks on the second ship instead and then crashes.

Running on chrome with K3 Viewer.

**Comment by mrmin123** [comment]
kancolle-auto might select the "wrong" ship for repairs if there are multiple ships under the repair threshold, even if they are not in the fleet you are sortieing. This point is mentioned in the [Setup Kancolle](https://github.com/mrmin123/kancolle-auto/wiki/Setup-kancolle) of the wiki. It is known side effect and will not be addressed from the script end. It should, however, not crash, but I can't help you without relevant details (logs, screenshots, list of ships that cause the crash, etc).

**Comment by goneclick** [comment]
I thought that would be the cause of this as well. So i made sure that all my ships were repaired before running the bot. But after about an hour, the script selected the wrong ship again and crashed. I'll try to record some evidence the next time this happens.

**Comment by mrmin123** [comment]
That's very odd. Is it selecting a ship that is NOT damaged and trying to repair it, leading to the crash? If that's the case I may have an idea as to why it's happening..

edit: the most useful thing would be to provide a screenshot of the state of your game (even more useful would be to provide a screenshot of your entire desktop for coordinate-finding, but I understand if you might not want to share that), and the last two dozen or so lines from the console log.

**Comment by Aftersky** [comment]
This just happened to me, kc auto tried to repair a ship that is already in the dock before I started the script (Abukuma) instead of the ship that requires repair (Maruyu) and crashed. Abukuma didn't even meet the condition I specified for a repair (critically damaged).

https://dl.dropboxusercontent.com/u/73564551/games/KanColle/rep.png

**Comment by mrmin123** [comment]
Hopefully this is fixed in the [latest update](https://github.com/mrmin123/kancolle-auto/wiki/Changelog#2016-05-05). Closing the ticket for now, but please reopen/create a new ticket if this still happens.
