### ISSUE TITLE
Add support for 2016 Spring Event

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#161]
I won't have time to play the event for at least a few days, so I'd like to ask people who might be using this during the event to help provide some screencaps of the event sortie panels. Ideally they'd be in png format and uncompressed.

If you'd like to generate the panel images yourself, the screencap'ed portion of the panel for sikuli to match on should be a section that is never covered by the gauge, medal, and EO/next page/prev page buttons at all times.

**Comment by Aftersky** [comment]
http://amat.su/Z6fOBr
http://amat.su/Vcp6QB
http://amat.su/JyJLVB

Does this help?

**Comment by mrmin123** [comment]
That's actually a big help, thanks!

The maps would've been amazing for node selection but they don't have the red circles so unfortunately we can't use that here (although I may revisit them to try and mimic the red circle overlay...).

**Comment by mintgreenrose** [comment]
What does an event sortie panel look like? I may be able to get that for you

**Comment by mrmin123** [comment]
I've already added the panel images, but I can still use screen captures of
the arrows you need to click to go from page to page in the event sortie
screens. Also, screencaptures of the map when you have to select a node,
with the little blue ping that resonates out of the node being as
small/translucent as possible.

**Comment by mintgreenrose** [comment]
Hope this is the one you're looking for:

http://s32.postimg.org/941ep9t45/Page_1.png

http://s32.postimg.org/pk5qemtut/Page_2.png

http://s32.postimg.org/tzxsur1yd/Page_3.png

For the node select map, I think that's available in the Kancolle Wikia

http://kancolle.wikia.com/wiki/Spring_2016_Event

**Comment by AppleBoi86** [comment]
I'm running E7 Oyashio farm. I might as well help a bit. Is this what you need?

postimg.org/image/733fdq69t/
postimg.org/image/7sr9n7d4x/
postimg.org/image/m9ej1s2m9/
**postimg.org/image/71thkb4g1/**
postimg.org/image/4s5d9jvi9/

**Comment by mrmin123** [comment]
@mintgreenrose Thanks for those. I've already revised some of the panel images and added the arrow/next page images. The node map on the wikia are overlays on a blank map so a bit inaccurate for use here.

@AppleBoi86 yes, those images are very helpful. The fourth image (I've bolded it) is probably the 'best' looking, although I'm definitely a bit concerned about the text bubble hovering over the top node. Oh well.

**Comment by AppleBoi86** [comment]
I think you would need this screen as well? As E5 and E7 will have at least 2 randomly chosen nodes for air battle against your airfields before the node selection screen.

postimg.org/image/64b105ik1/

**Comment by mrmin123** [comment]
Does that screen require interaction at all?

**Comment by AppleBoi86** [comment]
No interaction needed.  The air battle will take roughly 5 - 10 seconds for it to reach the formation selection screen.

EDIT : I'm testing out to see if the node selection is alright since the white bubble is bouncing up and down for node D but I encounter these errors.

**If I use 'formation_combinedfleet_4' for Formations:**
[92m[2016-05-14 16:21:03] Commencing sortie![0m
[log] CLICK on L(1387,464)@S(0)[0,0 1600x900]
[error] Region.exists: seems that imagefile could not be found on disk

**If I use 'combinedfleet_4' for Formations :**
[94m[2016-05-14 22:36:06] Reading config file[0m
[91m[2016-05-14 22:36:06] 'combinedfleet_4' is not a valid formation! Please ch
eck your config file.[0m
[info] Exit code: 0

**Comment by mrmin123** [comment]
@AppleBoi86 Sorry for the delayed response ... I don't get email updates on post edit, so I missed it. Does the file `formation_combinedfleet_4.png` exist in your `combat.sikuli` directory?

**Comment by mrmin123** [comment]
Actually, I'm an idiot. I implemented the value checks for the formations incorrectly.

The lines in `kancolle_auto.py` (starting at 345):

```
            settings_check_valid_formations = ['formation_combinedfleet_1', 'formation_combinedfleet_2', 'formation_combinedfleet_3', 'formation_combinedfleet_4']
            settings_check_filler_formation = 'formation_combinedfleet_4'
        else:
            settings_check_valid_formations = ['formation_diamond', 'formation_double_line', 'formation_echelon', 'formation_line_abreast', 'formation_line_ahead']
            settings_check_filler_formation = 'line_ahead'
```

should be changed to

```
            settings_check_valid_formations = ['combinedfleet_1', 'combinedfleet_2', 'combinedfleet_3', 'combinedfleet_4']
            settings_check_filler_formation = 'combinedfleet_4'
        else:
            settings_check_valid_formations = ['diamond', 'double_line', 'echelon', 'line_abreast', 'line_ahead']
            settings_check_filler_formation = 'line_ahead'
```

**Comment by mrmin123** [comment]
Are people finding the lack of airbase support to be hampering their ability to 'play' with kancolle-auto? I'm currently on the fence since 1. I'm not sure if it'll be used anywhere else 2. it seems like most of the monotonous grinding kancolle-auto is supposed to alleviate doesn't necessarily need to use the land air base support.

**Comment by Danielosama** [comment]
I've not used KancolleAuto for a week now since I'm being "searched" as a bot by being bombarded with catbombs every so often, but I'd say, to farm E7 at least, airbase support is quite important there, since it does a lot of the job by itself. Wether or not it'll be used anywhere else, no idea, maybe in the next event?

**Comment by AppleBoi86** [comment]
So far my E7 Oyashio farming is going smooth without airbase support.  Then again, the most important is your fleet setup and being able to get air superiority or not.

**Comment by mrmin123** [comment]
Closing this as E7 is over. Thanks for everyone's help and input. I've saved some assets for airbase support, but at the moment I have no plans on implementation.
