### ISSUE TITLE
TextRecognizer: init: tessdata folder not found

### ISSUE THREAD

**Issue by SomeGuyKyon** [mrmin123/kancolle-auto#164]
Hi, I tried your code yesterday and stuck in some problem.

it works fine in early, but some error showed up during expedition session.

here is my log. any suggestions I can get? 

C:\Users\LabSub111\Downloads\kancolle-auto-master>java -jar sikuli-script.jar -r
 ./kancolle_auto.sikuli
5월 08, 2016 5:59:01 오후 java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0
x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[94m[2016-05-08 17:59:07] Reading config file[0m
[92m[2016-05-08 17:59:07] Expeditions (fleet 2: 5, fleet 3: 38, fleet 4: 2) ena
bled![0m
[92m[2016-05-08 17:59:07] Combat enabled![0m
[92m[2016-05-08 17:59:07] Config loaded![0m
[94m[2016-05-08 17:59:07] Reading config file[0m
[92m[2016-05-08 17:59:07] Starting kancolle_auto[0m
[94m[2016-05-08 17:59:07] Finding window![0m
[94m[2016-05-08 17:59:07] Focus on KanColle![0m
[log] App.focus KC3(0) #0
[94m[2016-05-08 17:59:19] Defining module items![0m
[94m[2016-05-08 17:59:19] Focus on KanColle![0m
[log] App.focus KC3(0) #0
[92m[2016-05-08 17:59:27] At Home![0m
[94m[2016-05-08 17:59:27] Checking for returning expeditions![0m
[94m[2016-05-08 17:59:27] Are there returning expeditions to receive?[0m
[log] CLICK on L(351,167)@S(0)[0,0 1920x1080]
[log] CLICK on L(422,208)@S(0)[0,0 1920x1080]
[92m[2016-05-08 17:59:37] Yes, an expedition has returned![0m
[94m[2016-05-08 17:59:37] It's probably fleet 2 that returned![0m
[log] CLICK on L(655,376)@S(0)[0,0 1920x1080]
[94m[2016-05-08 17:59:44] Are there returning expeditions to receive?[0m
[log] CLICK on L(566,411)@S(0)[0,0 1920x1080]
[log] CLICK on L(386,197)@S(0)[0,0 1920x1080]
[92m[2016-05-08 17:59:53] Yes, an expedition has returned![0m
[94m[2016-05-08 17:59:53] It's probably fleet 3 that returned![0m
[log] CLICK on L(670,133)@S(0)[0,0 1920x1080]
[log] CLICK on L(770,394)@S(0)[0,0 1920x1080]
[94m[2016-05-08 18:00:08] Are there returning expeditions to receive?[0m
[94m[2016-05-08 18:00:12] No, no fleets to receive![0m
[94m[2016-05-08 18:00:12] Lets resupply fleets![0m
[94m[2016-05-08 18:00:16] Navigating to resupply screen with 1 sidestep(s)![0m

[log] CLICK on L(248,179)@S(0)[0,0 1920x1080]
[log] CLICK on L(46,242)@S(0)[0,0 1920x1080]
[log] CLICK on L(190,159)@S(0)[0,0 1920x1080]
[log] CLICK on L(134,149)@S(0)[0,0 1920x1080]
[log] CLICK on L(228,154)@S(0)[0,0 1920x1080]
[log] CLICK on L(134,151)@S(0)[0,0 1920x1080]
[92m[2016-05-08 18:00:28] Done resupplying![0m
[94m[2016-05-08 18:00:28] Focus on KanColle![0m
[log] App.focus KC3(0) #0
[94m[2016-05-08 18:00:43] Going home with 0 or less sidestep(s)![0m
[log] CLICK on L(105,302)@S(0)[0,0 1920x1080]
[92m[2016-05-08 18:00:49] At Home![0m
[94m[2016-05-08 18:00:49] Are there returning expeditions to receive?[0m
[94m[2016-05-08 18:00:52] No, no fleets to receive![0m
[94m[2016-05-08 18:00:52] Focus on KanColle![0m
[log] App.focus KC3(0) #0
[92m[2016-05-08 18:00:59] At Home![0m
[94m[2016-05-08 18:00:59] Checking for returning expeditions![0m
[94m[2016-05-08 18:00:59] Are there returning expeditions to receive?[0m
[94m[2016-05-08 18:01:02] No, no fleets to receive![0m
[94m[2016-05-08 18:01:03] Navigating to expedition menu with 1 sidestep(s)![0m

[log] CLICK on L(244,250)@S(0)[0,0 1920x1080]
[log] CLICK on L(411,206)@S(0)[0,0 1920x1080]
[log] CLICK on L(736,154)@S(0)[0,0 1920x1080]
[log] CLICK on L(770,161)@S(0)[0,0 1920x1080]
[log] CLICK on L(795,160)@S(0)[0,0 1920x1080]
[log] CLICK on L(731,160)@S(0)[0,0 1920x1080]
[94m[2016-05-08 18:01:41] Let's send fleet 2 out for expedition 5![0m
[log] CLICK on L(411,338)@S(0)[0,0 1920x1080]
[error] TextRecognizer: init: tessdata folder not found at C:/Users/LabSub111/Do
wnloads/kancolle-auto-master/libs/
[error] Region.text: text recognition is now switched off
[93m[2016-05-08 18:01:50] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:01:53] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:01:55] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:01:56] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:01:58] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:01:59] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:02:02] Got invalid timer (n0text)... trying again![0m
[error] Region.text: text recognition is currently switched off
[93m[2016-05-08 18:02:04] Got invalid timer (n0text)... trying again![0m

**Comment by mrmin123** [comment]
@dogdrip2848 You're missing the tesseract OCR files that Sikuli and kancolle-auto requires to do OCR. Please refer to the installation page to see how to install it: https://github.com/mrmin123/kancolle-auto/wiki/Install-kancolle-auto#installation . Relevant steps are the ones that mention the `tessdata` folder.

**Comment by SomeGuyKyon** [comment]
@mrmin123 Oh thank you for your fast response

**Comment by SomeGuyKyon** [comment]
@mrmin123 Still don't give `tessdata`folder. Can this issue occur because of my remote connecting environment using Teamviewer?

**Comment by SomeGuyKyon** [comment]
@mrmin123 Well, I've just managed  to solve. simply copy&pasted `tessdata` from my non-remote connected PC to PC that I've installed your code. It seems working fine for now.

**Comment by mrmin123** [comment]
@dogdrip2848 Sorry, didn't see your last message until now. Glad you managed to find the fix. I don't think remotely connecting to your environment would have an impact (I use Teamviewer myself) but who knows. Sikuli's installer is a bit inconsistent with its installation of tesseract.
