### ISSUE TITLE
kancolle-auto randomly closed

### ISSUE THREAD

**Issue by etcet54** [mrmin123/kancolle-auto#168]
- kancolle-auto version (last modified date): release r3 (2016-02-20)
- Viewer/browser: Kancolleviewer/Google Chrome
- Operating system: Win 7 SP1 x64, resolution 1366x768
- [ x ] Consistent
- [ ] Transient

Hello, I have an issue where kancolle-auto closed by itself after few hours. I just use it for expedition, most of the times When I see the screen, either it exits when receiving expedition/resupllying page. Tried using kancolleviewer and google chrome but no luck.

I don't know how to log/screen capture it since it closed suddenly at random times.
If there's a way to log it please let me know.

Thanks a lot

**Comment by n0k0m3** [comment]
If the error is Consistent, can you post here the cmd log?

On Thu, May 19, 2016 at 7:58 PM, etcet54 notifications@github.com wrote:

> - kancolle-auto version (last modified date): release r3 (2016-02-20)
> - ## Viewer/browser: Kancolleviewer/Google Chrome
>   
>   ## Operating system: Win 7 SP1 x64, resolution 1366x768
>   
>   [ x ] Consistent
> - Transient
> 
> Hello, I have an issue where kancolle-auto closed by itself after few
> hours. I just use it for expedition, most of the times When I see the
> screen, either it exits when receiving expedition/resupllying page. Tried
> using kancolleviewer and google chrome but no luck.
> 
> I don't know how to log/screen capture it since it closed suddenly at
> random times.
> 
> Thanks
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mrmin123/kancolle-auto/issues/168

## 

Sincerely,

Minh Nguyen

**Comment by etcet54** [comment]
I wanted to, but where can I find the log file? I can't screenshot it because I don't know when the program suddenly close, it happens randomly after few hours.

edit: I found a way to prevent the command prompt box from auto close on error, I'll screenshot when It happen again.

**Comment by mrmin123** [comment]
Yes, the log is required to troubleshoot.

You might also want to consider upgrading to a more recent version of kancolle-auto... I'd say master is pretty stable right now.

**Comment by etcet54** [comment]
Hello, here is the log, I finally able to capture it when it happened, hope it helps to find the problem.
![capture](https://cloud.githubusercontent.com/assets/19471603/15437101/7621da60-1eef-11e6-95a5-a4d8fc729a26.JPG)

**Comment by mrmin123** [comment]
@etcet54 I'd either say upgrade to the latest version of master (contains improvements to `rnavigation`, and does not navigate to the shop in general), or remove the `menu_top_shop` value from the `menu_top_options` list in the `rnavigation` function contained in `util.py`.

**Comment by etcet54** [comment]
@mrmin123 Ok, I'll try the master branch version first then. If still happen then I'll try to remove the menu_top_shop value as suggested. Thanks a lot for the help

**Comment by mrmin123** [comment]
No problem, hope things are fixed on master branch!

**Comment by etcet54** [comment]
Hello, I apologize for reopening the issue again. I've use the latest release (r4, 2 days ago) but the error happens again, this time the menu_top_home.png error.

Here's the log
![capture](https://cloud.githubusercontent.com/assets/19471603/15474411/f2dfd0d4-212e-11e6-8c71-137b1e969775.JPG)

**Comment by mrmin123** [comment]
@etcet54 No problem, but could you describe the problem a bit more? Having more of the log leading up to the crash would be helpful, but maybe you can describe what kancolle-auto was doing before then: what action/subroutine was it doing, what screen did it crash on, where was the mouse located when it crashed, etc...

**Comment by mrmin123** [comment]
@etcet54 No problem, but could you describe the problem a bit more? Having more of the log leading up to the crash would be helpful, but maybe you can describe what kancolle-auto was doing before then: what action/subroutine was it doing, what screen did it crash on, where was the mouse located when it crashed, etc...

**Comment by etcet54** [comment]
ah, ok. The last time it happened, it's ended when receiving expedition, the program ended on this kind of page
![4t](https://cloud.githubusercontent.com/assets/19471603/15486074/35630b22-216d-11e6-85e1-fe1d256a997f.png)
as for the mouse location, I'm sorry I don't really pay attention on that.

I've run it again for 7 hours now and it's still working fine.
I'll try to screenshot the log longer next time it happened again.

**Comment by mrmin123** [comment]
Hmm. It sounds like a transient issue. Since it's transient it's less of an issue in the code and more related to other factors/noise in the environment it's running in. The only thing I can recommend is to increase the `SleepModifier` in the config by 1 or 2. Or you might not see it again. Hard to tell.

I'm going to close this, but if you continue to see this happening even with the above config change, feel free to collect a few more data points and re-open this issue.

**Comment by etcet54** [comment]
Hi, luckily it's just happened again, this time it's on this page when receiving expedition
![kancolle-160524-06182845](https://cloud.githubusercontent.com/assets/19471603/15487564/92715656-2178-11e6-9f6e-4d67e1f72ca7.jpg)

Mouse position is on the middle of the screen

I've screenshot longer log too just in case it can help anything
![capture](https://cloud.githubusercontent.com/assets/19471603/15487503/e802d14a-2177-11e6-844b-9eb0dfa8be70.JPG)

alright, I'll try changing the sleepmodifier, but if it's still happen, guess I'm just unlucky for experiencing this, haha. Thanks a lot for your help.
