### ISSUE TITLE
Make repair system more robust

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#17]
Currently, the repair system can only fix one ship, regardless of how many ships are at or below the threshold. This needs to be fixed so that the tool can determine how many repair docks are available and utilize them as needed. Also the tool needs to be able to come back and conduct additional repairs as repairs end.

**Comment by kevin01523** [comment]
[2015-10-13 14:12:40] Sortie complete!
[2015-10-13 14:12:40] Focus on KanColle!
[log] App.focus KanColleTool Viewer(0) #0
[log] switchApp: KanColleTool Viewer
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-13 14:12:46] At Home!
[2015-10-13 14:12:46] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-13 14:12:51] No, no fleets to receive!
[2015-10-13 14:12:51] Refreshing Home!
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(508,345)@S(0)[0,0 1360x768]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(380,335)@S(0)[0,0 1360x768]
[2015-10-13 14:12:57] At Home!
[2015-10-13 14:12:57] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-13 14:13:02] No, no fleets to receive!
[2015-10-13 14:13:02] Navigating to Repair menu!
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(432,440)@S(0)[0,0 1360x768]
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[log] CLICK on L(563,241)@S(0)[0,0 1360x768]
[2015-10-13 14:13:12] Check for critically damaged ships.
[2015-10-13 14:13:15] Check for moderately-damaged ships.
[debug] waiting for P(repair_dmg_moderate.png) S: 0.95 to appear
[debug] P(repair_dmg_moderate.png) S: 0.95 has appeared.
[log] CLICK on L(1043,214)@S(0)[0,0 1360x768]
[2015-10-13 14:13:17] Starting repair on moderately damaged ship!
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has not appeared.
[error] script stopped with error in line 349
[error] FindFailed ( can not find repair_timer.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
21: util (  check_timer )     timer_raw = find(timer_img).right(width).text()
264: combat (  go_repair )     repair_timer = check_timer(self.kc_window, 'repair_timer.png', 80)
243: main (  sortie_action )     combat_item.go_repair()
[error] --- Traceback --- end --------------
kevin@ubuntu:~$

**Comment by mrmin123** [comment]
@kevin01523 No 'repair_timer.png' on screen after clicking on moderately damaged ship??

**Comment by kevin01523** [comment]
yep i dont know why it did not get recognized just happens ones or twice a day

it was a maruyu

**Comment by kevin01523** [comment]
[2015-10-14 16:43:43] Sortie complete!
[2015-10-14 16:43:43] Focus on KanColle!
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-14 16:43:50] At Home!
[2015-10-14 16:43:50] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-14 16:43:55] No, no fleets to receive!
[2015-10-14 16:43:55] Refreshing Home!
[debug] waiting for quests_main.png to appear
[debug] quests_main.png has appeared.
[log] CLICK on L(872,169)@S(0)[0,0 1360x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(369,567)@S(0)[0,0 1360x768]
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[debug] waiting for top_menu_return.png to appear
[debug] top_menu_return.png has appeared.
[log] CLICK on L(369,567)@S(0)[0,0 1360x768]
[2015-10-14 16:44:19] At Home!
[2015-10-14 16:44:19] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-14 16:44:24] No, no fleets to receive!
[2015-10-14 16:44:24] Navigating to Repair menu!
[debug] waiting for repair_main.png to appear
[debug] repair_main.png has appeared.
[log] CLICK on L(434,480)@S(0)[0,0 1360x768]
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[debug] waiting for repair_empty.png to appear
[debug] repair_empty.png has appeared.
[log] CLICK on L(565,281)@S(0)[0,0 1360x768]
[2015-10-14 16:44:33] Check for critically damaged ships.
[2015-10-14 16:44:37] Check for moderately-damaged ships.
[debug] waiting for P(repair_dmg_moderate.png) S: 0.95 to appear
[debug] P(repair_dmg_moderate.png) S: 0.95 has appeared.
[log] CLICK on L(1045,254)@S(0)[0,0 1360x768]
[2015-10-14 16:44:38] Starting repair on moderately damaged ship!
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has not appeared.
[2015-10-14 16:45:00] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find repair_timer.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 400
[error] FindFailed ( can not find repair_timer.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
21: util (  check_timer )     timer_raw = find(timer_img).right(width).text()
264: combat (  go_repair )     repair_timer = check_timer(self.kc_window, 'repair_timer.png', 80)
250: main (  sortie_action )     combat_item.go_repair()
391: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------
kevin@ubuntu:~/kancolle-auto$ 

http://imgur.com/7g5VMJW

**Comment by mrmin123** [comment]
Hmm... @kevin01523 there are a few possible things you could do to try and alleviate this, in order of likeliness:
1. Add the line `sleep(1)` or `sleep(2)` before `repair_timer = check_timer(self.kc_window, 'repair_timer.png', 80)` - _it's possible that there's a delay/animation that's throwing off the image check here_
2. Replace repair_timer.png - _in case your repair screen looks slightly different from when I made that screenshot, but this seems unlikely???_
3. Replace the line `repair_timer = check_timer(self.kc_window, 'repair_timer.png', 80)` with `repair_timer = check_timer(self.kc_window. Pattern('repair_timer.png').similar(0.7), 80` or something lower than 0.7 - _but it's already checking only at 0.8 similarity, so I'm not sure if this will help either_ 

I haven't had an issue with the repair module in quite some time now, but I'm leaning towards 1) being the most likely solution. If not, I'd have to chalk it up to Sikuli acting up (surprise surprise)...

**addendum**: good to see that the FindFailed except catch is working properly...

**Comment by kevin01523** [comment]
hmm ok ill try it ok im thinking of now is if that kind error occured  try to go back home if cannot go back home reload then restart script or in middle of sortie while the script crashed .

**Comment by mrmin123** [comment]
Frankly, I'm kind of opposed to the idea of having the script automatically refresh kancolle whenever it has an issue. I don't think the refresh functionality should be relied on so heavily, especially considering all the things I've read about refreshes being something the devs watch out for. I also don't think it's that critical considering how rarely it crashes, at least for me (then again, that might be a biased statistic since I've only done very specific things with the script). I also believe that a lot of errors can be rectified by minor tweaks. and doesn't have to resort to a full refresh.

**Comment by kevin01523** [comment]
more ocr problems [2015-10-20 22:45:40] Starting repair on lightly damaged ship!
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has appeared.
[debug] Region.text: #(0I :04230)#
[error] script stopped with error in line 416
[error] ValueError ( invalid literal for int() with base 10: :0 )
[error] --- Traceback --- error source first
line: module ( function ) statement 
283: combat (  go_repair )     log_success("Repair should be done at %s" % (datetime.datetime.now()
256: main (  sortie_action )     combat_item.go_repair()
416: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------

**Comment by mrmin123** [comment]
That's a pretty wild OCR read. 01:04:30 to 0I :04230??? Either way, I'll push a fix for it tonight, thanks for the report.

**Comment by kevin01523** [comment]
[2015-10-27 14:51:11] Got invalid timer (0Z:14:15)... trying again!
[debug] waiting for repair_timer.png to appear
[debug] repair_timer.png has appeared.
^X[debug] Region.text: #(OZ:I4215)#
[2015-10-27 14:51:12] Got invalid timer (0Z:14:15)... trying again!
[debug] waiting for repair_timer.png to appear
^C[debug] repair_timer.png has appeared.
[debug] Region.text: #(OZ:I4215)#
kevin@LinuxMint ~/kancolle-auto $ ^C

**Comment by mrmin123** [comment]
@kevin01523 Thanks for the report, but no need to make it so verbose.

**Comment by mrmin123** [comment]
FYI the OCR issue was patched a while ago in 2988172
