### ISSUE TITLE
Multicore CPU support

### ISSUE THREAD

**Issue by mintgreenrose** [mrmin123/kancolle-auto#172]
Will this program run faster on PCs with more cores on the CPU? Or is it more RAM/faster HDD (SSD) that will make a significant difference than CPU?

**Comment by mrmin123** [comment]
That's more dependent on Sikuli's reliance on CPU/cores/RAM. I don't know the specifics, but they do seem to influence how fast Sikuli can ID image matches. I've not seen any performance testing or metrics, but this has been alluded to on the Sikuli forums by the maintainer.

Personally, I've not seen any big difference whether I run it on a 7-year-old (at the time) average laptop or a 3-year-old (at the time) top of the line gaming PC, but then again I haven't done any performance testing...
