### ISSUE TITLE
Add KC3 API link RecoveryMethod

### ISSUE THREAD

**Issue by Nuts123** [mrmin123/kancolle-auto#180]
I noticed that the catbombs do not appear in the game through the API reference which is why it became necessary to add RecoveryMethod to play through the first option in KC3 (Play via API link)

![default](https://cloud.githubusercontent.com/assets/19754506/15966590/cb21e33c-2f5e-11e6-833b-d8a5827bf7cc.PNG)

I wanted to try myself to add this feature, but do not quite understand how to get the entire screen, and pass it to the function check_and_click()

p.s. I used to programming Python, but a little

and another question: Is it possible to make a determination image Sikuli faster than it is now? Sometimes it seems that the slow bot

**Comment by mrmin123** [comment]
If you start the game in API Link mode, and reload the page, it should keep you in API Link mode. You shouldn't need to go through the menu again.

And no, I've made little tweaks to make image matching less intensive/faster, but most of it is limited by your CPU/RAM and Sikuli's processes.

**Comment by Nuts123** [comment]
> If you start the game in API Link mode, and reload the page, it should keep you in API Link mode. You shouldn't need to go through the menu again.

but API link is broken and no longer enter the game without this menu

**Comment by mrmin123** [comment]
Oh, I see. The API Link expires and doesn't reset until you go through the menu. Gotcha.

**Comment by mrmin123** [comment]
You'd have to do something like this (pseudocode):

```
myApp = App.focus(settings['program'])
kc_window = myApp.focusedWindow()
check_and_click(kc_window, {KC3_BUTTON})
check_and_click(kc_window, {IMAGE_YOU_POSTED_ABOVE}
{CODE TO HIT 'Continue Anyway' BUTTON IN MAIN WINDOW}
```

**Comment by mrmin123** [comment]
Closing this as I don't see a pressing need for it right now. Catbombs should be relatively infrequent if the bot detection isn't triggered.
