### ISSUE TITLE
Stuck in quest page

### ISSUE THREAD

**Issue by etcet54** [mrmin123/kancolle-auto#181]
- kancolle-auto version (last modified date): 4.2 (2016-06-09)
- Viewer/browser: Google Chrome
- Operating system: Win 7 x64
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [ x] Consistent
- [ ] Transient

Console log (if applicable)

![rn](https://cloud.githubusercontent.com/assets/19471603/15981301/9dcffeca-2f9d-11e6-96b4-ac89139834f3.jpg)

Hello, since the latest maintenance, there seems to be a bug for the quest checking feature, or is it just happening to me? The program will stuck waiting for menu_top_quests.png, even though it says appeared.

I've tried updating to the newest kancolle-auto version but it seems the bug still exist. The only workaround for me now is to disable quest checking.

**Comment by mrmin123** [comment]
Quest images need to be updated for the new version, yes. You'll have to disable the Quests module for the moment.

**Comment by mrmin123** [comment]
They went and changed the fonts, spacing, and positions of the icons for the quest images. This will take a while to fix, haha

**Comment by mrmin123** [comment]
These are the images that need to be regenerated:
- ~~bd1~~
- ~~bd2~~
- ~~bd3~~
- **bd4**
- ~~bd5~~
- **bd6**
- ~~bd7~~
- ~~bd8~~
- ~~bw1~~
- ~~bw2~~
- ~~bw3~~
- **bw4**
- ~~bw5~~
- **bw6**
- **bw7**
- **bw10**
- ~~c2~~
- ~~c3~~
- ~~c4~~
- **c8**
- ~~d2~~
- ~~d3~~
- ~~d4~~
- ~~d9~~
- ~~d11~~
- ~~e3~~
- ~~e4~~

If anyone can provide uncompressed png screenshots for the quests that aren't crossed out I'd appreciate it!

Current progress can be found in branch 181_quests_update

**Comment by cobeng13** [comment]
Is this related to the looping i'm getting?

```
[log] CLICK on L(1644,107)@S(0)[0,0 1920x1080]

[log] CLICK on L(1639,113)@S(0)[0,0 1920x1080]

[log] CLICK on L(1672,100)@S(0)[0,0 1920x1080]

[log] CLICK on L(1684,92)@S(0)[0,0 1920x1080]

[log] CLICK on L(1670,95)@S(0)[0,0 1920x1080]

[log] CLICK on L(1639,95)@S(0)[0,0 1920x1080]

[log] CLICK on L(1662,99)@S(0)[0,0 1920x1080]

[log] CLICK on L(1637,93)@S(0)[0,0 1920x1080]
```

**Comment by mrmin123** [comment]
Yes. Please merge in the above-mentioned branch if you want a preliminary fix for it.

**Comment by mrmin123** [comment]
Quests not yet supported as of above PR/merge:
- ~~bd4~~
- ~~bd6~~
- ~~bw4~~
- ~~bw6~~
- ~~bw7~~
- ~~bw10~~
- ~~c8~~

**Comment by mrmin123** [comment]
All quests update as of d09da1d. Can't wait for the next time they slightly tweak something again forcing me to re-do all this.
