### ISSUE TITLE
Feature Request: Switch single type of Sub

### ISSUE THREAD

**Issue by Danielosama** [mrmin123/kancolle-auto#182]
Hello, I was wondering if it is possible to add the option to tell KCAuto to only switch, for example, between Maruyus? Since for 3-2A this would save a lot of time.
Thank you for your time

**Comment by mrmin123** [comment]
I think if you replace `fleetcomp_shiplist_submarine.png` and `fleetcomp_shiplist_submarine_available.png` with this image:

![image](https://cloud.githubusercontent.com/assets/4326866/15986735/6f070ff8-2fc4-11e6-9701-f7cdad82071c.png)

it should theoretically work.

**Comment by mintgreenrose** [comment]
Nice, i could really use this to only switch between dupe Yuus

**Comment by Danielosama** [comment]
Tried it, and it worked great, thanks!

**Comment by mrmin123** [comment]
@Danielosama Great!

@mintgreenrose If you generate the same type of image for Yuu from the shiplist like above, it should work. I'm on the fence about incorporating the ability to specify which sub to focus on into kancolle-auto since it seems like a very specific per-player use case.

**Comment by Danielosama** [comment]
@mrmin123  Might as well at least add the option for Maruyu and U-511/Ro-500, one for it's low repair time, and the other for it's high evasion. Just my thoughts though, this tool is already incredible as it is now :p

**Comment by mrmin123** [comment]
@Danielosama I'll incorporate it once I level my U-511 to a Ro-500 lol

**Comment by TwintailsMiku** [comment]
Going by that logic, I tried to exclude SSV with this image.

![fleetcomp_shiplist_submarine_available](https://cloud.githubusercontent.com/assets/17616329/16740810/f1eed152-475d-11e6-9059-fda1bbc3e709.png)

I'm doing 3-2A grinding so I have a full page of normal subs but when one sub is damaged, it doesn't replace the sub anymore. It just examines the damaged sub at the select ships and then dies.

**Comment by mrmin123** [comment]
Revised sub switch module is working. Valid values for the new `EnabledSubs` config line are `all`, `i-8`, `i-19`, `i-26`, `i-58`, `i-168`, `maruyu`, `ro-500`, and `u-511`. Multiple selections should be comma separated. `all` ONLY switches SS's (no SSVs and no Sub Tenders)
