### ISSUE TITLE
Last catbomb and refresh was a very short time ago

### ISSUE THREAD

**Issue by Nuts123** [mrmin123/kancolle-auto#183]
This is not a bug report. Maybe you should delete it? For those people who are faced with a large number of cats it can be a problem

![image](https://cloud.githubusercontent.com/assets/19754506/15987451/a6a5da76-3031-11e6-8980-c1da06f062f0.png)

I also noticed that the bot again gets time from the menu after katbomb expeditions, but he knew time before (I think the reason is a function _init()_ )

**Comment by mrmin123** [comment]
Right, someone mentioned something about this previously as well, saying that it was pretty pointless in practice. I'll remove it in the next update.

**Comment by Nuts123** [comment]
> I also noticed that the bot again gets time from the menu after katbomb expeditions, but he knew time before (I think the reason is a function init() )

what about this?

**Comment by mrmin123** [comment]
The re-`init()` post-catbomb recovery is because kancolle-auto doesn't necessarily know where in its programming the catbomb occurred. The safest way for it to recover the program itself is to re-initialize after the fact.

**Comment by Nuts123** [comment]
pity, that nothing can be done with preservation time, but thank you
