### ISSUE TITLE
[bug] Stop after a reboot

### ISSUE THREAD

**Issue by Nuts123** [mrmin123/kancolle-auto#184]
### Environment details
- kancolle-auto version (last modified date): c99c22b
- Viewer/browser: Google Chrome (KC3)
- Operating system: Windows 7
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [ ] Consistent
- [x] Transient

![default](https://cloud.githubusercontent.com/assets/19754506/16028404/a94e052a-31e7-11e6-9195-b0d1445e55ce.PNG)

sometimes after refresh bot stops when bot hover the cursor at game start

I tried to add a delay, but it did not help

![image](https://cloud.githubusercontent.com/assets/19754506/16033566/a9b6e030-3247-11e6-995c-67445bdd56bb.png)
#### Console log (if applicable)

```
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] TYPE "#F5."
[log] TYPE " "
[log] TYPE "#TAB."
[log] TYPE " "
[log] CLICK on L(765,475)@S(0)[0,0 1366x768]
```

**Comment by Nuts123** [comment]
Hmm, I kind of solved the problem, but need more time. If all goes well, I will write a  solution.

**Comment by Nuts123** [comment]
No, this does not solve problem

**Comment by Nuts123** [comment]
UPD:

I found that the problem occurs if the cursor is where the button is, at the time of refresh. Infinite loop: 

![image](https://cloud.githubusercontent.com/assets/19754506/16033622/fc9951f2-3247-11e6-86cd-edcb78325143.png)

Seems I solved the problem with this code:

![image](https://cloud.githubusercontent.com/assets/19754506/16033590/ccad76b2-3247-11e6-9b4d-7ad93c1ef431.png)

fubuki.png
![image](https://cloud.githubusercontent.com/assets/19754506/16033602/d8dc1a38-3247-11e6-863c-702b3d38fe7b.png)

**Comment by mrmin123** [comment]
Thanks for the proposed fix. I'm actually going to use a `rejigger_mouse` call to get the mouse off the button.
