### ISSUE TITLE
script crashes on windows 7 trying to continue ongoing quests

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#19]
#14 this issue still happens i dont know why it happens on windows 7ocr works but still crashes

**Comment by mrmin123** [comment]
OK, it might be an issue with line endings or indentation... Try this... c6be709020a9e2489c0c230fc4afc2b8756aa2c4

**Comment by kevin01523** [comment]
```
[debug] waiting for expedition_timer.png to appear
[debug] expedition_timer.png has appeared.
[error] TextRecognizer: init: tessdata folder not found at D:/sikuli/libs/
[error] Region.text: text recognition is now switched off
[error] script stopped with error in line 304
[error] AttributeError ( Ensei instance has no attribute 'check_later' )
[error] --- Traceback --- error source first
line: module ( function ) statement
201: main (  run_expedition )     expedition.check_later(int(expedition_timer[0:
2]), int(expedition_timer[3:5]))
286: main (  init )     run_expedition(expedition)
[error] --- Traceback --- end --------------
```

nope still the same i wonder whats wrong

**Comment by mrmin123** [comment]
I moved the methods around a bit to try and narrow down the problem: f8f029f89e28bde2af81f8bad79ff0794ffc1645

**Comment by kevin01523** [comment]
nope still the same but i tested w/ the latest build of 1.1.0 although i had to copy the sikuli folders outside or else i get cannot find module named error(although it worked for previous versions of 1.1.0 and 1.0.1  and for the ide
when im testing my mod to yuukarins  repo) and it works

**Comment by kevin01523** [comment]
ok i tried moving the script inside the sikuli folder on D:Sikulix
and what a surprise it worked i guess its one of sikulis annoying bugs well i got the idea from here https://answers.launchpad.net/sikuli/+question/191858

**Comment by mrmin123** [comment]
That is really weird... good job and thanks for figuring that out!
