### ISSUE TITLE
Access Denied During Launch

### ISSUE THREAD

**Issue by moonlee7777** [mrmin123/kancolle-auto#190]
I entered the launch command with the correct directories into cmd, both administrator and nonadmin, but it still doesnt work.

**Comment by mrmin123** [comment]
I'm going to need more information to help you debug. What was the error you saw, if any? What OS? What was the command you used?

**Comment by moonlee7777** [comment]
java -jar <path_to_sikuli>/sikuli-script.jar -r <path_to_kancolle_auto>/kancolle_auto.sikuli

This one, and it just said Access Denited. Windows 10.
![capture](https://cloud.githubusercontent.com/assets/20227203/16505775/98a50702-3eec-11e6-8443-c58542d2d5c6.PNG)

**Comment by silfumus** [comment]
I don't think you need include the <>.

**Comment by moonlee7777** [comment]
...now it works. Time to kill myself

Thanks

**Comment by moonlee7777** [comment]
okay, but now I get a different error about sikuliX having a fatal error

**Comment by silfumus** [comment]
We can't diagnose it without more information, you know.

**Comment by moonlee7777** [comment]
![capture](https://cloud.githubusercontent.com/assets/20227203/16506554/430cb236-3ef1-11e6-9926-aff2847d903b.PNG)

This is it.

**Comment by mrmin123** [comment]
It says in the error message to logout and login. That is exactly what you need to do. Your system was updated by Sikuli but the changes won't take effect until you re-Login.

**Comment by moonlee7777** [comment]
Ohh. Thanks.

**Comment by mrmin123** [comment]
NP. Guessing that this is resolved, so closing.
