### ISSUE TITLE
Feature Request: Stop after X Hours or X Number of sorties.

### ISSUE THREAD

**Issue by Danielosama** [mrmin123/kancolle-auto#191]
Hello again!
I was wondering if it was possible to add an option to tell the script to stop after a given amount of time/sorties?
Thanks for your time and your work!

**Comment by mrmin123** [comment]
Note to self:
- `ScheduledStop`
- Use existing `done_expeditions`, `done_sorties`, `done_pvp` counters for action-dependent stops
- Generate stop time on start for timer-dependent stops
