### ISSUE TITLE
[Bug] I think I found an actual submarine bug this time

### ISSUE THREAD

**Issue by dice4321** [mrmin123/kancolle-auto#192]
#### Environment details
- kancolle-auto version (last modified date): Latest as of 7/04
- Viewer/browser: Google Chrome / KV3
- Operating system: Windows 10 64bit
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [ ✓ ] Consistent
- [ ] Transient

I dont know if you guys are having the same problem or its just me. Anyways when kancolle-auto is about to switch the submarine after the repair, it just goes pass the page. I have about 15 submarines on the first and 2nd page and it doesn't even pick one, instead it cycles through the rest of the pages and just saids everything is in repair, even if I have a 2nd repair doc open.

http://i.imgur.com/R9dNa1Q.png

What I did to fix it was replace the images `fleetcomp_shiplist_submarine.png` and `fleetcomp_shiplist_submarine_available.png` with my own 

![fleetcomp_shiplist_submarine](https://cloud.githubusercontent.com/assets/20022859/16590039/bb0ae324-428a-11e6-929d-cc0fff2c4b81.png)

![fleetcomp_shiplist_submarine_available](https://cloud.githubusercontent.com/assets/20022859/16590050/c483ac38-428a-11e6-8748-d60d1696fac5.png)

and it worked! Just a fix if you guys are having the same problem as I am!

**Comment by silfumus** [comment]
I recall there's some font changes after the last maintenance.
Maybe that's what causing the problem.

**Comment by mrmin123** [comment]
Thanks for the report and fix. @diceman112 can you make a PR with the proposed changes? If you're not familiar/comfortable doing that don't worry about it.

**Comment by dice4321** [comment]
The deed is done!
