### ISSUE TITLE
unable to access jarfile e:\sikuli/sikuli-script.jar

### ISSUE THREAD

**Issue by lainconnue** [mrmin123/kancolle-auto#195]
I was trying to run kancolle auto for the first time after setting up the config when this happened.
![image](https://cloud.githubusercontent.com/assets/20400916/16752642/1445df8c-481e-11e6-9671-d871f10bb438.png)
I googled and looked for solutions to this problem.
Complete newbie as in don't know anything about coding. I have googled around and i tried following the instructions on this site https://answers.launchpad.net/sikuli/+question/236586. My sikuli folder looks like this now 
![image](https://cloud.githubusercontent.com/assets/20400916/16752685/844d5044-481e-11e6-979f-e7a6dea06d4a.png)
I tried to set up sikuli again but the set up window won't show up. The command prompt quickly opens and close so i don't know what happened (doesn't matter how many times i do it).

The only backup i have is the original winrar from sikuli's website which i placed in another folder, 
![image](https://cloud.githubusercontent.com/assets/20400916/16752731/deee5840-481e-11e6-8f8a-b6f891479e3c.png)

Additional info: my kancolle auto folder looks like this (i did not do anything to this folder.
![image](https://cloud.githubusercontent.com/assets/20400916/16752752/157dd4a8-481f-11e6-8f20-29fbed7edad0.png)
I am play kancolle via google chrome kc3 kai.

Very sorry to trouble you guys with this problem, i should have posted this problem earlier and not tried doing the fix myself.

**Comment by n0k0m3** [comment]
Welp the problem is in your file location
e:\sikuli\sikuli-script.jar not e:\sikuli/sikuli-script.jar
The difference between / and \ is significant, and btw, whenever you wanna
try any location, type it in explorer.

On Tue, Jul 12, 2016 at 8:59 AM, lainconnue notifications@github.com
wrote:

> I was trying to run kancolle auto for the first time after setting up the
> config when this happened.
> [image: image]
> https://cloud.githubusercontent.com/assets/20400916/16752642/1445df8c-481e-11e6-9671-d871f10bb438.png
> I googled and looked for solutions to this problem.
> Complete newbie as in don't know anything about coding. I have googled
> around and i tried following the instructions on this site
> https://answers.launchpad.net/sikuli/+question/236586. My sikuli folder
> looks like this now
> [image: image]
> https://cloud.githubusercontent.com/assets/20400916/16752685/844d5044-481e-11e6-979f-e7a6dea06d4a.png
> I tried to set up sikuli again but the set up window won't show up. The
> command prompt quickly opens and close so i don't know what happened
> (doesn't matter how many times i do it).
> 
> The only backup i have is the original winrar from sikuli's website which
> i placed in another folder,
> [image: image]
> https://cloud.githubusercontent.com/assets/20400916/16752731/deee5840-481e-11e6-8f8a-b6f891479e3c.png
> 
> Additional info: my kancolle auto folder looks like this (i did not do
> anything to this folder.
> [image: image]
> https://cloud.githubusercontent.com/assets/20400916/16752752/157dd4a8-481f-11e6-8f20-29fbed7edad0.png
> I am play kancolle via google chrome kc3 kai.
> 
> Very sorry to trouble you guys with this problem, i should have posted
> this problem earlier and not tried doing the fix myself.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/mrmin123/kancolle-auto/issues/195, or mute the thread
> https://github.com/notifications/unsubscribe/AKa08rvNJ5w9wEsMMDIt9htwOu_GMvr8ks5qUvTtgaJpZM4JJ92B
> .

## 

Minh Nguyen
B.S. Biochemistry
Florida Institute of Technology - Biological Sciences
150 W. University Blvd.
Melbourne, FL, 32901
Phone Number: 321-368-9310

**Comment by lainconnue** [comment]
![image](https://cloud.githubusercontent.com/assets/20400916/16753759/73eb7b28-4827-11e6-99dd-c6ee3e3c8459.png)

Most likely due to me tempering with the folder, but the error still persists. I can't go to sikuli set up (the one where you choose options 1-6), command prompt opens and closes rapidly, i can't print screen the image.

**Comment by mrmin123** [comment]
You're trying to run `sikuli-script.jar`, but that file no longer exists in the last screenshot you posted. In the screenshot in the OP, the file exists. Not sure what you're doing exactly, but I advise reinstalling Sikuli.

**Comment by lainconnue** [comment]
yes, it seems i have reinstalled incorrectly. i can't seem to reinstall to before when i still do have the file. I deleted all the files in that folder except for jre windows x64  i read something about rechoosing options from the sikuli set up window, but again following these steps
http://nadimsaker.blogspot.my/2015/02/sikuli-how-to-install-and-run-sikuli-in.html

the problem seems to be at step 3.
i downloaded from the site (it was a winrar file)
![image](https://cloud.githubusercontent.com/assets/20400916/16754699/16d45064-4830-11e6-8f4d-44edabb8acfe.png)

, extracted the files to sikulis folder
![image](https://cloud.githubusercontent.com/assets/20400916/16754706/305db2fa-4830-11e6-9db3-bf1ef16d6f7b.png)
, then i opened folder commands>windows and double clicked runSetup
![image](https://cloud.githubusercontent.com/assets/20400916/16754717/5cb1826e-4830-11e6-864e-ed93048182e5.png)
 but nothing happens except that command prompt opened and closed on its own (too fast to print screen its content)
![image](https://cloud.githubusercontent.com/assets/20400916/16754733/861c8162-4830-11e6-90a6-42559d273926.png)
.

What does this mean?

**Comment by mrmin123** [comment]
sikuli-setup should be running as an executable file, NOT an extractable archive. The way you're going about it right now, you're not installing sikuli at all... Do you have Java installed? That'd be the first thing I'd check.

Either way, this is more of an issue with getting sikuli up and running, and I'm afraid I currently don't have time to help you with this... Feel free to re-open this or open another ticket once you have Sikuli running and you have issues getting kancolle-auto to run on it.

**Comment by lainconnue** [comment]
yes i have it installed, when i click on jre it says::"You have already installed this software, do you want to reinstall it?" It's okay, sorry to trouble you with my problems since i've been through websites without much results i will keep on trying to install sikuli. Thank you very much have a nice day.
