### ISSUE TITLE
Command prompt clash

### ISSUE THREAD

**Issue by eee7112542** [mrmin123/kancolle-auto#202]
#### Environment details
- kancolle-auto version (last modified date): 4.3 (18 JUL 16)
- Viewer/browser: KanColleViewer!
- Operating system: Window 8.1

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? 
-  Consistent

[description of issue here, along with any screenshots and/or videos]
Command prompt clash after trying to run the script.
![auto problem](https://cloud.githubusercontent.com/assets/20514650/16911304/a22b9c48-4d18-11e6-894b-4c117c0a07cd.png)
This is what I can take before it close down in the next second.

**Comment by mrmin123** [comment]
Something wrong with your config. Post your config here.

**Comment by eee7112542** [comment]
![auto problem 2](https://cloud.githubusercontent.com/assets/20514650/16934282/a5d147a4-4d8f-11e6-8653-d198ccf95e59.png)
here it is.

**Comment by silfumus** [comment]
You're not supposed to delete any content of the config file.

**Comment by eee7112542** [comment]
![auto problem 3](https://cloud.githubusercontent.com/assets/20514650/16934574/6feb456a-4d92-11e6-933b-676cd90f0626.png)
like this? I thought it just a warning text so I deleted it.

**Comment by eee7112542** [comment]
![auto problem 4](https://cloud.githubusercontent.com/assets/20514650/16934613/ed738236-4d92-11e6-9d7c-92e45c8e085f.png)
Now I got a new problem instead T_T

**Comment by mrmin123** [comment]
Nothing is 'optional' in the config in the sense that you can't delete non-comment lines willy-nilly like that. If you want to turn a module off, you set it to Off, but you have to explicitly say it's off.

No idea about your new error. Multi-monitor setup? Sikuli only supports the first/primary monitor.

Closing as this isn't a kancolle-auto issue.

**Comment by silfumus** [comment]
Try using wordpad or third-party program like notepad++.
Then you could properly see the config file, something like this: https://raw.githubusercontent.com/mrmin123/kancolle-auto/master/config.ini

**Comment by eee7112542** [comment]
Ok, figured out I need to stay away from my computer to let it work lol. One final question, how should I setup my game screen size to match kancolle-auto? I'm using Gakada's KCV and don't know how should I set it.

**Comment by mrmin123** [comment]
I haven't used that viewer myself so I'm not sure but maybe in the settings somewhere? Hitting Ctrl + 0 might reset the size, too.
