### ISSUE TITLE
Add support for 2016 Summer Event

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#208]
As usual, I'll probably be getting a late start on this event... Please post panel images or node images here and I'll try to add them to assets sooner rather than later.

Please refer to #161 for the past event.

**Comment by stackhanovets** [comment]
If you're looking for map banners, wiki can help: 
http://en.kancollewiki.net/wiki/Summer_2016_Event

**Comment by BeemoLin** [comment]
When LBAS Enable set False in `config.ini`
`config_reader.py`.`settings['combat_enabled']` not define, it will crash for me.

**Comment by mrmin123** [comment]
@BeemoLin merged in your PR for that issue.

**Comment by joejoejoe3652** [comment]
I would like to help, but not sure how. I only cleared the first 2 maps; do you want pictures for those?

**Comment by mrmin123** [comment]
@joejoejoe3652 No, that's fine. I managed to beat those two myself so I have assets up to the third map. The thing I'm missing is the next page button to get to E4, and any node select and LBAS node select images for E4. The E4 panel image I think I can grab from the wiki @stackhanovets mentioned above.

**Comment by AppleBoi86** [comment]
Here's E-3 LBAS node selection image for Aquila farming.
**Recommended to clear E-3 first for the extra LBAS squad before farming. 
1 on Air Defense, 2 on Sortie to H node.** _Who loves BB Hime anyways?_

_node_lbas_E-3-H_1.png
imgur.com/dLLJGN9

_node_lbas_E-3-H_2.png
imgur.com/vpdWDb7

_event_panel_1-3.png
imgur.com/pWAD6UO

---

**During Air Raid on your AB,  an extra click to pass Harbour Hime's dialog screen if she is present.**

**Comment by BeemoLin** [comment]
@AppleBoi86 
Some time can't click node right position, the problem is when I capture the node image range to large, so I capture image range like this.
http://i.imgur.com/K5Rga9w.png

**Comment by mrmin123** [comment]
@BeemoLin I noticed that too, but I'm leaning towards narrowing the `node_select` in `expand_areas`. That way, we can still use the 70x70 image for more accurate image matching, but click more in the center area.

**Comment by mrmin123** [comment]
Lots of untested changes here in branch [208_summer_event](https://github.com/mrmin123/kancolle-auto/tree/208_summer_event).

Changes include:
- Added E-3 LBAS node images
- Added ability to sortie to E-4
- Code changes to better check damage states during sorties (#215)
- Added support for expeditions 189 and 190 (Event pre-boss and boss node support)
- Revised `expand_areas` for nodes to improve LBAS node selection accuracy

**Comment by mrmin123** [comment]
Forgot to say this earlier but @AppleBoi86 thanks for the images!

**Comment by mrmin123** [comment]
[208_summer_event](https://github.com/mrmin123/kancolle-auto/tree/208_summer_event) is pretty much ready to get merged into dev. Lots of tweaks were required from the previous un-tested version. New features were also added.
- Node selection images for E-4 and E-4 node I LBAS target images added
- Expeditions 189 and 190 confirmed to be working properly
  - Tweaked so that kancolle-auto automatically resupplies them after sortie is complete
- LBAS resupply and and combat confirmed working
  - Now supports LBAS groups that have no node targeted but is still active for resupply (air defense)
  - Patched config reader
  - Tweaked timings in both methods
  - Added console messages for both methods

### Found potential cause of ship loss in #215: If KC3Kai is being used w/ subtitles, the subtitles can cover up the damage portrait for the last ship in fleet during the post-combat results screen. Subtitles must be disabled or the subtitle size reduced to <13px!!

**Comment by mrmin123** [comment]
I believe this event is fully supported now as of [release r5](https://github.com/mrmin123/kancolle-auto/releases/tag/5) but I'm going to keep this open for a few more days for event-related bugs or requests.
