### ISSUE TITLE
Could not find Kancolle Homepage

### ISSUE THREAD

**Issue by Danielosama** [mrmin123/kancolle-auto#219]
#### Environment details
- kancolle-auto version (last modified date): Latest version
- Viewer/browser: Google Chrome
- Operating system: Windows 10
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [X ] Consistent
- [ ] Transient

Hello, I am trying to use the script on a Microsoft Surface. I've installed everything and launched the script, however, even though it brings forward the Chrome window, it is unable to find the homepage for some reason.
I've attached a screenshot of the screen where I launch the script.
#### Console log (if applicable)

```
[C:\SikuliX>java -jar sikuli-script.jar -r C:\SikuliX\kancolle_auto.sikuli
ago 21, 2016 12:24:19 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[94m[2016-08-21 00:24:30] Reading config file[0m
[92m[2016-08-21 00:24:30] Expeditions (fleet 2: 2, fleet 3: 5, fleet 4: 21) enabled![0m
[92m[2016-08-21 00:24:30] Combat enabled![0m
[92m[2016-08-21 00:24:30] Config loaded![0m
[94m[2016-08-21 00:24:30] Reading config file[0m
[92m[2016-08-21 00:24:30] Starting kancolle_auto[0m
[94m[2016-08-21 00:24:30] Finding window![0m
[94m[2016-08-21 00:24:30] Focus on KanColle![0m
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[log] App.focus Google Chrome(0) #0
[91m[2016-08-21 00:26:09] Could not find Kancolle homepage after 10 attempts. Exiting script.[0m
[info] Exit code: 0]
```

**Comment by silfumus** [comment]
Are you sure it was zoomed at 100%?

**Comment by Danielosama** [comment]
@silfumus Yes, that is the first thing I made sur of.

**Comment by silfumus** [comment]
Judging from the screenshot, that wasn't the case.
The KanColle area should be 800x480 yet on your screenshot it was 1200x720 (or 150% magnification).

**Comment by Danielosama** [comment]
@silfumus The screenshot has been cut to hide my API, so, unless Chrome is lying to me, it is zommed at 100%.

**Comment by silfumus** [comment]
Or try zooming to 67%. It might work, kamo.

**Comment by mrmin123** [comment]
@Danielosama as @silfumus your game window is at the wrong size. The game resolution must be 800x480 for Sikuli/kancolle-auto to work. Chrome might say 100% magnification but the pixel count is what's important, and that's clearly off. There might be some OS-level magnification happening because you're on a Surface?? Try hitting Windows+- a few times...

**Comment by Danielosama** [comment]
@mrmin123 After looking for a bit, there was indeed a 150% OS-level magnification. However, even when fixing it at 100%, I still get the same error :/
Here is a screenshot with both zooms at 100%

**Comment by mrmin123** [comment]
Just play around with the zooms until you get the window size you need.

**Comment by mrmin123** [comment]
@Danielosama Upon closer examination that window IS the right size, and there's a perfect match for `menu_main_home.png`... dunno why it's still flipping out...

**Comment by mrmin123** [comment]
Are you on the latest release? If so, could you replace this line in `kancolle_auto.py`:

``` python
# debug_find('dmg_critical.png', 'Chrome', 0.75)  # For debugging purposes only!
```

to (notice it's not a comment anymore)

``` python
debug_find('menu_main_home.png', 'Chrome', 0.8)  # For debugging purposes only!
```

and try running the script again? Paste the results here please.

**Comment by Danielosama** [comment]
Well this is weird, up until now I was trying directly through the DMM site (on Chrome), since it was not working, I decided to try a Kancolle web proxy (OOI la foret, still on Chrome) and this time, it does find the window, but the script seems unable to click (I was watching it, and the cursor moved, but did not click anything).

**Comment by Danielosama** [comment]
```
C:\SikuliX>java -jar sikuli-script.jar -r C:\SikuliX\kancolle_auto.sikuli
ago 21, 2016 2:49:33 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...)
eturned error code 5.
[94m[2016-08-21 02:49:58] Reading config file[0m
[92m[2016-08-21 02:49:58] Expeditions (fleet 2: 2, fleet 3: 5, fleet 4: 21) enabled![0m
[92m[2016-08-21 02:49:58] Combat enabled![0m
[92m[2016-08-21 02:49:58] Config loaded![0m
[94m[2016-08-21 02:49:58] Reading config file[0m
[92m[2016-08-21 02:49:58] Starting kancolle_auto[0m
[94m[2016-08-21 02:49:58] Finding window![0m
[94m[2016-08-21 02:49:58] Focus on KanColle![0m
[log] App.focus Google Chrome(0) #0
[94m[2016-08-21 02:50:31] Defining module items![0m
[94m[2016-08-21 02:50:31] Focus on KanColle![0m
[log] App.focus Google Chrome(0) #0
[92m[2016-08-21 02:51:03] At Home![0m
[94m[2016-08-21 02:51:03] Checking for returning expeditions![0m
[94m[2016-08-21 02:51:03] Are there returning expeditions to receive?[0m
[94m[2016-08-21 02:51:06] No, no fleets to receive![0m
[94m[2016-08-21 02:51:07] Refreshing home with 1 or less sidestep(s)![0m
[log] CLICK on L(874,297)@S(0)[0,0 3240x2160]
[91m[2016-08-21 02:51:48] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer![0m
FindFailed: can not find menu_side_home.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 383
[error] FindFailed ( can not find menu_side_home.png on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(JythonScriptRunner.java:326)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScriptRunner.java:290)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunner.java:200)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunner.java:162)
        at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)
```

Edit: This is what I get with Ooi la foret.

**Comment by Danielosama** [comment]
@mrmin123  I did what you said (DMM site on Chrome), here is the result:

```
C:\SikuliX>java -jar sikuli-script.jar -r C:\SikuliX\kancolle_auto.sikuli
ago 21, 2016 3:11:02 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...)
eturned error code 5.
[log] App.focus Chrome(0) #0


+  Sikuli match object for 'menu_main_home.png' in window 'Chrome'
+    with minimum similarity of 0.8:
M[781,140 12x12]@S(S(0)[0,0 3240x2160]) S:0,98 Target:787,146


[error] script stopped with error in line 382
[error] Could not evaluate error source nor reason. Analyze StackTrace!
[error] Traceback (most recent call last):
  File "C:\SikuliX\kancolle_auto.sikuli\kancolle_auto.py", line 382, in <module>
    debug_find('menu_main_home.png', 'Chrome', 0.8)  # For debugging purposes only!
  File "C:\SikuliX\kancolle_auto.sikuli\util.sikuli\util.py", line 627, in debug_find
    raise SystemExit
SystemExit
´´´´
```

**Comment by silfumus** [comment]
Try increasing the sleepmodifier in config, to 1 or 3.

**Comment by Danielosama** [comment]
@silfumus The sleepmodifier is at 5 already (it is the default value I always put), and as I said, I watched the script unfold, the cursor moved, but did not click :/

**Comment by mrmin123** [comment]
The debug command reports a successful match in your browser so I can't think of a reason off the top of my head as to why it's looping there... I wonder if the fact that you're on a Surface affects anything. I recently switched my kancolle laptop from Ubuntu to Win10 and it's working fine, but that laptop doesn't have anything like a touch screen on it. It might also be worth a try to look at [this post](https://github.com/mrmin123/kancolle-auto/issues/211#issuecomment-239823767) and seeing if the fix suggested there helps at all.

**Comment by Danielosama** [comment]
@mrmin123 Well, I tried with the DMM site on Internet Explorer, and the script had no problem finding the homepage, however, it seems the clicks don't go through for som reason, and I think I know why. My Surface's resolution is 2160x1440, however, on the script log it shows this: 

```
[log] CLICK on L(874,297)@S(0)[0,0 3240x2160]
```

It seems to be identifying a wrong resolution, coud that be the problem?

**Comment by silfumus** [comment]
Hint: 3240x2160 is 150% of 2160x1440.
So I suppose you should go to control panel and meddle with the os' magnification settings.

**Comment by Danielosama** [comment]
@silfumus @mrmin123  Welp, now I feel like the most stupid person in the world...
Turned off and on the Surface, now it works perfectly (facepalm). My guess is the 100% scaling did not take effect until I reset the Surface, even though the script was able to find the homepage.
Anyways, thanks a lot for the help, and sorry for all of this :x

**Comment by stackhanovets** [comment]
@Danielosama, 
<sub><sup>Please inform us if you were banned. We should know Kadokawa's staff is reading GitHub. </sup></sub>

**Comment by Danielosama** [comment]
@stackhanovets What makes you think I was banned? This conversation has absolutely nothing to do about that Oo

**Comment by mrmin123** [comment]
@Danielosama maybe @stackhanovets means in regards to the future, since you posted screenshots with your in-game name here (feel free to remove those pictures).

Either way, glad you got it sorted out.

**Comment by Danielosama** [comment]
@mrmin123 Ah I see, I will delete them now.
@stackhanovets My bad, I misunderstood your commentary.
