### ISSUE TITLE
Port Check questions

### ISSUE THREAD

**Issue by mintgreenrose** [mrmin123/kancolle-auto#220]
Can the 15 minute timeout of Port Check be changed?

Is there a way for Port Check to retain a specific ship and scrap the rest?

Thanks for the latest updates!

**Comment by mrmin123** [comment]
@mintgreenrose yes. You want to find these blocks in `combat.py`:

``` python
        if self.port_check:
            if self.kc_region.exists('combat_start_warning_shipsfull.png'):
                log_warning("Port is full! Please make some room for new ships! Sortie cancelled!")
                self.next_sortie_time_set(0, 15, 5)
                return (continue_combat, False)
```

``` python
        if self.area_num == 'E':
            if self.kc_region.exists('combat_start_warning_shipsfull_event.png'):
                log_warning("Port is full for event! Please make some room for new ships! Sortie cancelled!")
                self.next_sortie_time_set(0, 15, 5)
                return (continue_combat, False)
```

and change the value in the `self.next_sortie_time_set()` method call. The first parameter is hours, second is minutes, and the third is the 'flex', which varies the minutes by the number you provide.

Port check will not check for or scrap ships, nor will that feature be added.

**Comment by mrmin123** [comment]
To clarify, port checking for ships and scrapping will not be implemented because it would be way too much work to implement and maintain. Sorry.
