### ISSUE TITLE
Better (optional) mid-command recovery

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#224]
There are a lot of instances when the script will stop because of a pop-up on the browser that prohibits clicks from getting through (DMM popup, KC3Kai exit confirmation popup if it is enabled). It might be possible to implement something that allows for better recovery in these scenario.

**Comment by BeemoLin** [comment]
When script has too many thing need to do, the every battle will do long time maybe. Because I can control the sudden incident, so process speed is important to me, But it is great idea!

**Comment by mrmin123** [comment]
@BeemoLin This feature only kicks in when the script actually crashes due to a `FindFailed` or when the script begins to infinitely loop (stuck in a `while` loop, trying to click away with no avail), so there shouldn't be a performance hit.

**Comment by mrmin123** [comment]
PR is merged. Ran for a few days and it seems stable.
