### ISSUE TITLE
Feature Request: Fleet Command Facility Support

### ISSUE THREAD

**Issue by stackhanovets** [mrmin123/kancolle-auto#228]
Hi all!
Wow, that was an awesome event, thanks to @mrmin123 ! I've got a bunch of new ships now, but the most interesting is this one:

![1](https://cloud.githubusercontent.com/assets/16455270/18111675/43fa2192-6f2a-11e6-812d-b9bf7627096d.jpg)

Ooyodo's remodel grants an outstanding feature:
http://kancolle.wikia.com/wiki/Fleet_Command_Facility
As you see, using it causes a different screen:

![latest](https://cloud.githubusercontent.com/assets/16455270/18111839/72939776-6f2b-11e6-8b98-5ed2415ed8a6.png)

You can watch the whole process: 
https://youtu.be/jUGivLdvn18

Are there ways to apply **kancolle-auto** with it?

**Comment by mrmin123** [comment]
@stackhanovets Good news: FCF support already exists! If you set `CombinedFleet` to `True` in the Combat module, and the FCF screen comes up, kancolle-auto will automatically make a decision based on the number of critically-damaged ships you have.

**Comment by stackhanovets** [comment]
@mrmin123 Oh, sounds good! Looks like I've never saw that in Changelog, my bad. Thank you!

![anime kantai collection shimakaze rabbit plush pendants keychain cut soft stuffed doll 14cm](https://cloud.githubusercontent.com/assets/16455270/18123427/712adc96-6f76-11e6-9716-c67d81f54be2.jpg)
