### ISSUE TITLE
more exped cannot find image

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#24]
kevin@ubuntu:~$ java -jar /home/kevin/SikuliX/sikuli-script.jar -d 2 -r /home/kevin/kancolle-auto/kancolle_auto.sikuli
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
[debug] Running on Java 7 (1.7.0_79-b14)
[debug] ResourceLoaderBasic: check: we are running on arch: i386
[debug] ResourceLoaderBasic: check: using Java at: /usr/lib/jvm/java-7-openjdk-i386/jre/
[debug] Screen: initScreens: basic initialization (1 Screen(s) found)
[2015-10-07 00:08:42] Reading config file
[2015-10-07 00:08:42] Config loaded!
[2015-10-07 00:08:42] Starting kancolle_auto
[2015-10-07 00:08:42] Focus on KanColle!
[log] App.focus Google Chrome(0) #0
[log] switchApp: Google Chrome
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-07 00:08:49] At Home!
[2015-10-07 00:08:49] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-07 00:08:53] No, no fleets to receive!
[2015-10-07 00:08:53] Refreshing Home!
[debug] waiting for supply_main.png to appear
[debug] supply_main.png has appeared.
[log] CLICK on L(620,348)@S(0)[0,0 1350x665]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(614,383)@S(0)[0,0 1350x665]
[2015-10-07 00:08:59] At Home!
[2015-10-07 00:08:59] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-07 00:09:03] No, no fleets to receive!
[2015-10-07 00:09:03] Navigating to Expedition menu!
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(742,393)@S(0)[0,0 1350x665]
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[log] CLICK on L(1216,363)@S(0)[0,0 1350x665]
[debug] waiting for expedition_screen_ready.png to appear
[debug] expedition_screen_ready.png has appeared.
[2015-10-07 00:09:11] Let's send an expedition out!
[debug] waiting for ensei_area_05.png to appear
[debug] ensei_area_05.png has appeared.
[debug] waiting for ensei_area_05.png to appear
[debug] ensei_area_05.png has appeared.
[log] CLICK on L(910,561)@S(0)[0,0 1350x665]
[debug] waiting for ensei_name_38.png to appear
[debug] ensei_name_38.png has appeared.
[debug] waiting for ensei_name_38.png to appear
[debug] ensei_name_38.png has appeared.
[log] CLICK on L(839,448)@S(0)[0,0 1350x665]
[debug] waiting for expedition_timer.png to appear
[debug] expedition_timer.png has appeared.
[debug] OCR data path: /usr/local/share/
[debug] TextRecognizer: inited.
[debug] Region.text: #(00:09:26)#
[2015-10-07 00:09:31] Expedition is already running: Expedition 38 (ETA 2015-10-07 00:19:31)
[2015-10-07 00:09:31] Let's send an expedition out!
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[log] CLICK on L(678,560)@S(0)[0,0 1350x665]
[debug] waiting for ensei_name_05.png to appear
[debug] ensei_name_05.png has appeared.
[debug] waiting for ensei_name_05.png to appear
[debug] ensei_name_05.png has appeared.
[log] CLICK on L(841,418)@S(0)[0,0 1350x665]
[debug] waiting for expedition_timer.png to appear
[debug] expedition_timer.png has appeared.
[debug] Region.text: #(00:48:32)#
[2015-10-07 00:09:46] Expedition is already running: Expedition 5 (ETA 2015-10-07 00:58:46)
[2015-10-07 00:09:46] Let's send an expedition out!
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[log] CLICK on L(678,560)@S(0)[0,0 1350x665]
[debug] waiting for ensei_name_06.png to appear
[debug] ensei_name_06.png has not appeared.
[error] script stopped with error in line 324
[error] FindFailed ( can not find ensei_name_06.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
38: util (  wait_and_click )     kc_window.wait(pic, time)
185: main (  run_expedition )     wait_and_click(kc_window, expedition.name_pict, 10)
316: main (  init )     run_expedition(expedition)
[error] --- Traceback --- end --------------

**Comment by kevin01523** [comment]
ok fixed after updatating image from screenshot on ubuntu 
![Image of exped 6](http://imgur.com/serYq1n.png)

**Comment by mrmin123** [comment]
@kevin01523 Thanks, I'll include it in the next update. Maybe I should go back and re-create all the expedition images while I'm at it...
