### ISSUE TITLE
Add/revise assets for 2016 Fall Event

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#243]
@diceman112 has already provided some images, but we don't have images to cross-reference to confirm that they work at all times (pre-medal, post-medal), and we don't have node images. If anyone would like to provide screenshots of the event panels and nodes that'd be great. Screen captures should be uncompressed PNGs for maximum accuracy in image matching, and node images should have the blue ring either invisible or as small possible (see previous node images to see what might be acceptable).

Connected to #242.

**Comment by dice4321** [comment]
I figured out my mistake, there were event panel pictures I left in the previous push I made in kancolle_auto.sikuli folder and the correct ones in the combat folder. I thought the program read images from a specific path!

**Comment by nekoma0** [comment]
hi, how do i provide screenshots of node to the directory? i`m quite new to this github thing

Edited:
i just created a fork from this.
do i add file and create a new branch from my fork and make a pull request?
or i just directly add file to my master, and then make a pull request?
i`m quite confuse on how this works.

**Comment by mrmin123** [comment]
Hi @nekoma0 Yes, it typically works like that. You are basically making changes to your `master` branch, committing your changes to your `master`, uploading (pushing) your changes to `master`, then requesting that I merge your changes to my `master` via the PR. You COULD make a new branch, make changes to that, and then request to merge to my `master` (or any other branch, for that matter), if you want to make sure that your `master` branch doesn't get messed up. This is useful if you have multiple branches being worked on in parallel, or if you want to isolate experimental changes from your working `master` branch.

For this particular ticket I recommend forking the `243_2016_fall` branch, making your changes to that branch, and then making a PR to merge your changes to my `243_2016_fall` branch. It helps isolate code changes and encapsulates them in a logical package.

**Comment by nekoma0** [comment]
Hi, @mrmin123 
thanks for the info. what if you updated your repo, will my repo fork gets updated automatically?
i mean, if there's any changes on your `master` , will my `master` automatically obtain changes from your `master`?

**Comment by twisting2017** [comment]
Hi, not sure if you still need those:

if you need anything else, just say so.

![2](https://cloud.githubusercontent.com/assets/21052240/20610462/531363ce-b29a-11e6-8e79-e25580249bb6.png)
![1](https://cloud.githubusercontent.com/assets/21052240/20610463/53142cd2-b29a-11e6-983e-920f27e4a510.png)

**Comment by mrmin123** [comment]
@nekoma0 no, unfortunately you need to manually do a `git pull` or `git fetch` then `git merge` to get updates.

@twisting2017 thanks for the screenshots. I've updated the panel images and merged the changes into `master`.

**Comment by mrmin123** [comment]
Only a few days left but `master` is now updated with what I believe are the required images (for the majority of cases) for the 2016 Fall event. Closing this for now, but please let me know if there are assets you'd like to see added.
