### ISSUE TITLE
Proposal tessdata generation

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#25]
update read me o put how to generate tessdata in ubuntu and wndows

in windows you need to delete the libs folder so sikuli will generate the libs folder w/ tessdata inside

in ubuntu you need 
to install via apt
sudo apt-get update
sudo apt-get install tesseract-ocr
after installation
check tesseract-ocr location on /usr/share
then
sudo cp -rpf  /usr/share/tesseract-ocr/tessdata /usr/local/share/tessdata

**Comment by mrmin123** [comment]
@kevin01523 Thanks for the update. I'll update the readme with the info next update.
