### ISSUE TITLE
LBAS sortie start button issue

### ISSUE THREAD

**Issue by stackhanovets** [mrmin123/kancolle-auto#255]
Hi.
I've catched a new excepcion in the combat module. Look at this config part:

> [LBAS]
> Enabled: False
> EnabledGroups: 1,2,3
> Group1Nodes:
> Group2Nodes:
> Group3Nodes:
> 

As you see I've used an air defence strategy when all three LBAS slots were used to obtain the white text (no damage taken during an abbyssal base air raid). 
The sortie start button was _combat_start.png_: 
![combat_start](https://cloud.githubusercontent.com/assets/16455270/21007802/8f71cef4-bd4f-11e6-99c9-207715d64a64.png)

But the script has missed it and looked for _combat_start_lbas.png_ followed by green line: 
![combat_start_lbas](https://cloud.githubusercontent.com/assets/16455270/21007874/fd7dfdc8-bd4f-11e6-86ea-cee8dd429e2e.png)

I've disabled the LBAS section, so I have to resupply all three slots manually now.

**Comment by mrmin123** [comment]
I'm not considering this a bug only because at the time the LBAS module was implemented there was no need to sortie all the LBAS groups on defense-only, so the button for such a scenario was never checked. I'll probably implement this in the next cleanup.

**Comment by mrmin123** [comment]
Should be fixed in `master`.
