### ISSUE TITLE
Failing to start Expeditions

### ISSUE THREAD

**Issue by perryhuynh** [mrmin123/kancolle-auto#256]
*Please read the FAQ/Common Issues section of the README before opening a ticket. If you are submitting a feature request or a non-bug report, please feel free to delete this template. Also feel free to delete sections of this template you do not find relevant when submitting a bug report. Thanks!*

#### Environment details

* kancolle-auto version (last modified date): Commit `c6b5ce8`
* Viewer/browser: KC3
* Operating system: XUbuntu

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:

- [X] Consistent
- [ ] Transient

Bot fails to click on `kancolle_auto.sikuli/decision.png`, so it is never actually able to start any expeditions. It seems to be failing to find other images such as `kancolle_auto.sikuli/next.png` when receiving an expedition as well. Could there possibly have been a UI update?

#### Console log (if applicable)
```
[2016-12-22 10:02:06] Let's send fleet 2 out for expedition 2!
[debug] waiting for P(ensei_name_02.png) S: 0.8 T: -10,-7 to appear
[debug] P(ensei_name_02.png) S: 0.8 T: -10,-7 has appeared.
[log] CLICK on L(394,312)@S(0)[0,0 1024x768]
[debug] waiting for expedition_timer.png to appear
[debug] expedition_timer.png has not appeared.
[log] TYPE "#ESC."
[2016-12-22 10:02:19] Basic recovery successful! Re-initializing kancolle-auto!
[2016-12-22 10:02:19] Reading config file!
[2016-12-22 10:02:19] Scheduled Sleep enabled: ~7.0 hours starting at ~0030
[2016-12-22 10:02:19] Expeditions enabled: fleet 2: 2, fleet 3: 5, fleet 4: 6
[2016-12-22 10:02:19] Reading util config file!
[2016-12-22 10:02:19] Config successfully loaded!
[2016-12-22 10:02:19] Starting kancolle_auto!
[2016-12-22 10:02:19] Finding window!
[2016-12-22 10:02:19] Focus on KanColle!
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
```

#### Relevant config snippet (if applicable)
```
[replace this line with relevant portion from config with comments removed]
```

**Comment by mrmin123** [comment]
@perryhuynh could you provide screenshots of your screen, particularly of pages that are failing image recognition? For what it's worth, I'm not encountering any issues on my end, so I don't think it's a UI change...

**Comment by perryhuynh** [comment]
![expediton](http://i.imgur.com/SsGRY5N.png)
![compass](http://i.imgur.com/l0AtuNS.png)

I've noticed it on expedition, compass, and unfortunately I don't have a screenshot of the expedition receive page.

The issue started happening even before the maintenance yesterday so it probably indeed is not a UI change...

I also tried to do a fresh install of the OS in a VM etc with no luck

**Comment by mrmin123** [comment]
Yea I have no idea what the issue would be... There's a 100% match between your screenshots and elements that kancolle-auto checks for... I'm guessing maybe a Sikuli issue but those usually don't result in intermittent issues...

**Comment by perryhuynh** [comment]
The issue seemed to be with VMWare Workstation 12 Pro 12.5.2 build-4638234 (Latest Version)

It runs fine on Virtualbox

**Comment by mrmin123** [comment]
Awesome, glad that worked out.
