### ISSUE TITLE
Crash on startup, seems to be a Python issue?

### ISSUE THREAD

**Issue by RHERHE123** [mrmin123/kancolle-auto#26]
Not entirely sure what the issue is, I've tried Python 2.7.10 and 2.7 both 32/64bit. Using sikuli 1.0.1 and Java JRE 8. tessdata folder is present. Also tried messing with the imports but I'm not too familiar with Python.

![error2](https://cloud.githubusercontent.com/assets/15021377/10350240/7abf816a-6d08-11e5-91c3-eb5dc62d2c50.PNG)

**Comment by RHERHE123** [comment]
Never mind, the more updated branch seems to be working fine. I had to set the window name manually in kancolle_auto.py though.

**Comment by mrmin123** [comment]
@RHERHE123 Thanks for the update; glad you found the updated branch. I'm hoping to make some additional changes to it and merge it in this weekend. Are you using Chrome for your Kancolle viewer?

**Comment by RHERHE123** [comment]
No, using flash player.

**Comment by mrmin123** [comment]
So changing the `Program` field to 'Flash' or whatever in `settings.ini` didn't work, but manually setting it in `kancolle_auto.py` did?

**Comment by RHERHE123** [comment]
Actually it seems to work fine now. Was getting an AttributeError before for some reason. Do you mind if I add you on Steam? It's a lot easier for me to use than Github.

**Comment by mrmin123** [comment]
Sure. mrmin123 on Steam

**Comment by RHERHE123** [comment]
I already sent a friend request earlier to see if you could help me get it working.
