### ISSUE TITLE
Upgrade to use Sikuli 1.1.1

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#261]
* Update to actively maintained version of Sikuli
* Makes install process easier (Sikuli installs Tesseract OCR more consistently)
* ~~May break compatibility with KAGA~~ Breaks compatibility with KAGA

---

Testing:
* Main loops ✔️ 
* Expeditions ✔️ 
* PvP ✔️ 
* Combat ✔️ 
* Sub Switch ✔️

**Comment by waicool20** [comment]
You should update the wiki to reflect changes to the executable

**Comment by mrmin123** [comment]
Thanks for the reminder... it was woefully out of date.
