### ISSUE TITLE
Script stopped with error in line 4 ; Import error no module named util

### ISSUE THREAD

**Issue by lainconnue** [mrmin123/kancolle-auto#266]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): release 7 , 22nd January
* Viewer/browser: chrome
* Operating system:win 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:
Consistent

#### Console log (if applicable)

![image](https://cloud.githubusercontent.com/assets/20400916/22228938/6127aebc-e20f-11e6-9870-d85973088031.png)

#### Relevant config snippet (if applicable)
```
default config
```

**Comment by n0k0m3** [comment]
Probably (if you're using git desktop) git is syncing util script while kca
is loading.
Try to move kca to another folder

**Comment by mrmin123** [comment]
@lainconnue Please upgrade/reinstall Sikuli following [these directions](https://github.com/mrmin123/kancolle-auto/wiki/Install-kancolle-auto#installation).

**Comment by mrmin123** [comment]
Closing this and opening up announcement #267
