### ISSUE TITLE
Exception in "Main" java.lang. NoClassDefFoundError; org/sikuli/script/IScreen

### ISSUE THREAD

**Issue by lainconnue** [mrmin123/kancolle-auto#268]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): release 7
* Viewer/browser:chrome
* Operating system:win 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:
Consistent

#### Console log (if applicable)
```
[replace this line with ~50 lines of console log]
![image](https://cloud.githubusercontent.com/assets/20400916/22233670/d2283524-e22c-11e6-8023-e3d1011e63b5.png)

```

#### Relevant config snippet (if applicable)
```
default config
```

**Comment by mrmin123** [comment]
Not a kancolle-auto issue. Maybe try googling 'sikuli' and the error and see what you get? I got this hit but I don't know if it's the cause of your issue: https://answers.launchpad.net/sikuli/+question/247998

**Comment by lainconnue** [comment]
Huh. Guess it's not a big issue if nobody else is reporting it. Oh well, posted the question there so once it's answered i will post the link back here

**Comment by mrmin123** [comment]
Yea I think multiple people have release 7 working with no/few issues. Might have something to do with your Java setup, but that's outside my wheelhouse. Good luck!
