### ISSUE TITLE
Add/revise assets for 2017 Winter Event

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#274]
Here we go again!

If anyone would like to provide screenshots of the event panels and nodes that'd be much appreciated. Screen captures should be uncompressed PNGs for maximum accuracy in image matching, and node images should have the blue ring either invisible or as small possible (see previous node images to see what might be acceptable).

**Comment by mrmin123** [comment]
Added E-1 assets, including LBAS selection images for nodes B and I.

**Comment by mrmin123** [comment]
Added some E-2 assets.

**Comment by Danielosama** [comment]
Hey man, I've already done E1 and E2 on Hard, will farm a bit before E3, do you need any screenshot in particular?

**Comment by AppleBoi86** [comment]
Sometimes the script gets stuck at selecting _node_lbas_E-2-J_1.  Any idea of the cause?  It clicks outside the circle then the script get stuck with no error.

Happens to _node_lbas_E-2-I-1 as well.

**Comment by mrmin123** [comment]
@Danielosama I also did up to E-2 so I think we're good for assets right now, unless you have some E-3 map assets you'd like to share! I'm working on generating the E-3 panel asset right now, but don't plan to sortie to it for a few days. Also, if there are some E-2 assets that isn't in already that would aid in farming, if you provide screenshots of those I can get them in. I think node selections for nodes E and G from node D, and LBAS targeting for node G are the potentially useful ones I'm missing, but I don't know if they are needed for farming. Thanks for the offer regardless!

@AppleBoi86 that behavior is a bit odd since node selection should be clicking in a 10px by 10px area from the center of the matched image, and the nodes are ~20px in diameter. You could try tightening the window even further by line 227 in `util.py` to this:
```python
        return[-3, 3, -3, 3]
```
and see if that helps.

**Comment by AppleBoi86** [comment]
@mrmin123  Thank you. That worked.  Mine was at -9, 9, -9, 9

Here's LBAS node for E-2-G-1/2
http://imgur.com/a/Jkvvt

**Comment by Danielosama** [comment]
@mrmin123  Here you go, images of Nodes E and G   http://imgur.com/a/5G5Dm

**Comment by mrmin123** [comment]
@AppleBoi86 @Danielosama thank you both! I'll get those in tonight.

Edit: added

**Comment by waicool20** [comment]
_node_lbas_E-1-I_1 and _node_lbas_E-1-I_2 need to be cropped to exclude the two lines (or just the right line) on the side, otherwise it fails to choose it after clearing the map since the right path disappears

**Comment by mrmin123** [comment]
@waicool20 It would make more sense to generate a second set of images for those nodes for use post-LD. Cropping would require a reprogramming of how click areas are generated, or specifying a custom click area just for this, which would be akin to using a sledgehammer to kill a fly.

If you could provide a screenshot of the map post-clear with and without the first LBAS setting I can generate the node images. This is preferable to a PR.

**Comment by waicool20** [comment]
![image](https://cloud.githubusercontent.com/assets/5538666/23010365/f544d9c8-f455-11e6-813d-560209909e86.png)

![image](https://cloud.githubusercontent.com/assets/5538666/23010367/f9261f20-f455-11e6-9b50-4ea16dee79c9.png)

**Comment by mrmin123** [comment]
Thanks, I'll be adding them along with some E-3 assets soon!

edit: done

**Comment by Danielosama** [comment]
@mrmin123  Just finished E3 Hard, any image you may need?

**Comment by AppleBoi86** [comment]
[error] script stopped with error in line 433
[error] FindFailed ( can not find lbas_panel_switch.png on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
 
^ I have that happened twice when you sortie with LBAS is at orange morale.

**Comment by mrmin123** [comment]
@AppleBoi86 that should have been resolved as of Feb 11 (#279). Is this happening past this version?

@Danielosama the only ones I'm missing are ones related to node J: node selection to node V, and lbas nodes for node J. That said, I'm planning on generating these images in the next few hours so if you're not in the middle of sortieing to node J it's not a big deal.

**Comment by AppleBoi86** [comment]
My bad, I didn't update the image.  
Working with no issue now.  Thank you.

**Comment by tigurand** [comment]
I always stuck on 2nd group LBAS choice on E-3.

[2017-02-18 14:49:44] Assigning targets to LBAS group 1
[log] CLICK on L(754,334)@S(0)[0,0 1920x1080] (521 msec)
[log] CLICK on L(750,334)@S(0)[0,0 1920x1080] (521 msec)
[log] CLICK on L(1269,156)@S(0)[0,0 1920x1080] (521 msec)
[2017-02-18 14:50:16] Assigning targets to LBAS group 2
[log] CLICK on L(751,334)@S(0)[0,0 1920x1080] (521 msec)
[2017-02-18 14:50:50] LBAS groups ready with their assignments!

It wasn't actually ready and just stuck there until I manually choose the node.

**Comment by waicool20** [comment]
@tigurand Was happening for me on E1 cleared I node before it was added, the script probably couldn't match up the images.

@mrmin123 I think the script should scan for the green button after assigning the LBAS, and if it's not there it should crash saying it couldn't find the image or something more elegant.

**Comment by mrmin123** [comment]
@tigurand This is a known issue but I haven't gotten around to a fix just yet.

@waicool20 it already scans for the green button.

**Comment by mrmin123** [comment]
I think with the last update all the necessary 2017 Winter Event assets are in. Leaving this open until the end of the event so if there's anything missing please make a note of it here, but otherwise there will be no further updates of assets.

**Comment by mrmin123** [comment]
Event is over, and event assets have been removed as of above PR (01d50e0).
