### ISSUE TITLE
LBAS Assign Crash

### ISSUE THREAD

**Issue by perryhuynh** [mrmin123/kancolle-auto#279]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 2017-02-11
* Viewer/browser: Chromium
* Operating system: Xubuntu 16.04

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:

Issue can be produced consistently

Script fails to find `lbas_panel_switch.png` causing it to crash whenever the planes have low morale, since the panel will look like this:

![](http://i.imgur.com/E9v1Q8s.png)

instead of

![](http://i.imgur.com/t606cxV.png)

#### Console log (if applicable)
```
[2017-02-11 18:21:05] Assigning targets to LBAS group 1
[log]  TYPE "#ESC."
[2017-02-11 18:21:17] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: lbas_panel_switch.png: (15x273) in R[112,117 800x480]@S(0) E:Y, T:3.0
  Line 2718, in file Region.java
```

#### Relevant config snippet (if applicable)
```
[replace this line with relevant portion from config with comments removed]
```

**Comment by mrmin123** [comment]
Thanks for the report. This seemed to be a straight-forward enough fix so I merged in un-tested changes as d35711321ceeb224f2ad3a408a908a8166ec86ff. Feel free to re-open if this doesn't fix it!
