### ISSUE TITLE
LBAS assignment hangs

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#293]
I've been encountering it today and behavior was confirmed by @tigurand and @waicool20 in #274 

Most likely a timer issue.

**Comment by mrmin123** [comment]
@tigurand @waicool20 can you update master and check if this fixes the bum LBAS assignment issue? I tested it on one iteration and the second squadron assignments went through fine. Heading to sleep now so I'll continue debugging if needed tomorrow.

**Comment by mrmin123** [comment]
Oh there's another issue here... After pressing the green button for the first LBAS squad, as the mouse moves back to the desired node, it'll trigger the LBAS panel to move and cover up the node. As far as Sikuli knows it saw the node and ordered a click, but in-game the node was never clicked because the click happened on the LBAS screen.

**Comment by waicool20** [comment]
The assignment worked fine for me ever since you added the Node I cleared images.

I'd suggest checking for the green button, if it doesn't see it, the script should try to redo the assignment.

**Comment by mrmin123** [comment]
@waicool20 that won't be necessary. Issue has been fixed in latest `master` by adding a rejigger mouse to the middle-top of screen after LBAS assignment.

Do note that the issue you were having prior with the lack of Node I cleared images is completely different: it was just the lack of proper images to match against. No amount of added logic would have helped in that regard.

Closing ticket.
