### ISSUE TITLE
Sikuli Folder Problem

### ISSUE THREAD

**Issue by Chololoco13** [mrmin123/kancolle-auto#297]
* kancolle-auto version (last one):
* Viewer/browser:Google Chrome
* Operating system: windows 10

I'm trying to install Sikulix.
I'm on the second step
 https://puu.sh/u95pX/dffdae5c1f.png
https://puu.sh/u94Ak/29df0db248.png

But I can not find the Sikuli folders
https://puu.sh/u95D7/b8d865c5da.png

what am I doing wrong?

**Comment by mrmin123** [comment]
The second step doesn't mention a Sikuli folder? I'm a bit concerned because you didn't select Pack 1 but it seems to have generated the sikulix.jar file, which is what you need, so you might be good to go.

**Comment by mrmin123** [comment]
Closing since this isn't a kancolle-auto problem.
