### ISSUE TITLE
Not an issue but where is the code for 2017 Winter Event?

### ISSUE THREAD

**Issue by ghost** [mrmin123/kancolle-auto#300]
Hi there, i am kinda new here so i would need some help in getting the latest copy with the new winter event on it. The current release i am using 7.1 does not have the winter event support it seems. I would like to farm the last map node 1 for submarine leveling.

**Comment by silfumus** [comment]
This download the latest stable branch: https://github.com/mrmin123/kancolle-auto/archive/master.zip

**Comment by mrmin123** [comment]
@intothefantasy as @silfumus has pointed out, you want the cutting-edge `master` branch for Event support. Events typical involve a lot of incremental updates so there isn't a 'stable' release version assigned until after the event, when the event assets have typical been removed. Until then you'll want to periodically want to update your kancolle-auto version to keep event assets up-to-date.

I'll leave this ticket open as a reminder to self to update the README with pertinent event information.

**Comment by ghost** [comment]
@silfumus thanks for the help.

**Comment by ghost** [comment]
@mrmin123 just a question here, for simple event map 3 node 1 sub leveling. Is this setting possible even not in the 'stable' release? just a navigation to the node and retreat after that tho.

**Comment by mrmin123** [comment]
@intothefantasy it's possible. You just need the cutting-edge for the event assets. Cutting-edge is more of an extension of stable at this point.

I don't know what the node selection is but you can refer to the [example event configs](https://github.com/mrmin123/kancolle-auto/wiki/Event-configs) to get an idea of how to configure it. If you need help with it just write here.
