### ISSUE TITLE
Add reset difficulties options?

### ISSUE THREAD

**Issue by nhatdisk** [mrmin123/kancolle-auto#301]
Hi, just a suggestion but can you add an option to reset event difficulties? Would be useful for, for example, people who want to farm in easy and clear in hard.

A temporary solution would be to add an option to set the number of sorties.

Cheers and keep up the good work.

**Comment by waicool20** [comment]
@nhatdisk Number of sorties before the script stops can be set through the scheduled stop option

Edit: autocorrect

**Comment by mrmin123** [comment]
@nhatdisk at the moment ScheduleStop would be your best bet... but if you can provide screenshots of the following I might be able to cook something up:

1. Screen with button to press to change difficulty
2. Screen with different difficulty options
3. Any subsequent screens before getting to the screen where you press the button to sortie

**Comment by mrmin123** [comment]
Closing for this event due to lack of assets, and even if I did have them, I wouldn't be able to test. Will consider revisiting on next event.
