### ISSUE TITLE
Adding SSVs to sub switching 

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#303]
Continuing the work started by @waicool20 in #291. Will review fix for #288 here as well.

**Comment by mrmin123** [comment]
@waicool20 note that I renamed the `_kai` suffixes to `-kai`

**Comment by waicool20** [comment]
Need to revise the ship type check for sub switching since SSVs don't have the stats that ```fleetcomp_ship_stats_submarine.png``` currently has, so the script ends up not switching them out.

I think using the ship class kanji would be a better way of distinguishing ships, you could probably also forego going into the stats menu, unless you need the higher res image checking. Could save some time this way.

**Comment by mrmin123** [comment]
@waicool20 Using the kanji was an approach I entertained when I initially created the sub switch module, but is something I ultimately moved away from due to two reasons:

1. A lot more images that I would have to manually maintain
2. Sub identification time actually has a worse worst-case performance

Point 1 is a bit moot now, ever since the `EnabledSubs` option introduction, which ended up requiring generation of individual assets for every sub anyway, but Point 2 still stands. With 15 SS and SSVs in the game the worst case results in kancolle-auto taking 15 seconds to identify a sub (and that's with the recent default Sikuli wait time optimization... otherwise it would have taken 45 seconds).

I'll definitely give this more thought but the current method might still be the fastest and most efficient generic implementation. I should note that submarines, including SSVs, have a [default stat of AA and ASW of 0](http://kancolle.wikia.com/wiki/List_of_submarines_by_upgraded_maximum_stats), which is what kancolle-auto checks for. For the moment I would advise that your SSVs only be equipped w/ equipment that do not alter these two stats.

If you have use-case situations where you need SSVs in your fleet, and they have to be equipped with AA/ASW equipment, and they need to be automatically sub-switched, let me know what that situation is and I may be convinced to consider this harder, but I've never encountered this myself.

**Comment by waicool20** [comment]
I guess I'll equip all my subs with only torps then, and take out any seaplane bombers a sub might have before starting a session.
