### ISSUE TITLE
winter event issue on map 3 1st node farming

### ISSUE THREAD

**Issue by ghost** [mrmin123/kancolle-auto#307]
i am using the master version to test out the event map 3 1st node submarine leveling. With the latest master, i am having this issue

![image](https://cloud.githubusercontent.com/assets/25874372/23122239/5c9873fa-f79e-11e6-958a-06f38af026e7.png)

running under windows environment and this version log 
#### 2017-02-19

it will just stuck on the event section of the game at 1st page (with 2 of the events maps)

**Comment by mrmin123** [comment]
There's a typo in the config of the current version of `master`. It says something like `Subarea: =`. If you get rid of the semicolon it should fix this.
