### ISSUE TITLE
Revise timings

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#309]
The latest changes optimizing kancolle-auto over-optimized the quest reward handling, as it crashes on the reward screen, probably due to the shorter standard wait times. This ticket should resolve this issue.

**Comment by mrmin123** [comment]
A number of timings actually need to be changed with the new default autowait time.

**Comment by mrmin123** [comment]
If somebody is running combined fleet combat w/ the latest master, can they confirm whether or not everything still works properly..?

**Comment by stackhanovets** [comment]
Hi,
I've found at least 3 issues in the sikuliX-based release.

- mentioned quest reward bug: 
![catch](https://cloud.githubusercontent.com/assets/16455270/23295371/4d7ec8f2-fa81-11e6-9376-c8e7dcc966c5.png)

- LBAS buttons issue. I've used 1st air squad for bombing and 2nd for interception, so for E-1 farm I've activated only 2nd squad. The script tried to resupply 1st squad and point it on map resulting to endless loop. 

- CATBOMBS! Really, I've not grinded the event so much, but now it looks like the script timings have become randomless.

Will use the pre-sikuliX release for now.

**Comment by mrmin123** [comment]
1. Has been resolved
2. I'm not sure what you mean by this? If you are sending out LBAS squad 1,
of course it needs to be resupplied and assigned nodes?
3. Since Cat bombing is user specific behavior I can't help you there.
Previous discussions seem to point to too many numbers of clicks/actions
triggering this, so a constantly failing setup might exacerbate the issue.
I can tell you with certainty, however, that there were no changes to the
designed "randomness" in the code.

**Comment by mrmin123** [comment]
Regarding point 2, I guess I can't rule out issues w/ the recent wait timer changes. I'll see if I can reproduce.

**Comment by stackhanovets** [comment]
1. OK
2. I was sending only 2nd group, the script has tried to resupply 1st group and kept waiting at a map screen. Nevermind, I've just replaced the squads for the required order, so the 1st squad is resuppluing normally rather than 2nd when only one squad is selected: 

```

[LBAS]
Enabled: True
EnabledGroups: 1
Group1Nodes: 
Group2Nodes: _node_lbas_E-1-D, _node_lbas_E-1-L
Group3Nodes:

```

(of course I knew about the images)

3. I don't know the reason but the old version works fine. Well, I guess the reason was the quest reward bug lol.

**Comment by mrmin123** [comment]
OK, good to know that the LBAS stuff was resolved. IIRC there is an LBAS deployment mode that does not involve node selections but does involve resupplying (air base defense maybe?). For those cases you would want to Enable their group (`EnabledGroups: 1, 2`), but leave their `Group#Nodes` assignments blank. This will allow kancolle-auto to resupply them, but does not try to assign them to nodes on sorite.

And for 3, yea, it's entirely possible that when the script crashed on the quest reward screen and tried to recover it kept on sending clicks which triggered the catbomb. I'm still working out the kinks but once they're resolved try switching back to the latest release and see if it's more stable/less catbomb-enducing.

**Comment by mrmin123** [comment]
After extended testing timings seem fine. Closing.
