### ISSUE TITLE
not responding, not sure what is happening to the bot. No errors

### ISSUE THREAD

**Issue by ghost** [mrmin123/kancolle-auto#310]
currently i am using this version
https://github.com/mrmin123/kancolle-auto/wiki/Changelog#2017-02-20

i did the event map 3 on node 1 for leveling my sub. In my module, i only active expedition and combat.

frequently, i am having this issue where the bot just stop working and when i see the cmd, i wont see any errors.

![image](https://cloud.githubusercontent.com/assets/25874372/23201390/4f1cca1a-f914-11e6-8bdc-10d59964ea79.png)

which is why i am not sure how to report this as well. This issue hits after like few hours of playing or sometimes around 30mins will hit it.

**Comment by mrmin123** [comment]
I don't know what might be causing that off the top of my head but try running kancolle-auto/Sikuli with the `-d 3` flag for a higher level of debug messages... It might surface something that the default logs don't.

**Comment by ghost** [comment]
here is some log after i use d 3, previously was using d 2

![image](https://cloud.githubusercontent.com/assets/25874372/23208874/b9386068-f931-11e6-991f-4be98cc1dd51.png)

there is a mention of catbomb there, i dont encounter them tho, or is it a new feature of kc3 to reconnect after cat bomb? when i came back,  still seeing my home screen

**Comment by mrmin123** [comment]
Not sure why this is happening, but try removing these lines (~line 201) in `util.py`:

```python
        # Set short autowait timeouts
        for key in global_regions:
            global_regions[key].setAutoWaitTimeout(1)
```

and report back..

**Comment by ghost** [comment]
here is what i get for another one, not sure if is related to the above but i did remove that 

![image](https://cloud.githubusercontent.com/assets/25874372/23256168/4d003574-f9f9-11e6-8a4b-92138d8dc6f9.png)

and is stuck on this page

![image](https://cloud.githubusercontent.com/assets/25874372/23256179/5d89aefc-f9f9-11e6-9935-5f11844b822b.png)


as i know i am setting LBAS to false
i think there is a possibility where the bot just clicked on the LBAS icon which this on the E3 map
![image](https://cloud.githubusercontent.com/assets/25874372/23268339/5f02558e-fa28-11e6-93ef-2ad0ed3a2a1f.png)


here is the step i found which is success with the combat sortie

[2017-02-24 00:17:10] Navigating to combat menu with 0 sidestep(s)!
[log] CLICK on L(393,320)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(394,410)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(885,520)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(885,349)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(887,388)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(882,317)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(805,542)@S(0)[0,0 1920x1200] (521 msec)

and for this is the one has error,. the last part of the click looks way off the coordinates

[2017-02-24 00:25:16] Navigating to combat menu with 0 sidestep(s)!
[log] CLICK on L(319,325)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(461,394)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(877,521)@S(0)[0,0 1920x1200] (521 msec)
[log] CLICK on L(917,357)@S(0)[0,0 1920x1200] (520 msec)
[log] CLICK on L(655,482)@S(0)[0,0 1920x1200] (520 msec)



`

**Comment by mrmin123** [comment]
Looks like the event panel image for it needs to be updated:

![_event_panel_2-1](https://cloud.githubusercontent.com/assets/4326866/23287637/8313f76e-f9f3-11e6-89db-3278211edc79.png)

I guess the LBAS image wasn't there when I generated the image... Any other crashes besides this?

**Comment by ghost** [comment]
so far no other errors. I think this is the only one i encounter. Which event panel image should i use then? the one you posted before this reply?

**Comment by mrmin123** [comment]
Use this one instead:
![_event_panel_2-1](https://cloud.githubusercontent.com/assets/4326866/23287757/39d87092-f9f4-11e6-8a4b-97c3b66978f2.png)


I'm still concerned that removing the
```python
global_regions[key].setAutoWaitTimeout(1)
```
line fixed your initial problem, however..

**Comment by ghost** [comment]
i will try to add that line back and see will it cause the previous issue or not.

**Comment by mrmin123** [comment]
Try using the latest master in since that has some other relevant bugfixes as well

**Comment by ghost** [comment]
i have highlighted which version i am using previously.
https://github.com/mrmin123/kancolle-auto/wiki/Changelog#2017-02-20

the latest master version is the same as the one i am using currently?

**Comment by mrmin123** [comment]
No, I just merged some new changes in. Latest master can be found [here](https://github.com/mrmin123/kancolle-auto/archive/master.zip).

edit: I also updated the wiki's changelog

**Comment by ghost** [comment]
alright, will test later. Thanks, will update any findings here later as well.

**Comment by mrmin123** [comment]
Cool, thanks. You *might* encounter other issues related to the reducing of the default wait times with the combat module, mainly combined fleet sorties, as I've not tested this. If you encounter any bugs related to that please report them at #309. Otherwise, update this one.

**Comment by ghost** [comment]
new issue here, stuck on the refuel section. 

![image](https://cloud.githubusercontent.com/assets/25874372/23294531/ca51c058-faa6-11e6-88a6-e86b302e8277.png)

earlier i go have the same stuck on pvp section tho but i cant capture the error that time as i am not around and not using cmd to call the run..bat file.

**Comment by mrmin123** [comment]
I'm not really sure what to say about that crash... it seems like the image matching is working weirdly/sporadically? If that's the case it might be more of a Sikuli issue... Can't say for certain at the moment.

**Comment by mrmin123** [comment]
Closing for now.
