### ISSUE TITLE
ADD 1-5 to combat module?

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#32]
since 1-5 is simple enough and with the right fleet it acts like 3-2  and due to saury update i think its time to expand the combat module atleast 1-5 4-3 i think is still kinda hard

edit:or is it already possible?
edit2:upon checking the images it seems slightly possible 1-5 image still not available ill try to fiddle or make a workaround on my local copy

**Comment by mrmin123** [comment]
Merged a resolution for this into master. If the subarea is set to anything > 4, it'll assume it's an EO. Seemed reasonable enough.

**Comment by kevin01523** [comment]
if self.checkeo > 4:
            wait_and_click(self.kc_window, 'combat_panel_eo.png')
        wait_and_click(self.kc_window, self.subarea_pict)
actually did it but not perfect suddenly i was faced with an error lol even though it worked before on my own edit well
[error] Region.exists: seems that imagefile could not be found on disk 
well might be some bug i caused
on combat combat_start.png

**Comment by mrmin123** [comment]
@kevin01523 If you made edits to the previous version of master the subarea_pict for 1-5 didn't exist so that's probably why you got that error. I've added images for a whole slew of operations in the last merge.

**Comment by kevin01523** [comment]
no i did put new images it did run on 1-5 but after i changed something on config that happened it happens on Formations selection screen this is the right way to use it right?
Formations: line_abreast , line_abreast , line_abreast , line_abreast , line_abreast

**Comment by mrmin123** [comment]
Ah, yes, but no spaces between the commas. It'll end up looking for things like 'formation_ line_abreast .png' (note the spaces). I'll include a patch to remove all spaces automatically in the next update.

**Comment by kevin01523** [comment]
[2015-10-11 04:38:34] At Home!
[2015-10-11 04:38:34] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-11 04:38:38] No, no fleets to receive!
[2015-10-11 04:38:38] Navigating to Sortie menu!
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(485,393)@S(0)[0,0 1360x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(519,363)@S(0)[0,0 1360x768]
[debug] waiting for combat_area_1.png to appear
[debug] combat_area_1.png has appeared.
[debug] waiting for combat_area_1.png to appear
[debug] combat_area_1.png has appeared.
[log] CLICK on L(442,565)@S(0)[0,0 1360x768]
[debug] waiting for combat_panel_eo.png to appear
[debug] combat_panel_eo.png has appeared.
[debug] waiting for combat_panel_eo.png to appear
[debug] combat_panel_eo.png has appeared.
[log] CLICK on L(1008,403)@S(0)[0,0 1360x768]
[debug] waiting for combat_panel_1-5.png to appear
[debug] combat_panel_1-5.png has appeared.
[debug] waiting for combat_panel_1-5.png to appear
[debug] combat_panel_1-5.png has appeared.
[log] CLICK on L(737,332)@S(0)[0,0 1360x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(971,568)@S(0)[0,0 1360x768]
[2015-10-11 04:38:56] Checking fleet condition...
[2015-10-11 04:39:06] Light damage: 0; moderate damage: 0; critical damage: 0
[2015-10-11 04:39:13] Checking fleet morale!
[2015-10-11 04:39:19] Ships have good morale!
[2015-10-11 04:39:23] Commencing sortie!
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(916,569)@S(0)[0,0 1360x768]
[error] Region.exists: seems that imagefile could not be found on disk
[error] Region.exists: seems that imagefile could not be found on disk
[error] Region.exists: seems that imagefile could not be found on disk
[error] Region.exists: seems that imagefile could not be found on disk

**Comment by mrmin123** [comment]
@kevin01523 It seems like the sortie is starting properly, so it's not related to the EO support addition. Not what image is not being found. Formations? If so, check the files you have/your config for typos?

**Comment by kevin01523** [comment]
ah the problem is on the spaces you mentioned when i removed spaces it worked ok
