### ISSUE TITLE
Night battle = True, get declined

### ISSUE THREAD

**Issue by n0k0m3** [mrmin123/kancolle-auto#324]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): Latest commit ef2f095
* Viewer/browser: Chrome/KC3kai
* Operating system: Windows 7
**USED WITH KAGA**

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: consistent

Although nightbattle is set to "true" for 2 last nodes, the script still decline NB. I ran the script w/o KAGA and changed lower case "true" to "True" and it worked again.
I knew that the uppercase-lowercase problem were fixed earlier this year, but it seemed NB still use old arguement

```
if self.night_battles[nodes_run] == "True"
```

#### Console log (if applicable)
```
[2017-02-26 04:09:29] Continuing on to next node...
[log] CLICK on L(313,339)@S(0)[0,0 1600x900] (521 msec)
[log] CLICK on L(341,445)@S(0)[0,0 1600x900] (524 msec)
[2017-02-26 04:09:40] Spinning compass!
[log] CLICK on L(629,382)@S(0)[0,0 1600x900] (525 msec)
[2017-02-26 04:09:55] Selecting fleet formation!
[2017-02-26 04:11:48] Declining night battle!
[log] CLICK on L(327,314)@S(0)[0,0 1600x900] (528 msec)
[log] CLICK on L(407,490)@S(0)[0,0 1600x900] (528 msec)
[2017-02-26 04:12:09] Checking fleet condition...
[2017-02-26 04:12:12] Light damage: 0; moderate damage: 0; critical damage: 1
[log] CLICK on L(252,248)@S(0)[0,0 1600x900] (529 msec)
[2017-02-26 04:12:19] Checking fleet condition...
[2017-02-26 04:12:22] Light damage: 1; moderate damage: 0; critical damage: 1
[log] CLICK on L(506,448)@S(0)[0,0 1600x900] (536 msec)
[log] CLICK on L(762,505)@S(0)[0,0 1600x900] (527 msec)
[2017-02-26 04:13:06] Sortie complete!
```

#### Relevant config snippet (if applicable)
```
Formations = combinedfleet_4, combinedfleet_4, combinedfleet_3, combinedfleet_4
NightBattles = false, false, true, true
RetreatLimit = 2
RepairLimit = 1
```

**Comment by mrmin123** [comment]
I can sanitize the inputs but KAGA should be outputting proper Python booleans (`True`/`False`, as opposed to `true`/`false`) which is what kancolle-auto was designed for. The issue is expounded for NB because it actually reads in a string, not a direct boolean. Please report this on the KAGA bug tracker.
