### ISSUE TITLE
Include Morale in sub switching

### ISSUE THREAD

**Issue by R-Jimenez** [mrmin123/kancolle-auto#325]
Title is pretty self-explanatory. Would be neat to expand the submarine switching mechanism to include morale as well as damage. Not sure if this conflicts with the current workflow (I'm not sure if it could parse out the ship which is fatigued, and then resolve the ship class), but was just a thought I had while playing around with things.

Sorry if this is not formatted correctly for a suggestion, and thanks for all the work you've put in into this amazing script. It's really a fun little marvel to someone who loves scripting.

**Comment by mrmin123** [comment]
This should be do-able. Will require additions to the config.

And yea, it's been fun working on this! I used to program pipelines and task automation professionally, so I'm a lot more interested in the optimization and customization of the automation capabilities of the script than actually playing the game at this point. Lots of interesting challenges to tackle in automating even a relatively simple game. I personally think that the game does a poor job in respecting the player's time, but that might just be me...

**Comment by R-Jimenez** [comment]
Hah, I feel you. These labors of love (the successful ones anyways) always come from someone who utilizes the tech for work in some regard. Glad you've managed to get some enjoyment out of it! As someone who comes and goes in KanColle, I think most people would agree some quality of life changes would be nice to the game.

**Comment by mrmin123** [comment]
Implemented as of above PR (01d50e0)
