### ISSUE TITLE
I-13 Kai / I-14 Kai missing from submarine switching

### ISSUE THREAD

**Issue by R-Jimenez** [mrmin123/kancolle-auto#327]
Small bug, but title is self-explanatory. The kais for both ships are not included in the fleet shiplist / allowed configuration, and so are not considered by the switching module. If you use one of them in your fleet you get to wait a couple hours and then come back scratching your head like I did.

**Comment by mrmin123** [comment]
I don't have the kai'ed version of these ships so I can't test myself, but they should work fine as-is. You're manually defining them in the `EnabledSubs` list as `i-13` and `i-14` without `all`?

**Comment by waicool20** [comment]
I-13 Kai and I-14 Kai are both working for me...if you mean they are not getting switched out, you got to make sure they don't use equipment that increases their ASW/AA stats

**Comment by R-Jimenez** [comment]
I had `i-13` and `i-14` in the config (alongside every other valid ID, not `all`), and adding `i-13-kai` or 'i-14-kai' caused a config crash (started saying a bunch of other parameters 'were invalid' as if I put a bad character somewhere) so I presumed that was the issue. However I then found out it was more widespread, where the sub switching seemed to fail to register SSV's as submarines, even when explicitly added.

Settings with I-58 in the docks.
Config:
[SubmarineSwitch]
Enabled = true
EnabledSubs = i-8, i-19, i-26, i-58, i-168, maruyu, ro-500, u-511, i-8-kai, i-13, i-14, i-19-kai, i-26-kai, i-58-kai, i-401
ReplaceLimit = 
FatigueSwitch = true

Console:
[93m[2017-03-12 09:47:49] Not all ships under repairs are submarines, or not all submarines could not be swapped out! Waiting for repairs![0m

I then flipped the FatigueSwitch off and re-ran to see if it would then recognize her, but no luck. So my next trial was to switch an under-repair I-168 kai into the mix, and see if it would register *her*. My working hypothesis without looking at the script is that the list is being used to swap in replacements, but if those replacements are SSV's then they will not be considered to be replaced themselves when they get damaged. This correlates with the result that when I put I-168 in the comp, the script naturally recognized her as an SS and moved to replace her.

Of note is that while the script was switching her out, it skipped over both I-13 kai and I-14 kai, but I do have them equipped with seaplanes, so their stats are increased as @waicool20  stated. I'll throw some torps on them and be done with it, but I'm curious, how does this factor in? My other SSV's also have seaplanes, but they get swapped in just fine (but not out).

**Comment by waicool20** [comment]
@R-Jimenez 
What I use in my orel cruising profile:
```
[SubmarineSwitch]
Enabled = False
EnabledSubs = i-8, i-8-kai, i-13, i-14, i-19, i-19-kai, i-58, i-58-kai, i-168, i-401, ro-500, u-511
ReplaceLimit = 0
FatigueSwitch = False
```

So as I found out myself the hard way(see #303), when the script tries to switch a ship out, it checks if its a sub by checking if its ASW and AA stats are 0 and not its kanji symbol, so basically if you have an SSV on the fleet with non-0 ASW or AA stat it'll be able to switch in but not switch out

**Comment by waicool20** [comment]
@mrmin123 Looking back at #303, I think you misunderstood me when I said kanji, I wonder why you couldn't just use something akin to:
![image](https://cloud.githubusercontent.com/assets/5538666/23832669/6608e4fc-0774-11e7-804e-fdb8b96cb9ef.png)
![image](https://cloud.githubusercontent.com/assets/5538666/23832676/860b904c-0774-11e7-84eb-06001e402fef.png)
so you could just skip going into the details page, might shave off a few seconds and we won't be running into the above problems.

**Comment by R-Jimenez** [comment]
I see, I see. Thanks for the clarification. I've stripped the planes for now, and hopefully will speed things along. Cheers mate!

**Comment by mrmin123** [comment]
@waicool20 you're right, I did mis-understand you at the time. I thought you meant the actual kanji of the ship's names, not their class icon, which I only noticed recently while looking into how to optimize vs PvP vs sub-heavy fleets.

For the time being, however, please stick to using equipment on SSVs that do not modify ASW and AA stats.

**Comment by mrmin123** [comment]
Closing this for now... relevant QOL improvement will occur with #331
