### ISSUE TITLE
Submarine Switching Bug

### ISSUE THREAD

**Issue by perryhuynh** [mrmin123/kancolle-auto#328]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 2017-02-28
* Viewer/browser: Chromium
* Operating system: Xubuntu 16.04

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: Consistent

When using `ro-500` for solo Orel Cruising, if I start with a lower level `ro-500`, she is correctly switched to the first/highest level `ro-500` after meeting the damage limit. But no submarine switching occurs after that.

#### Console log (if applicable)
```
[replace this line with ~50 lines of console log]
```

#### Relevant config snippet (if applicable)
```
[SubmarineSwitch]
Enabled = True
EnabledSubs = ro-500, u-511
ReplaceLimit = 1
FatigueSwitch = False
```

**Comment by waicool20** [comment]
Might be a similar problem to #327, make sure you don't have equipment like [Submarine Radar & Passive Radiolocator (E27)](http://kancolle.wikia.com/wiki/Submarine_Radar_%26_Passive_Radiolocator_(E27)) or sonars that will modify her ASW/AA stat from 0

**Comment by perryhuynh** [comment]
That's most likely the issue, didn't even realize the new submarine equipment gave AA
