### ISSUE TITLE
Error when trying to run all 3 exp in the same world?

### ISSUE THREAD

**Issue by AppleBoi86** [mrmin123/kancolle-auto#33]
I ran into a problem and would like some help. It just stops at HQ and tells me it couldn't " ensei_area_01.png".
## Here's the problem I encounter.

�C:\Windows\system32>call C:\Sikuli\runIDE.cmd -r C:\mrmin123\kancolle_auto.sikul
i
+++ running this Java
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
+++ trying to start Sikuli IDE
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar
C:\Sikuli\sikuli-ide.jar -r C:\mrmin123\kancolle_auto.sikuli
�[94m[2015-10-11 02:40:10] Reading config file�[0m
�[92m[2015-10-11 02:40:10] Config loaded!�[0m
�[92m[2015-10-11 02:40:10] Starting kancolle_auto�[0m
�[94m[2015-10-11 02:40:10] Focus on KanColle!�[0m
[log] App.focus KanColleViewer(0) #0
�[92m[2015-10-11 02:40:16] At Home!�[0m
�[94m[2015-10-11 02:40:16] Are there returning expeditions to receive?�[0m
�[94m[2015-10-11 02:40:20] No, no fleets to receive!�[0m
�[92m[2015-10-11 02:40:20] Refreshing Home!�[0m
[log] CLICK on L(926,69)@S(0)[0,0 1600x900]
[log] CLICK on L(821,472)@S(0)[0,0 1600x900]
�[92m[2015-10-11 02:40:35] At Home!�[0m
�[94m[2015-10-11 02:40:35] Are there returning expeditions to receive?�[0m
�[94m[2015-10-11 02:40:39] No, no fleets to receive!�[0m
�[94m[2015-10-11 02:40:39] Navigating to Expedition menu!�[0m
[log] CLICK on L(963,286)@S(0)[0,0 1600x900]
[log] CLICK on L(1437,256)@S(0)[0,0 1600x900]
�[94m[2015-10-11 02:40:43] Let's send an expedition out!�[0m
[log] CLICK on L(899,453)@S(0)[0,0 1600x900]
[log] CLICK on L(1063,248)@S(0)[0,0 1600x900]
[log] CLICK on L(1441,461)@S(0)[0,0 1600x900]
�[94m[2015-10-11 02:40:53] Trying to send out fleet 3 for expedition 3�[0m
[log] CLICK on L(1185,137)@S(0)[0,0 1600x900]
�[91m[2015-10-11 02:40:55] Fleet not available. Check back later!�[0m
�[94m[2015-10-11 02:40:55] Focus on KanColle!�[0m
[log] App.focus KanColleViewer(0) #0
�[94m[2015-10-11 02:41:04] Going Home!�[0m
[log] CLICK on L(835,276)@S(0)[0,0 1600x900]
�[92m[2015-10-11 02:41:07] At Home!�[0m
�[94m[2015-10-11 02:41:07] Are there returning expeditions to receive?�[0m
�[94m[2015-10-11 02:41:10] No, no fleets to receive!�[0m
�[94m[2015-10-11 02:41:10] Let's send an expedition out!�[0m
[error] script stopped with error in line 320
[error] FindFailed ( can not find ensei_area_01.png on the screen. )
Exception in thread "main" java.lang.IllegalStateException: No match found
at java.util.regex.Matcher.group(Unknown Source)
at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(J
ythonScriptRunner.java:326)
at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScri
ptRunner.java:290)
at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunn
er.java:200)
at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunn
er.java:162)
at org.sikuli.basics.SikuliScript.main(SikuliScript.java:181)
at org.sikuli.ide.SikuliIDE.main(SikuliIDE.java:212)

**Comment by kevin01523** [comment]
try this one runScript -d 2 -r path to script use sikuli 1.0.1 option 2 and 5

**Comment by mrmin123** [comment]
Problem arises when the fleet is already sent out on another expedition than the one it is assigned in the config.

**Comment by AppleBoi86** [comment]
Thank you both of you. My bad for setting the wrong exp. All is good now. 

Does it matter if I use IDE instead of Script?

Also, I love how you make everything user friendly, mrmin123. Especially that config.ini.

**Comment by kevin01523** [comment]
hmm i tihink its possible same as damage check the busy check well its just check if the fleet is busy but instead of checking the time it will recheck that specific fleet after a certain amount of time

**Comment by mrmin123** [comment]
Script should no longer crash when an expedition fleet is out on an expedition other than the one assigned in the config file for the script.

**Comment by mrmin123** [comment]
@AppleBoi86 I've never tried the IDE version of Sikuli, but if it works for you, it works! And thanks; if you find anything poorly worded/confusing in the config or rest of the documentation let me know.
