### ISSUE TITLE
U-511 Submarine Switch Image

### ISSUE THREAD

**Issue by perryhuynh** [mrmin123/kancolle-auto#333]
I can do a PR for this, but should the `fleetcomp_shiplist_submarine_u-511.png` image be replaced to one similar to `fleetcomp_shiplist_submarine_i-168.png` to accommodate for U-511 Kai, or create an entirely new asset for U-511 Kai?

**Comment by mrmin123** [comment]
Forgot that U-511 Kai existed! I'll take care of it shortly.

**Comment by mrmin123** [comment]
Updated asset:

![fleetcomp_shiplist_submarine_u-511](https://cloud.githubusercontent.com/assets/4326866/23835448/e32d655c-0724-11e7-915b-1cb39ba085e0.png)

Will be merged into master later
