### ISSUE TITLE
Fleet comp switching missing button click.

### ISSUE THREAD

**Issue by R-Jimenez** [mrmin123/kancolle-auto#345]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 2017-03-17
* Viewer/browser: Chrome / KC3Kai
* Operating system: Windows 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: Consistent.

When the script goes to switch fleet comps, it misses the load button, clicking just to the right of it to no effect.

**Comment by mrmin123** [comment]
This ticket will also involve adding support for fleet comp positions 5~10.
