### ISSUE TITLE
Repair Failure

### ISSUE THREAD

**Issue by Aripracc** [mrmin123/kancolle-auto#355]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 9.1
* Viewer/browser: KC3
* Operating system: Debian

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:
Consistent, when determining that a repair is now required kancolle-auto will navigate to the repair screen. It appears to then click somewhere random and restart.

#### Console log (if applicable)
https://gist.github.com/Aripracc/83e1016e1adcac9b4345b73b212cd3fe
I sanitized most of this log for my own safety, this log completes two runs and then needs to repair. But will always fail to repair and simply loop here forever.

**Comment by Aripracc** [comment]
I was able to get a more useful log by disabling basic recovery.
```
[2017-04-03 21:13:37] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: repair_timer_alt.png: (92x72) in R[259,94 800x480]@S(0) E:Y, T:1.0
  Line 2476, in file Region.java

[error] script [ /kancolle-auto/kancolle_auto.sikuli ] stopped with error in line 542
[error] FindFailed ( repair_timer_alt.png: (92x72) in R[259,94 800x480]@S(0) E:Y, T:1.0 )
[error] --- Traceback --- error source first
line: module ( function ) statement 
448: combat (  go_repair )     repair_timer_alt_matches = self.kc_region.findAll(Pattern('repair_timer_alt.png').similar(0.5))
252: main (  sortie_action )     combat_item.go_repair()
412: main (  init )     sortie_action()
434: main (  kancolle_auto_wrapper )     init()
540: main (  <module> )     kancolle_auto_wrapper()
[error] --- Traceback --- end --------------
[KAGA] [2017-04-03 21:13:37] [c.w.k.k.KancolleAuto] INFO - Kancolle Auto session has terminated!
[KAGA] [2017-04-03 21:13:37] [c.w.k.k.KancolleAuto] DEBUG - Exit Value was 1
[KAGA] [2017-04-03 21:13:37] [c.w.k.k.KancolleAuto] INFO - Kancolle Auto didn't terminate gracefully
```

**Comment by mrmin123** [comment]
Merged to `master`. Thanks for the PR!
