### ISSUE TITLE
Doesn't work with EO anymore.

### ISSUE THREAD

**Issue by FanedColossapede** [mrmin123/kancolle-auto#360]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): #### 2017-04-03
* Viewer/browser: Electronic Observer Version 2.1.8 [TL 2.1a] (https://github.com/RyuuKitsune/ElectronicObserver/releases/tag/2.1.8-2.1a), and the Chinese version of EO (https://github.com/RadarNyan/ElectronicObserver)
* Operating system: Windows 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:

Kancolle Auto does not capture the browser (EO in this case) running KC.

#### Console log (if applicable)
```
[replace this line with ~50 lines of console log]
```

#### Relevant config snippet (if applicable)
```
[replace this line with relevant portion from config with comments removed]
```

**Comment by mrmin123** [comment]
I'm away from my machine so I can't test this right now, but could you
confirm it was working before? Does it bring the app to the foreground at
least? Have you tried clicking into the window on kancolle-auto start?

**Comment by mrmin123** [comment]
Closing due to lack of updates.
