### ISSUE TITLE
morale enhancing routine for expeditions?

### ISSUE THREAD

**Issue by SomeGuyKyon** [mrmin123/kancolle-auto#362]
Is there any plan for the morale enhancing sortie routine?

Usually I do so-called "kira(twinkle, morale enhanced)" for expedition fleets to get more rewards.

Set a ship from expedition fleet that needs morale enhancing in 1st place of a fleet, put some dummy ships to avoid damage toward the 1st ship. and then send them sorties to 1-1 until the 1st ship reaches maximum morale. Switching the 1st place of a fleet to other ship that was in the expedition fleet.

well, I guess it needs lotta works.
1. need to form a fleet according to expedition setting(specifically config-written by user I think? especially written in ships name like [Satsuki(DD), Oboro(DD), Kasumi(DD), Abukuma(CVL)]).
2. need to search for the ships
3. need to search for the dummy ships(which is mainly destroyers not heart-locked).

is this possible?

**Comment by mrmin123** [comment]
Unfortunately the method you're talking about, as you've said, will take a lot of work. The amount of assets needed to be generated is prohibitive, to say the least.

A possible alternative would be to use the fleet presets to cycle the sorties to 1-1 with, but I don't know if that's a desirable solution, either.

**Comment by waicool20** [comment]
Cycling presets can be done with my patch #350 I guess you can try that

**Comment by SomeGuyKyon** [comment]
Thank you for your replies! I'm thinking of trying some extensions by manipulating config file with own Python code outside of Kancolle-auto.
