### ISSUE TITLE
Event port check should be expanded

### ISSUE THREAD

**Issue by R-Jimenez** [mrmin123/kancolle-auto#365]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 2017-05-?? (Mystery version :o)
* Viewer/browser: KC3
* Operating system: Windows 7

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:
Consistent.

Events cannot be sortied if there are less than five ship slots available, yet port check doesn't seem to properly trigger, resulting in the script having to soft-recover and try again infinitely. Going to build up some drops through 3-2 training and see what the event UI shows and how it compares to the current warning scan. It's a minor issue, but seeing it loop incessantly is irritating on a design level.

**Comment by mrmin123** [comment]
Assets for checking ports in and out of Events are outdated due to the UI update kancolle got a while back. I have the Event one, but not the normal one.

**Comment by mrmin123** [comment]
Oh, never mind, the non-Event one is still fine.
