### ISSUE TITLE
There is problem on starting kancolle-auto

### ISSUE THREAD

**Issue by purol** [mrmin123/kancolle-auto#372]
* kancolle-auto version (date on first line of your CHANGELOG.md): 2017-05-07
* Viewer/browser: Chrome
* Operating system: Windows 10

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: consistent

When I click start of KAGA, it doesn't work with some error message.
Here is a link : [http://imgur.com/a/SV7W3](http://imgur.com/a/SV7W3)

#### Console log (if applicable)

does the console log mean Debug log?
then, see the upper [link](http://imgur.com/a/SV7W3)

#### Relevant config snippet (if applicable)
```
[General]
Program = Chrome
RecoveryMethod = KC3
BasicRecovery = True
JSTOffset = 0
SleepCycle = 20
Paranoia = 1
SleepModifier = 0

[ScheduledSleep]
Enabled = True
StartTime = 0030
SleepLength = 3.5

[ScheduledStop]
Enabled = False
Mode = TIME
Count = 5

[Expeditions]
Enabled = True
Fleet2 = 2
Fleet3 = 5
Fleet4 = 11

[PvP]
Enabled = True
FleetComp = 1

[Combat]
Enabled = True
FleetComp = 2
Area = 2
Subarea = 3
CombinedFleet = False
Nodes = 5
NodeSelects = 
Formations = line_ahead
NightBattles = False
RetreatLimit = 2
RepairLimit = 0
RepairTimeLimit = 0030
CheckFatigue = False
PortCheck = False
MedalStop = False
LastNodePush = False

[SubmarineSwitch]
Enabled = True
EnabledSubs = ss
ReplaceLimit = 0
FatigueSwitch = True

[LBAS]
Enabled = False
EnabledGroups = 1
Group1Nodes = 
Group2Nodes = 
Group3Nodes = 

[Quests]
Enabled = True
Quests = bd1, bd2, bd3, bd4, bd5, bd6, bd7, bd8, bw1, bw2, bw3, bw4, bw5, bw6, bw7, bw8, bw9, bw10, c2, c3, c4, c8, d2, d3, d4, d9, d11, e3, e4
CheckSchedule = 5

```

**Comment by mrmin123** [comment]
Kancolle-auto runs fine with that config via command line. This is probably an issue with KAGA, which I don't maintain. Please make a ticket on the [KAGA issue tracker](https://github.com/waicool20/KAGA/issues).

Pinging @waicool20 just in case.

**Comment by waicool20** [comment]
Not a Kaga problem either most likely a jython problem with the bundled jython that comes with SikuliX install, try reinstalling SikuliX if you are not using system Jython, would also be nice if you could show the rest of the debug/console, as it also shows what command its using to launch kancolle-auto

**Comment by mrmin123** [comment]
@purol could you copy and paste the full log? Also, please try running kancolle-auto via command line and see it runs or not (I'm guessing not). This might be an issue/conflict with your environment setup.

**Comment by purol** [comment]
This problem occurred by the name of folder.
I named folder in Korean.
After I changed it in English, the error disappeared.
Sorry for making you confused.
