### ISSUE TITLE
exception in thread "main" java.lang.noclassdeffounderror: org/sikuli/basics/hotkeylistener

### ISSUE THREAD

**Issue by lainconnue** [mrmin123/kancolle-auto#375]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md):downloaded to pc dated today
* Viewer/browser:kc3
* Operating system: win 10 64bit

#### Issue
So i've followed the wiki on installing as much as possible (Then again I might be wrong)
![image](https://cloud.githubusercontent.com/assets/20400916/26526106/4d86f628-43a9-11e7-8822-31cda8d21e2b.png)
![image](https://cloud.githubusercontent.com/assets/20400916/26526110/6b83db3c-43a9-11e7-9376-1146eeecf470.png)
![image](https://cloud.githubusercontent.com/assets/20400916/26526113/8522ae38-43a9-11e7-8670-c31fc13a25a1.png)

I think the problem occured with sikulix. So, I went over to the link in set up wiki page to try and download again but I can't seem to find the said version through the links.

So I went over to their chatroom and asked for direction to said version and is currently waiting for reply.

![image](https://cloud.githubusercontent.com/assets/20400916/26526148/b77e3cc0-43aa-11e7-9216-4f5b1d005a36.png)

Meanwhile, I am contemplating on whether or not to dowload the latest build of sikuli 1.1.1 as placed here: https://launchpad.net/sikuli/+download
Edit: what happened when i installed newest 1.1.1 in another folder.
![image](https://cloud.githubusercontent.com/assets/20400916/26528005/66b16962-43db-11e7-9d3b-50382c6c0a24.png)

Edit as of 30th May 2017:
After uninstalling java reinstalling it and then downloading newest 1.1.1. I can start kancolle auto no problem. Been using it for a day now no issue so far, just that in orel the subs always go into night battle even when night battle parameter is set as false.

Thanks for taking the time to read through the issue.
```

**Comment by R-Jimenez** [comment]
Concerning your night battle issue, from the config section of the wiki, bolded for emphasis:

> NightBattles — Define whether or not to engage in night battle at each combat node, separated by commas. **If you specify less values than the number of Nodes, kancolle-auto will automatically use True for the remaining nodes.**

**Comment by lainconnue** [comment]
I must have overlooked that one I assumed something kike that was
implemented so I have already changed. Was going to edit it out . Thanks
anyway

On 30 May 2017 21:02, "R-Jimenez" <notifications@github.com> wrote:

Concerning your night battle issue, from the config section of the wiki,
bolded for emphasis:

NightBattles — Define whether or not to engage in night battle at each
combat node, separated by commas. *If you specify less values than the
number of Nodes, kancolle-auto will automatically use True for the
remaining nodes.*

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mrmin123/kancolle-auto/issues/375#issuecomment-304871115>,
or mute the thread

**Comment by mrmin123** [comment]
Looks like this has been resolved, so closing.
