### ISSUE TITLE
Sub names broken in latest update

### ISSUE THREAD

**Issue by muromachi** [mrmin123/kancolle-auto#380]
Hmmm, latest update broke the sub switch feature because the spacing between the ship class and ship name changed ><

![fleetcomp_shiplist_submarine_i-26](https://cloud.githubusercontent.com/assets/25769016/26834683/97149f3c-4b08-11e7-97da-93daecb12a0b.png)
![fleetcomp_shiplist_submarine_u-511](https://cloud.githubusercontent.com/assets/25769016/26834696/9e8129ac-4b08-11e7-80cb-e910cc18125b.png)
![fleetcomp_shiplist_submarine_ro-500](https://cloud.githubusercontent.com/assets/25769016/26834714/a7699f7c-4b08-11e7-9a92-81fbb644842d.png)
![fleetcomp_shiplist_submarine_maruyu](https://cloud.githubusercontent.com/assets/25769016/26834723/afbc04bc-4b08-11e7-896f-a242f623471f.png)
![fleetcomp_shiplist_submarine_i-58](https://cloud.githubusercontent.com/assets/25769016/26834728/b3df9a5e-4b08-11e7-8f52-3945bb3a6435.png)

I did some, hope they are ok? (they work for me)

**Comment by lainconnue** [comment]
Yes. I thought I was the only one where sub switch would fail and wait for
rep. Thank you.

**Comment by mrmin123** [comment]
Oof, I haven't had a chance to look at the game yet but thanks for the heads up. There are more stringent guidelines for the submarine switch assets [here](https://github.com/mrmin123/kancolle-auto/wiki/Asset-generation-guide#submarine-switch-assets), but if those work for you by all means continue using them until I get around to providing an 'official' update.
