### ISSUE TITLE
Submarine Switch not functioning

### ISSUE THREAD

**Issue by moonlee7777** [mrmin123/kancolle-auto#383]
#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): #### 2017-04-03
* Viewer/browser: KC3
* Operating system: Windows 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: Constant

Submarine switch doesn't switch submarines

#### Relevant config snippet (if applicable)
```
[Combat]
Enabled = True
FleetComp = 2
Area = 2
Subarea = 3
CombinedFleet = False
Nodes = 5
NodeSelects =
Formations = line_ahead
NightBattles = False, False, False
RetreatLimit = 2
RepairLimit = 1
RepairTimeLimit = 9999
CheckFatigue = False
PortCheck = False
MedalStop = False
LastNodePush = False

[SubmarineSwitch]
Enabled = True
EnabledSubs = all
ReplaceLimit = 1
FatigueSwitch = True
```

**Comment by lainconnue** [comment]
Get the latest kcauto or update the sub asset. The newest kancolle update
early june disrupted the position. There is already a solved issue relevant
to your query.
