### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by KofukuGT** [mrmin123/kancolle-auto#387]
not able to install the command prompt thing

**Comment by lainconnue** [comment]
The command prompt is already in your windows. Click windows key type
command prompt or windows key + R and then cmd.

**Comment by KofukuGT** [comment]
but i cant enter the thing it doesnt work

**Comment by KofukuGT** [comment]
i need someone to walk me thru the installation i think

**Comment by waicool20** [comment]
You can use KAGA if you have all the files downloaded and installed instead of the command line, https://github.com/waicool20/kaga

**Comment by KofukuGT** [comment]
i dk how to enter configs too but i have java and sikuli

**Comment by waicool20** [comment]
Just download KAGA and it will have GUI for you to set configs

**Comment by KofukuGT** [comment]
ok ill try that and ill msg u soon

**Comment by waicool20** [comment]
Your welcome to join discord for simple questions: https://discord.gg/2tt5Der

**Comment by KofukuGT** [comment]
what is the kancolle auto root

**Comment by waicool20** [comment]
The directory containing `CHANGELOG.md`, `config.ini` etc.

**Comment by KofukuGT** [comment]
ok thx

**Comment by KofukuGT** [comment]
but i did it but even when i run kc3 still does not work

**Comment by waicool20** [comment]
Can you copy the messages inside the debug window over here?

**Comment by KofukuGT** [comment]
it says its starting and running but there is no action

**Comment by waicool20** [comment]
Yes just copy the messages over here so we can know what's happening in detail

**Comment by KofukuGT** [comment]
ok trying to do it now

**Comment by KofukuGT** [comment]
[KAGA] [2017-07-07 21:30:40] [c.w.k.k.KancolleAuto] INFO - Starting new Kancolle Auto session
[KAGA] [2017-07-07 21:30:40] [c.w.k.k.KancolleAuto] DEBUG - Launching with command: java -jar C:\Users\Kaiee\Downloads\sikulix.jar -r C:\Users\Kaiee\Desktop\kc auto\kancolle-auto-10\kancolle_auto.sikuli
[KAGA] [2017-07-07 21:30:40] [c.w.k.k.KancolleAuto] DEBUG - Session profile: {"general":{"offset":-1,"jstOffset":-1,"basicRecovery":true,"sleepCycle":20,"paranoia":1,"program":"Chrome","sleepModifier":0,"recoveryMethod":"KC3"},"scheduledSleep":{"length":3.5,"enabled":false,"startTime":"0030"},"scheduledStop":{"count":5,"enabled":false,"mode":"TIME"},"expeditions":{"enabled":true,"fleet4":"21","fleet2":"2","fleet3":"5"},"pvp":{"enabled":false,"fleetComp":1},"sortie":{"enabled":true,"repairTimeLimit":"0030","subarea":"5","nodeSelects":[],"nightBattles":[false],"formations":["LINE_AHEAD"],"combinedFleet":false,"repairLimit":1,"reserveDocks":false,"lastNodePush":false,"portCheck":false,"medalStop":false,"fleetComps":[1],"retreatLimit":2,"checkFatigue":false,"area":"1","nodes":1},"submarineSwitch":{"enabled":true,"enabledSubs":["SS"],"replaceLimit":0,"fatigueSwitch":false,"useBuckets":false},"lbas":{"enabled":false,"group2Nodes":[],"enabledGroups":[],"group1Nodes":[],"group3Nodes":[]},"quests":{"enabled":true,"quests":["bd1","bd2","bd3","bd4","bd5","bd6","bd7","bd8","bw1","bw2","bw3","bw4","bw5","bw6","bw7","bw8","bw9","bw10","c2","c3","c4","c8","d2","d3","d4","d9","d11","e3","e4"],"checkSchedule":5},"name":"1-5a (Abukuma)"}
Jul 07, 2017 9:30:41 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

**Comment by waicool20** [comment]
You are using chrome for kancolle right? or KC3?

**Comment by KofukuGT** [comment]
yes

**Comment by KofukuGT** [comment]
kc3kai

**Comment by waicool20** [comment]
Hmm not so sure what is happening then, try letting it run longer after you start it. 

The discussion is getting a bit long winded, I recommend continuing in discord.

**Comment by KofukuGT** [comment]
ok

**Comment by waicool20** [comment]
@mrmin123 should be solved, can close

**Comment by mrmin123** [comment]
@waicool20 thanks for helping with this.
