### ISSUE TITLE
Environment:

### ISSUE THREAD

**Issue by zergling50** [mrmin123/kancolle-auto#388]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* 2017-06-07 ([Release 10]
* KC3/Chrome
* Windows 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?: Consistent

As soon as I launch Kancolle Auto from a bat file the command prompt opens, skims through some lines, and then crashes. Since it crashed so fast I had to use prnt screen to catch the command prompt info, but I have a picture here (slightly transparent as it was hard to time the prnt screen)

![error code verbose](https://user-images.githubusercontent.com/30790150/29012701-98749f0c-7b0b-11e7-83ff-e3b584e69bce.png)

#### Console log (if applicable)
See above screenshot

#### Relevant config snippet (if applicable)
```


[General]
Program = Chrome
RecoveryMethod = KC3
BasicRecovery = True
JSTOffset = 17SleepCycle = 20
Paranoia = 3
SleepModifier = 2

[ScheduledSleep]
Enabled = True
StartTime = 0030
SleepLength = 9.0[ScheduledStop]
Enabled = TrueMode = sortie
Count = 40[Expeditions]
Enabled = True
Fleet2 = 9
Fleet3 = 13Fleet4 = 2
[PvP]
Enabled = False
FleetComp = 1

[Combat]
Enabled = True
FleetComps = 0
Area = 1Subarea = 5CombinedFleet = False
Nodes = 3
NodeSelects =
Formations = line_ahead, line_abreast, line_abreast
NightBattles = False
RetreatLimit = 1RepairLimit = 1
RepairTimeLimit = 0200
ReserveDocks = False
CheckFatigue = True
PortCheck = False
MedalStop = False
LastNodePush = False

[SubmarineSwitch]
Enabled = False
EnabledSubs = ss
ReplaceLimit =
FatigueSwitch = False
UseBuckets = False

[LBAS]
Enabled = False
EnabledGroups =
Group1Nodes =
Group2Nodes =
Group3Nodes =

[Quests]
Enabled = True
Quests = bd1, bd2, bd3, d2, d3, d4, e3, e4
CheckSchedule = 5
```

**Comment by mrmin123** [comment]
@zergling50 You're missing some newlines/linebreaks in your config file. Try this:

```


[General]
Program = Chrome
RecoveryMethod = KC3
BasicRecovery = True
JSTOffset = 17
SleepCycle = 20
Paranoia = 3
SleepModifier = 2

[ScheduledSleep]
Enabled = True
StartTime = 0030
SleepLength = 9.0

[ScheduledStop]
Enabled = True
Mode = sortie
Count = 40

[Expeditions]
Enabled = True
Fleet2 = 9
Fleet3 = 13
Fleet4 = 2

[PvP]
Enabled = False
FleetComp = 1

[Combat]
Enabled = True
FleetComps = 0
Area = 1
Subarea = 5
CombinedFleet = False
Nodes = 3
NodeSelects =
Formations = line_ahead, line_abreast, line_abreast
NightBattles = False
RetreatLimit = 1
RepairLimit = 1
RepairTimeLimit = 0200
ReserveDocks = False
CheckFatigue = True
PortCheck = False
MedalStop = False
LastNodePush = False

[SubmarineSwitch]
Enabled = False
EnabledSubs = ss
ReplaceLimit =
FatigueSwitch = False
UseBuckets = False

[LBAS]
Enabled = False
EnabledGroups =
Group1Nodes =
Group2Nodes =
Group3Nodes =

[Quests]
Enabled = True
Quests = bd1, bd2, bd3, d2, d3, d4, e3, e4
CheckSchedule = 5
```

**Comment by zergling50** [comment]
I did that and now that first error is gone, however now it's crashing again and I don't see any errors in the command prompt. Here's a new screenshot.

![error code 2 verbose](https://user-images.githubusercontent.com/30790150/29038930-55a28fce-7b77-11e7-9338-2fcaef727ee0.png)

Sorry about this but thank you for your help so far!

**Comment by mrmin123** [comment]
Oh, `FleetComps = 0` in the `Combat` section should be `FleetComps = 1` for the default fleet.

**Comment by mrmin123** [comment]
Closing as this is a config issue.
