### ISSUE TITLE
Support for Luigi Torelli/Different Forms

### ISSUE THREAD

**Issue by twisting2017** [mrmin123/kancolle-auto#396]
Hello,

it would be nice if Luigi Torelli and her subforms could be added to the submarine switcher module.

assets:
![i-504](https://user-images.githubusercontent.com/21052240/30660229-76615be6-9e40-11e7-8e38-51374f640f47.png)
![luigi](https://user-images.githubusercontent.com/21052240/30660228-765e520c-9e40-11e7-9b5d-1fa8a2b22cef.png)
![luigi_kai](https://user-images.githubusercontent.com/21052240/30660230-7669ffc6-9e40-11e7-92fb-3be4abc6cdda.png)
![uit-25](https://user-images.githubusercontent.com/21052240/30660227-765d820a-9e40-11e7-90f7-0af33fbab1c9.png)

**Comment by mrmin123** [comment]
There is already support for base Luigi. I'd like to add I-504 and UIT-25 but your assets don't match the [asset generation guidelines](https://github.com/mrmin123/kancolle-auto/wiki/Asset-generation-guide#submarine-switch-assets). Could you re-generate for the ships you still have access to?

**Comment by twisting2017** [comment]
hope this works:
![i-504_neu](https://user-images.githubusercontent.com/21052240/30770866-54b5f504-a03b-11e7-9d8a-9e94745343ba.png)
