### ISSUE TITLE
I can't run Kancolle-auto

### ISSUE THREAD

**Issue by shiragasama** [mrmin123/kancolle-auto#402]
#### Issue
Help me! I did all the step 1,2,3,4,5. But i dont know how to run kancolle-auto. I copied the code "java -jar <path_to_sikuli>\sikulix.jar -r <path_to_kancolle_auto>\kancolle_auto.sikuli" but it kept messaging me like this. I dont know what to do. Maybe someone can show me a tutorial video please?
...
![image](https://user-images.githubusercontent.com/32711085/31453790-788bf130-aedd-11e7-83c4-24700906576e.png)
...
#### Relevant config snippet (if applicable)
By the way, I want to sortie 1-5 node A for leveling DD/CL. So I edited like this, is it ok?
...
[Combat]
Enabled = True
FleetComps = 1
Area = 1
Subarea = 5
CombinedFleet = False
Nodes = 1
NodeSelects =
Formations = line_abreast
NightBattles = False
RetreatLimit = 2
RepairLimit = 1
RepairTimeLimit = 0030
ReserveDocks = False
CheckFatigue = False
PortCheck = True
MedalStop = False
LastNodePush = False
```

**Comment by mrmin123** [comment]
You need to actually replace the <path_to> values in the command with
actual paths; those are meant to be placeholder values.

Configuration looks good from a quick gander

**Comment by shiragasama** [comment]
Can I see your path code? I learned a little C language, so i'm not really good in these stuffs

**Comment by mrmin123** [comment]
So if your sikulix.jar is in c:/sikuli, you'd write the sikuli path as
c:/sikuli/sikulix.jar, and if your kancolle auto is in
c:/sikuli/kancolle-auto, the conplete path would be
c:/sikuli/kancolle-auto/kancolle-auto.sikuli

**Comment by mrmin123** [comment]
So the command would become java -jar c:/sikuli/sikulix.jar -r c
:/sikuli/kancolle-auto/kancolle-auto.sikuli

**Comment by shiragasama** [comment]
Thanks for your guide. I made it. But I got new problem: the mouse random click and move, not like my want. Just wait a minute, I'll show screen record

**Comment by shiragasama** [comment]
https://youtu.be/dLhAw8jLL1M
(im so sorry, bandicam hide the mouse. but you can imagine it rendom moves after 1-2 sec, and random click)
I'm trying to use kancolle-auto for 1-5 A. So all I need is click sortie, choose 1-5, choose line abreast, and go back. But i dont know what it's doing

**Comment by shiragasama** [comment]
By the way, this is my whole config. I dont think it's wrong :/
[General]
Program = Google Chrome
RecoveryMethod = KC3
BasicRecovery = True
JSTOffset = 2
SleepCycle = 20
Paranoia = 3
SleepModifier = 0

[ScheduledSleep]
Enabled = True
StartTime = 0030
SleepLength = 5.5

[ScheduledStop]
Enabled = False
Mode = time
Count = 5

[Expeditions]
Enabled = True
Fleet2 = 21
Fleet3 = 13
Fleet4 = 2

[PvP]
Enabled = False
FleetComp = 1

[Combat]
Enabled = True
FleetComps = 1
Area = 1
Subarea = 5
CombinedFleet = False
Nodes = 1
NodeSelects =
Formations = line_abreast
NightBattles = False
RetreatLimit = 2
RepairLimit = 1
RepairTimeLimit = 0030
ReserveDocks = False
CheckFatigue = False
PortCheck = True
MedalStop = False
LastNodePush = False

[SubmarineSwitch]
Enabled = False
EnabledSubs = ss
ReplaceLimit =
FatigueSwitch = False
UseBuckets = False

[LBAS]
Enabled = False
EnabledGroups =
Group1Nodes =
Group2Nodes =
Group3Nodes =

[Quests]
Enabled = False
Quests = bd1, bd2, bd3, bd4, bd5, bd6, bd7, bd8, bw1, bw2, bw3, bw4, bw5, bw6, bw7, bw8, bw9, bw10, c2, c3, c4, c8, d2, d3, d4, d9, d11, e3, e4
CheckSchedule = 5

**Comment by shiragasama** [comment]
Okay after minutes random moves, it still does sortie like i want. But is there anyway to let it clicks faster? 3-5 secs for a click is too slow, just asking. That is my final question!

**Comment by mrmin123** [comment]
Not at the moment. I would recommend turning down the Paranoia setting in your config to 0 or 1 for faster iterations. kcauto-kai will have faster performance.
