### ISSUE TITLE
18-10-2017 Kancolle UI Changes

### ISSUE THREAD

**Issue by waicool20** [mrmin123/kancolle-auto#407]
They updated the UI today, will be opening this issue to post screenshots of some potential assets that need to be updated.

**Comment by waicool20** [comment]
![image](https://user-images.githubusercontent.com/5538666/31715898-3bc1f960-b438-11e7-8b37-c6059794792c.png)
Nav bar as seen from the pvp screen
![image](https://user-images.githubusercontent.com/5538666/31715910-56980e96-b438-11e7-9351-59585b2038c1.png)
New expedition screen (Note the different pvp button in nav bar)
![image](https://user-images.githubusercontent.com/5538666/31715971-976e04ca-b438-11e7-9c6f-27c9900f0b97.png)
New back button in quest menu i think?

**Comment by waicool20** [comment]
![image](https://user-images.githubusercontent.com/5538666/31716340-ebac868c-b439-11e7-8287-43a3a72db25a.png)
New Sortie button

**Comment by stackhanovets** [comment]
Looks like they done massive changes in expedition interface. I've made a hotfix. Please note **it does not contain all existing map templates**.
[kancolle_auto.sikuli.zip](https://github.com/mrmin123/kancolle-auto/files/1394565/kancolle_auto.sikuli.zip)

**Comment by shiragasama** [comment]
I'm here to waiting for the big fixing patch from gods

**Comment by waicool20** [comment]
Don't forget to join us on KC Auto discord~~ https://discord.gg/2tt5Der

**Comment by etcet54** [comment]
@stackhanovets thanks for the new images, but it seems the OCR is now somehow unable to detect running expedition and instead keep saying "expedition just returned", hence it keeps looping to send ongoing expedition.

working fine if no expedition running when starting kancolle-auto though.

**Comment by mrmin123** [comment]
Working on this now, hang tight.

**Comment by mrmin123** [comment]
Test branch: https://github.com/mrmin123/kancolle-auto/tree/407_ui_update

**Comment by Danielosama** [comment]
Have been running the script (expeditions only) and works fine.
Any possibility you'll add the new resupply option for expeditions?

**Comment by mrmin123** [comment]
PR merged, please update to master.

@Danielosama No, no plans for them in kancolle-auto at the moment.
