### ISSUE TITLE
Missed the sortie button

### ISSUE THREAD

**Issue by sanga000** [mrmin123/kancolle-auto#411]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 10.2
* Viewer/browser: Chrome
* Operating system: Windows 10

#### Issue
The mouse click simply missed the red "start sortie" button when it should be clicking it (it clicked the border of the button instead). Since the screen makes no change afterwards (as no button was actually clicked), KC Auto simply waits forever and does nothing. This has happened quite a few times already, but it is of course not not reproducible every time since the mouse click position is random.

As you can see here the mouse missed the "start sortie" button by a pixel or so. 
![kc-auto miss](https://user-images.githubusercontent.com/26204896/31979986-288ce6a4-b97c-11e7-81fe-c5020b839e03.png)
Edit: Screenshot seems to not show the mouse, so I just used the tip of the arrow to point where the mouse was pointing

Would it be possible to make the allowed positions for mouse click smaller?

Thanks

#### Console log (if applicable)
![kc-auto miss script](https://user-images.githubusercontent.com/26204896/31979901-b4f406b4-b97b-11e7-840a-f6021bce4ab8.png)

**Comment by stackhanovets** [comment]
@mrmin123 ,
I've also troubled with `menu_main_home.png`:

```
[...] Reading config file!
[...] Expeditions enabled: fleet 2: 6, fleet 3: 9, fleet 4: 21
[...] Combat enabled (PvP mode)


[...] Quests enabled
[...] Reading util config file!
[...] Config successfully loaded!
[...] Starting kancolle_auto!
[...] Finding window!
[...] Focus on KanColle!
[log] App.focus:  [...:Chrome]
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [...:Chrome]
[log]  TYPE "#ESC."
[...] Could not find Kancolle homepage after 10 attempts. Exiting script.
[error] script [ .../kancolle-auto/kancolle_auto.sikuli ] stopped with error in line 540
[error] Error caused by: Traceback (most recent call last):
  File ".../kancolle-auto/kancolle_auto.sikuli/kancolle_auto.py", line 540, in <module>
    kancolle_auto_wrapper()
  File ".../kancolle-auto/kancolle_auto.sikuli/kancolle_auto.py", line 540, in <module>
    kancolle_auto_wrapper()
  File ".../kancolle-auto/kancolle_auto.sikuli/kancolle_auto.py", line 434, in kancolle_auto_wrapper
    init()
  File ".../kancolle-auto/kancolle_auto.sikuli/kancolle_auto.py", line 360, in init
    focus_window()
  File ".../kancolle-auto/kancolle_auto.sikuli/kancolle_auto.py", line 68, in focus_window
    exit()
SystemExit

```

However, the solution was to replace `menu_main_home.png`:
![menu_main_home](https://user-images.githubusercontent.com/16455270/32007693-f1447658-b9b2-11e7-804d-fdc19f289275.png)

**Comment by sanga000** [comment]
Actually my problem has appeared for quite a while, so it has nothing to do with this patch (which changed a few details in the UI). I am guessing that the problem I posted is due to the allowed area for mouse click being one or two pixel lines larger than the the actual icon, hence the mouse click missed the button.

**Comment by mrmin123** [comment]
@sanga000 thanks for the report, surprised more people haven't ran into this.
