### ISSUE TITLE
Failed to focus after today's(2017-10-25) maintenance

### ISSUE THREAD

**Issue by etcet54** [mrmin123/kancolle-auto#413]
#### Environment details

* kancolle-auto version : 2017-10-18 ([Release 10.2]
* Viewer/browser: KC3 Kai
* Operating system: Windows 10

#### Issue is consistent

Hi, does anyone have an issue where kancolle-auto couldn't focus to google chrome after today's maintenance?

Tried to restart the machine and running on other machine, no luck. Could there be another UI change after this patch?

Thanks

#### Console log

![v34gh](https://user-images.githubusercontent.com/19471603/31995659-8f99ac14-b9af-11e7-866a-2cecb73d8895.jpg)

**Comment by Kiras756** [comment]
Also noticed, try this.
![menu_main_home](https://user-images.githubusercontent.com/26521625/31996421-26c9366e-b991-11e7-9e24-4a11118147fd.PNG)

**Comment by Kiras756** [comment]
file should be called menu_main_home.png

**Comment by etcet54** [comment]
@Kiras756 Thanks for the image good sir, will try and update shortly

**Comment by etcet54** [comment]
Confirmed works and function normally again, thanks a lot for the help.
