### ISSUE TITLE
Unable to focus on window after Kancolle maintenance 25/10/17.

### ISSUE THREAD

**Issue by kenahamtan** [mrmin123/kancolle-auto#414]
*Please read the FAQ/Common Issues section of the README before opening a ticket. Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kancolle-auto version (date on first line of your CHANGELOG.md): 10.2
* Viewer/browser: Chrome
* Operating system: Windows 10

#### Issue
Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)?:  consistent

After today update, kancolle auto could not focus on game window.

#### Console log (if applicable)
```
[2017-10-25 21:26:46] Reading config file!
[2017-10-25 21:26:46] Expeditions enabled: fleet 2: 11, fleet 3: 6, fleet 4: 5
[2017-10-25 21:26:46] Reading util config file!
[2017-10-25 21:26:46] Config successfully loaded!
[2017-10-25 21:26:46] Starting kancolle_auto!
[2017-10-25 21:26:46] Finding window!
[2017-10-25 21:26:46] Focus on KanColle!
[log] App.focus:  [6680:Chrome]
[log] App.focus:  [6680:Chrome]
[log]  TYPE "#ESC."
[log] App.focus:  [6680:Chrome]
[log]  TYPE "#ESC."
```

#### Relevant config snippet (if applicable)
```
[replace this line with relevant portion from config with comments removed]
```

**Comment by waicool20** [comment]
Fixed in https://github.com/mrmin123/kancolle-auto/pull/412

Consider joining us on discord to get quick news on script breakage :D https://discord.gg/2tt5Der

**Comment by kenahamtan** [comment]
Thanks you.
