### ISSUE TITLE
Add ability to specify different retreat and repair thresholds

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#43]
Example: only retreat on critical damage, but repair all ships that are moderately damaged after returning to base

**Comment by Danielosama** [comment]
I don't really know where to post this so here goes:
I discovered  this tool some days ago and I absolutely love it; it's clear to understand and works really well, I just have some questions:
1) I suck hard at scripts/consoles/Sikuli/etc but I still managed to launch the script through IDE (with some trial and error), by doing so it seems I can not see the timer indicating the next automated action (or maybe I'm not looking at the right place). Not asking you to fix that in particular, just to inform.
2) Is there a way to have your tool always up to date? I can see that you update it quite often, and I'm sure there is a better way than downloading the zip again and replace all the files :x 
3) I am very interested in using the combat module for 3-2A leveling, but since I'd not want to lose a sub or other ship, I have to ask: how likely is it that the script will sortie with a critically damaged sub? If it sorties, and the sub sinks, will it continue to sortie?
Thanks for your amazing work and for your answers!

**Comment by mrmin123** [comment]
Hey! Glad you're finding the tool useful.
1. Good to know. I actually haven't used Sikuli IDE so I'll add a note to the readme saying that you won't see the messages when running through the IDE. Is there a reason why you're not using sikuli-script?
2. The best way to keep it up to date would be to install git on your computer (there's also an IDE client for GitHub) and [clone this repository](https://help.github.com/articles/cloning-a-repository/). After that you can check against this repository and download any updates ([fetch + merge](http://githowto.com/pulling_changes)). I would recommend setting up a separate branch to keep changes to the config separate ([checkout](https://www.atlassian.com/git/tutorials/undoing-changes/git-checkout/)). You may still have to update files manually (probably the config) from time to time, at which point you might need to commit some stuff to your local repository. All of this might be simplified in the IDE version of GitHub.
3. It's highly unlikely that it will sortie with a critically damaged ship, but there are no guarantees. For what it's worth, the script checks your ships' damage status at the end of every battle, and before sortieing. Unfortunately, it does continue to sortie even after it loses a ship (I should really add a check for that). I did lose a ship at 3-2-A when I first implemented automatic sorties (RIP Furutaka), but that problem has been (hopefully) rectified since then. I've since leveled around 8 or so CAs to their Kai-Ni's and haven't lost a single ship over the weeks it took. It's pretty stable at the moment.

**Comment by mrmin123** [comment]
@Danielosama that said, regarding 2), if you don't want to deal with git at all, I think the zip download + replace is your best bet. If the source config.ini didn't change, you're safe just replacing everything but config.ini.

**Comment by Danielosama** [comment]
1.  I actually have no idea how to use sikuli-script :p  
   Most of the time I don't really know what I'm doing; I mean, it's a miracle I was able to install Python, Sikuli (doing the tessdata thing and all) and get your script to work in the first place x)
2.  The thing is, IDE is a bit dumb, I have to move quite a few files around to get your script to work when running through IDE. For example: the images from combat and expedition need to be in the same file where kancolle_auto.py is; another example is how I need to put combat.py, expedition.py and util.py in the same place where runIDE.cmd is. If I don't do this, then IDE says it can't find sh*\* and the script stops :/ 
   It's VERY probable that I'm just doing something wrong, but doing this is the only way I found to make it work with IDE (for now).
3.  Alright then, I'll give it a go :p

**Comment by kevin01523** [comment]
your on windows right? make sure your using version 1.0.1 if you downloaded 1.1.0 it only works on IDE

**Comment by Danielosama** [comment]
@kevin01523 I have the right version installed, that much I'm certain of.

**Comment by mrmin123** [comment]
@Danielosama using the IDE sounds really annoying. Have you tried the installation and usage steps outlined in the readme? It's just a matter of opening up the command prompt (Windows + R), navigating to the correct directory, and passing the correct parameters as indicated in the readme.

**Comment by Danielosama** [comment]
@mrmin123 I followed the readme instructions step by step :/ 
Since I am probably doing something wrong, I must ask: do I simply open cmd, navigate to kancolle_auto and then copy paste the parameters of the readme?

Edit: I just realised I have no sikuli-script in my Sikuli folder, maybe I did install something wrong.

**Comment by mrmin123** [comment]
@Danielosama it would be open cmd, navigate to where Sikuli-script is installed, and then copy-paste this command: `java -jar sikuli-script.jar -r <path_to_kancolle_auto>\kancolle_auto.sikuli` except replace `<path_to_kancolle_auto>` to where you have this repository downloaded. So if it's in `C:\kancolle_auto\`m it would be `java -jar sikuli-script.jar -r C:\kancolle_auto\kancolle_auto.sikuli`

Make sure that the kancolle_auto.sikuli directory exists under whatever you're specifying, since you're basically telling Sikuli to use the contents of that folder.

**Comment by Danielosama** [comment]
@mrmin123 Alright, it tells me "unable to access jarfile sikuli-script.jar", for some reason I do not have it installed even thought I followed the instructions. Maybe I should a clean install?

**Comment by mrmin123** [comment]
Yes, if sikuli-script.jar (or something similar) doesn't exist where you installed Sikuli, you might want to re-install it. Back up your tessdata folder, just in case!

**Comment by kevin01523** [comment]
ok make a folder named sikuli in C:\ copy sikuli-setup.jar install it with option 2 and 5 
then after installation delete libs folder
then copy contents of kancolle-auto or kancolle_auto.sikuli  and config.ini to C:\sikuli
edit config ini to your requirement
now open cmd 
on cmd 
type cd C:\
C:\WINDOWS\system32>cd C:\
C:>cd sikuli
now type
java -jar sikuli-script.jar -r -d 2 kancolle_auto.sikuli 
press enter

**Comment by Danielosama** [comment]
@kevin01523 Well, I did a clean install and all, and I definitely seem to be getting there, but it tells me the following "libs folder is in user's path but not activated".

**Comment by Danielosama** [comment]
Well I'll be damned, it finally works!! :D 
Thanks a lot for the help to both of you (and your patience with someone like me :p )

**Comment by kevin01523** [comment]
well i do encounter alot of problems in using sikuli and through experoince and googling i came up some fixes of my own just post any log here or make an issue if you encounter problems

**Comment by mrmin123** [comment]
@Danielosama good to hear that it's working for you now! And thanks for all your help with troubleshooting @kevin01523 !
