### ISSUE TITLE
App.focus loop

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#46]
ok i dont know what happened really happened i just found the script looping and kancolle on cat error

```
[2015-10-13 04:19:43] At Home!
[2015-10-13 04:19:43] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-13 04:19:48] No, no fleets to receive!
[2015-10-13 04:19:48] Navigating to Expedition menu!
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(496,383)@S(0)[0,0 1360x768]
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[debug] waiting for expedition.png to appear
[debug] expedition.png has appeared.
[log] CLICK on L(970,353)@S(0)[0,0 1360x768]
[debug] waiting for expedition_screen_ready.png to appear
[debug] expedition_screen_ready.png has appeared.
[2015-10-13 04:19:55] Let's send an expedition out!
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[debug] waiting for ensei_area_01.png to appear
[debug] ensei_area_01.png has appeared.
[log] CLICK on L(432,550)@S(0)[0,0 1360x768]
[debug] waiting for ensei_name_06.png to appear
[debug] ensei_name_06.png has appeared.
[debug] waiting for ensei_name_06.png to appear
[debug] ensei_name_06.png has appeared.
[log] CLICK on L(595,438)@S(0)[0,0 1360x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(974,558)@S(0)[0,0 1360x768]
[2015-10-13 04:20:08] Trying to send out fleet 4 for expedition 6
[debug] waiting for fleet_4.png to appear
[debug] fleet_4.png has appeared.
[debug] waiting for fleet_4.png to appear
[debug] fleet_4.png has appeared.
[log] CLICK on L(749,233)@S(0)[0,0 1360x768]
[2015-10-13 04:20:14] Checking expedition fleet status!
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for ensei_start.png to appear
[debug] ensei_start.png has appeared.
[debug] waiting for ensei_start.png to appear
[debug] ensei_start.png has appeared.
[log] CLICK on L(922,560)@S(0)[0,0 1360x768]
[debug] waiting for exp_started.png to appear
[debug] exp_started.png has appeared.
[2015-10-13 04:20:27] Expedition sent!: Expedition 6 (ETA 2015-10-13 04:59:52)
[2015-10-13 04:20:28] Next action at 2015-10-13 04:59:52
[2015-10-13 05:00:00] Checking for return of expedition 6
[2015-10-13 05:00:00] Focus on KanColle!
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium

```

**Comment by mrmin123** [comment]
If your kancolle catbomb'ed that'll happen. The script tries to focus into the specified program until it finds sortie.png, which it won't if there's a catbomb. I'll add a check for catbomb at some point, but I don't know what good that will do other than exit out of the script.

@perryhuynh actually mentioned that he made modifications to reload the game on script crash in the discussion for #40. Perhaps something like that could be incorporated in the future.

**Comment by kevin01523** [comment]
it was on a repo where you based the config.ini that could be improved if theres an option on the config.ini to turn it off and on and use different reload images or reload method depending on the browser
i did modify the that one to work with electronic observer well it was hard to implement with kc3 and kct

what it really does of the script is stuck or could not find any images it wants it reloads the game

**Comment by mrmin123** [comment]
@kevin01523 I got the idea for the config from Onegai-ooyodosan but couldn't find anything regarding the catbomb in there.

And yes, there's the issue of having it work with all sorts of different browsers and Viewers. Not sure if that's within the scope of the tool. It'd be a nice to have, but I think for now the workaround for catbombs will be to reload your browser/Viewer, and then restart the script.

**Comment by kevin01523** [comment]
https://github.com/tantinevincent/Onegai-ooyodosan/blob/master/main.sikuli/main.py
actually its there 

```
@logged
def returnToBase():
clickIfExistsWithResetMouse("base.png")
clickIfExistsWithResetMouse("back.png")
sleep(3)
if exists("sortie.png"):
return
# Can not back to base, restart kancolle
restartKancolle() # calls reload if its stuck


#reload function
def restartKancolle():
isOnWelcomePage = False
wait_welcome_page_time = 20
while not isOnWelcomePage:
clickWithResetMouse(Pattern("reload.png").similar(0.80))
sleep(wait_welcome_page_time)
wait_welcome_page_time = wait_welcome_page_time *2
isOnWelcomePage = exists(Pattern("welcome_page.png").targetOffset(209,156))
clickWithResetMouse(Pattern("welcome_page.png").targetOffset(209,156))
sleep(wait_welcome_page_time)
```

well all i did modify on my local copy of this that i changed the reload  png and added conditions

well this one would work wonders if your playing using any browser on dmm or if using a tool/viewer with simple reload like Electronic observer or even kcv if it has reload button

on kc3 theres an option to enable reloading within the game but its hard to use theres countdown and i think its semi transparent
the other option for kc3 is to normally click the reload button the browser then theres a condtion to look for the pop up and game start of kc3 then wait for the welcome page

well for now i think a simple function same as on Onegai-ooyodosan would be sufficient for dmm site players since theres that api locking going on

**Comment by perryhuynh** [comment]
Using KC3, I just used the "Play via DMM Website" option and there is no reload confirmation pop up

**Comment by mrmin123** [comment]
OK, I guess there might be enough of a value add with adding support for dealing with the catbombs especially in light of the recent changes with the API links timing out. I'll close this ticket and #40, and open up a separate one to consolidate efforts.
