### ISSUE TITLE
Add support for dealing with catbombs

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#47]
Continuation of discussion in #40 and #46

The catbomb image already exists in the repo.
Probably useful now with the new API link timeout stuff the kancolle staff implemented recently.

Situations I can think of that will require unique refresh steps (??):
- Firefox
- Chrome
  - Chrome w/ KC3 (Play w/ API, Play w/ DMM, Play w/ DMM iFrame)
- IE??
- The other viewers???

**Comment by kevin01523** [comment]
Electronic observer well just a different reload.png

and i dont think anyone uses IE now a days for kc well maybe viewers using ie but not directly
well i do think chrome is priority 1 2nd is firefox others for future

**Comment by perryhuynh** [comment]
I've submitted a pull request, I apologize for what may be shitty code as I've never used python/sikuli before. I only added support for Chrome so far. I don't know how well Sikuli image recognition works as the colors/etc of the Chrome interface can vary depending on Desktop Environment/Operating System/etc.

I didn't add support for API Links/DMM frame because refreshing an API link could cause an infinite loop of catbombs unless I added support for refreshing the API link

**Comment by kevin01523** [comment]
cat errors would cause findfailed exceptions
so if any findfailed excetion occured try to focus on kancolle window then check exist check all return buttons to hq screen if not found check if there's that cat if exist try to reload the game
after reloading the game re initialize the script like what it does after starting it.
^
i think this is the first goal if that one is now foolproof then next is trying to support 
mainstream viewers

edit
def mainloopWithException():
count = 0
while(True):
try:
print(count)
switchApp(config.browser)
doAllJob(count)
random_sleep_time = random.randrange(int(config.sleep_time_0.9), int(config.sleep_time_1.1)) # sleeping with random offset time
print "sleep " + str(random_sleep_time) + " sec..."
sleep(random_sleep_time)
count += 1
except FindFailed :
print("find failed")
returnToBase()

ah so he did use what im tacking about trying ti return home if theres a findfailed situation

**Comment by perryhuynh** [comment]
Implementing that from Onegai-ooyodosan should be fairly easy, I'm still trying to reproduce the bug with formation selection on node(s?) 2+

**Comment by kevin01523** [comment]
i do not encounter them maybe its an config error like what i exprienced
in the config must be line_ahead,line_ahead,line_ahead,line_ahead,line_ahead,

on nigh battle
False,False,False,False,False,

this fixed my problem

**Comment by mrmin123** [comment]
@perryhuynh Thanks for the PR. I'll take a look at it later tonight.

I think a simple cross-browser solution for refreshing is to just have Sikuli send a 'Ctrl+r' keystroke to the browser. KC3 I need to look further into.

And yes, catbombs will make Sikuli throw a FindFailed error, which can be caught in an exception. It'll just be a matter of wrapping the main function(s) in a try-catch.

@kevin01523 @perryhuynh Are you guys still getting errors when you have spaces in the formation/nightbattle sections of the config? I thought I fixed that a while back..

**Comment by kevin01523** [comment]
im not getting errors but i dont know about him because he gets errors during formation selection or looping there which kinda the same as me before

so if implemented its a matter of filtering common errors and catching them so the script wouldn't stop and just refresh

**Comment by perryhuynh** [comment]
After I pulled the latest updates and changed the config to the same way @kevin01523 I watched it do a few runs but haven't really been home to check. I don't know how to exactly reproduce it because sometimes it happens, sometimes it doesn't. Will report back later

edit: it failed to select formation again on the 2nd node of 4-3 again, it shouldn't matter but I'm going to test it orel cruising now

I have my formations like this in the config:

```
Formations: line_abreast,line_abreast,line_abreast,
```

**Comment by kevin01523** [comment]
ah saury well i did experience it there but the latest one fixed it for me

**Comment by perryhuynh** [comment]
I tested it with Orel Cruising for ~3 hours and it didn't have to call my refresh_page() function once, maybe it has something to do with line_abreast?

**Comment by mrmin123** [comment]
Hey @perryhuynh , thanks for the PR. I expanded a bit on the idea and made my own branch for catbomb recovery here: [47_catbomb](https://github.com/mrmin123/kancolle-auto/tree/47_catbomb)

If you and @kevin01523 can test it out I'd appreciate it!

**Comment by kevin01523** [comment]
git fetch origin && git pull && git reset --hard  HEAD && git reset --hard origin/47_catbomb  && sudo git clean -f -x -d ok did this just now ill test it on orel 1st then 1-5

**Comment by perryhuynh** [comment]
Sure I'll test it on Orel overnight

**Comment by kevin01523** [comment]
[2015-10-14 14:20:28] At Home!
[2015-10-14 14:20:28] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-14 14:20:32] No, no fleets to receive!
[2015-10-14 14:20:32] Navigating to Sortie menu!
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(510,385)@S(0)[0,0 1360x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(544,355)@S(0)[0,0 1360x768]
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[log] CLICK on L(544,557)@S(0)[0,0 1360x768]
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[log] CLICK on L(571,466)@S(0)[0,0 1360x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(996,560)@S(0)[0,0 1360x768]
[2015-10-14 14:20:48] Checking fleet condition...
[2015-10-14 14:20:58] Light damage: 0; moderate damage: 0; critical damage: 0
[2015-10-14 14:21:04] Checking fleet morale!
[2015-10-14 14:21:11] Ships have good morale!
[2015-10-14 14:21:14] Commencing sortie!
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has not appeared.
[2015-10-14 14:21:20] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find combat_start.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 400
[error] FindFailed ( can not find combat_start.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
45: util (  wait_and_click )     kc_window.wait(pic)
116: combat (  go_sortie )     wait_and_click(self.kc_window, 'combat_start.png')
245: main (  sortie_action )     combat_item.go_sortie()
391: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------

i guess the one above is a special case

[2015-10-14 14:42:22] At Home!
[2015-10-14 14:42:22] Are there returning expeditions to receive?
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[2015-10-14 14:42:26] No, no fleets to receive!
[2015-10-14 14:42:26] Navigating to Sortie menu!
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
[log] CLICK on L(510,385)@S(0)[0,0 1360x768]
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[debug] waiting for combat.png to appear
[debug] combat.png has appeared.
[log] CLICK on L(544,355)@S(0)[0,0 1360x768]
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[debug] waiting for combat_area_2.png to appear
[debug] combat_area_2.png has appeared.
[log] CLICK on L(544,557)@S(0)[0,0 1360x768]
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[debug] waiting for combat_panel_2-3.png to appear
[debug] combat_panel_2-3.png has appeared.
[log] CLICK on L(571,466)@S(0)[0,0 1360x768]
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[debug] waiting for decision.png to appear
[debug] decision.png has appeared.
[log] CLICK on L(996,560)@S(0)[0,0 1360x768]
[2015-10-14 14:42:42] Checking fleet condition...
[2015-10-14 14:42:51] Light damage: 0; moderate damage: 0; critical damage: 0
[2015-10-14 14:42:58] Checking fleet morale!
[2015-10-14 14:43:04] Ships have good morale!
[2015-10-14 14:43:08] Commencing sortie!
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(941,561)@S(0)[0,0 1360x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(647,362)@S(0)[0,0 1360x768]
[2015-10-14 14:43:29] Spinning compass!
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(758,301)@S(0)[0,0 1360x768]
[2015-10-14 14:43:43] Selecting fleet formation!
[2015-10-14 14:44:23] Declining night battle!
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(603,356)@S(0)[0,0 1360x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1064,548)@S(0)[0,0 1360x768]
[2015-10-14 14:44:40] Checking fleet condition...
[2015-10-14 14:44:51] Light damage: 0; moderate damage: 0; critical damage: 0
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1064,548)@S(0)[0,0 1360x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[log] CLICK on L(605,355)@S(0)[0,0 1360x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(647,362)@S(0)[0,0 1360x768]
[2015-10-14 14:45:31] Spinning compass!
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(647,362)@S(0)[0,0 1360x768]
[2015-10-14 14:45:59] Spinning compass!
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(758,301)@S(0)[0,0 1360x768]
[2015-10-14 14:46:13] Selecting fleet formation!
[2015-10-14 14:46:52] Declining night battle!
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(603,356)@S(0)[0,0 1360x768]
[debug] waiting for next.png to appear
[debug] next.png has not appeared.
[error] script stopped with error in line 400
[error] UnboundLocalError ( local variable 'last_refresh' referenced before assignment )
[error] --- Traceback --- error source first
line: module ( function ) statement 
319: main (  refresh_kancolle )     if last_refresh != '':
[error] --- Traceback --- end --------------
kevin@ubuntu:~/kancolle-auto$

**Comment by mrmin123** [comment]
Not sure how you got to that point @kevin01523 . decision.png wasn't clicked properly? What's that popup say?

Sortieing is working fine on my end...

**Comment by kevin01523** [comment]
i guess the pop up interfered and decision.png wasnt clicked did not try to refresh.on the 2nd one it didnt refresh but got an error

sortieng is working too
the pop up maybe log in to dmm
or refresh log in since it redirected me to log in then loaded the game again

note:
manual clicking ctrl+r reloads the page w/ the start the game page of kc3 kai
might be useful:
F5 also works for reloading

**Comment by mrmin123** [comment]
I intentionally made it so that it won't hammer on reload if it's a non-catbomb error. I'd much rather have the user click through and resolve the error instead of having kancolle get refreshed because Sikuli couldn't find some error in the middle of a sortie or something...

**Comment by kevin01523** [comment]
uhm ok well the 2nd one is a legitimate cat error but i dunno what happened

**Comment by mrmin123** [comment]
Ok, I'll have to take a closer look at the second scenario tomorrow. Is the
screenshot for the first or second scenario?

**Comment by kevin01523** [comment]
the 1st screenshot is for the 1st scenario the 2nd one is for the 2nd and its log is below each screenshot

**Comment by perryhuynh** [comment]
the 1st screenshot error msg says something like because an error has occurred the page will be refreshed, i'm also going to begin testing now but not via API link

**Comment by kevin01523** [comment]
just use the play using frame

**Comment by perryhuynh** [comment]
I was able to orel overnight without any issues

**Comment by mrmin123** [comment]
@kevin01523 ok, for some reason yesterday when I was checking your comments I couldn't see the 'second scenario' but I'm on a different machine now and I can see it. Anyways, the issue for the second (legit catbomb) crash should be fixed on the latest 47_catbomb (e7c206e).

For the first scenario, the popup most likely interfered with the clicks, causing the crash. Not sure if the script should account for this.

**Comment by kevin01523** [comment]
as i said i guess the one above is a special case. so maybe we can leave it be for now.
hmm does it try to  focus on kc window before refreshing?

i tried editing the script adding another elif on a non catbomb scenario findfailed where it tries to go first focus on game window  go home then restart script .but to no avail. well it does work if i put it on else but that will cause endless loop if findfailed occured during sortie.

**Comment by mrmin123** [comment]
@kevin01523 It shouldn't need to focus on kc_window before refreshing, because the previous commands should have focused on it to begin with. If it's not at the correct window when it attempts to refresh, then there are other issues not correctable by the script at play.

What does your `elif` conditional look like? I'd imagine it would work fine if you put it in `else`, not sure why you're getting an infinite loop. Some pseudocode:

```
else:
    if !check_and_click(kc_window, 'button_for_home'):
        type('r', KeyModifier.CTRL)
        # commands to re-start game
        wait_and_click(kc_window, Pattern('game_start.png').exact(), WAITLONG)
        last_refresh = datetime.datetime.now()
```

**Comment by kevin01523** [comment]
havent tested it yet with sortie well its a test only  im not refreshing the game or relying on refreshing kancolle  but reinitializing the script like it was cold boot after attempting to go home.another kind of error handling when findfailed occured other than a cat error the script will try to continue and not crash but it will still log the crash.

something like
Else:
log(non cat error exception)
appfocus()
gohome()
if sortiemain.png exist
init()
else
 log_error("Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!")
print e
raise

**Comment by kevin01523** [comment]
ok ithe script encounterd a cat error but does nothing well its kinda froze and stopped at 

[2015-10-15 07:08:19] Ships have good morale!
[2015-10-15 07:08:23] Commencing sortie!
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[log] CLICK on L(938,559)@S(0)[0,0 1360x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(644,360)@S(0)[0,0 1360x768]
[2015-10-15 07:08:46] Spinning compass!
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(755,299)@S(0)[0,0 1360x768]
[2015-10-15 07:09:23] Selecting fleet formation!
[2015-10-15 07:10:15] Declining night battle!
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[log] CLICK on L(600,354)@S(0)[0,0 1360x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1061,546)@S(0)[0,0 1360x768]
[2015-10-15 07:10:32] Checking fleet condition...
[2015-10-15 07:10:40] Light damage: 3; moderate damage: 0; critical damage: 0
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[log] CLICK on L(1061,546)@S(0)[0,0 1360x768]
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[debug] waiting for next_alt.png to appear
[debug] next_alt.png has appeared.
[log] CLICK on L(1068,555)@S(0)[0,0 1360x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[log] CLICK on L(602,353)@S(0)[0,0 1360x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[log] CLICK on L(644,360)@S(0)[0,0 1360x768]
[2015-10-15 07:11:46] Spinning compass!
[debug] waiting for P(formation_line_ahead.png) S: 0.99 to appear
[debug] P(formation_line_ahead.png) S: 0.99 has appeared.
[log] CLICK on L(755,299)@S(0)[0,0 1360x768]
[2015-10-15 07:12:00] Selecting fleet formation!

 im not stopping the script and still not moving or do not even throw an error here
its waiting indefinitely?

**Comment by mrmin123** [comment]
@kevin01523 oh lol. The main combat loop is designed to repeat until it finds one of the things it's looking for (compass, next, next_alt, night battle prompts...) so that's probably why. I'll have to wrangle in a fix in there.

**Comment by kevin01523** [comment]
well most cat errors do occur on combat haha next is resupply or sending the expediton

**Comment by mrmin123** [comment]
@kevin01523 9d28978

**Comment by kevin01523** [comment]
ok ill try that now

**Comment by perryhuynh** [comment]
Ran into this issue overnight, dunno how long it was going on

```
[2015-10-15 22:04:20] Could not find Kancolle homepage after 10 attempts. Exiting script.
[info] Exit code: 0
[2015-10-15 22:04:23] Reading config file
[2015-10-15 22:04:23] Expeditions enabled!
[2015-10-15 22:04:23] Combat enabled!
[2015-10-15 22:04:23] Config loaded!
[2015-10-15 22:04:23] Starting kancolle_auto
[2015-10-15 22:04:23] Focus on KanColle!
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
```

I'm fairly certain it has something to do with line_abreast, as I don't seem to ever experience this when using line_ahead

**Comment by mrmin123** [comment]
@perryhuynh Stuck at the formation select screen again, I take it? If it's only happening when you have it set to line_abreast it sounds like the `formation_line_abreast.png` needs to be updated. And set the match threshold from `exact()` to something lower. I'll do some more testing tonight and push a fix.

**Comment by perryhuynh** [comment]
Yep, formation selection when using line abreast, I'm going to make another formation_line_abreast.png later and try ~similar(.90)

**Comment by mrmin123** [comment]
@perryhuynh If you set it to `simliar(0.9)` could you also run some sorties with line_ahead and make sure that it doesn't select line_abreast? The two buttons are so similar that I was constantly running into that issue, which is the reason why I set it to `exact()` in the first place.

**Comment by perryhuynh** [comment]
Yeah that was my fear, I won't be able to do this until ~4PM pst

**Comment by kevin01523** [comment]
https://github.com/mrmin123/kancolle-auto/pull/53/

**Comment by mrmin123** [comment]
@perryhuynh No prob. Glad to have more eyes on this issue.

Thanks for the PR @kevin01523 . I'm going to make some minor changes to the PR and then merge it in later tonight when I get home.

**Comment by kevin01523** [comment]
```
←[92m[2015-10-16 06:33:02] At Home!←[0m
←[94m[2015-10-16 06:33:02] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-16 06:33:07] No, no fleets to receive!←[0m
←[94m[2015-10-16 06:33:07] Lets resupply fleets!←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for supply_main.png to appear
[debug] supply_main.png has appeared.
[log] CLICK on L(375,326)@S(0)[0,0 1366x768]
[debug] waiting for supply_screen.png to appear
[debug] supply_screen.png has appeared.
[debug] waiting for supply_all.png to appear
[debug] supply_all.png has appeared.
[log] CLICK on L(416,223)@S(0)[0,0 1366x768]
←[92m[2015-10-16 06:33:27] Done resupplying!←[0m
←[94m[2015-10-16 06:33:27] Focus on KanColle!←[0m
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-16 06:33:39] Going Home!←[0m
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(369,361)@S(0)[0,0 1366x768]
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
[debug] waiting for sortie.png to appear
[debug] sortie.png has appeared.
←[92m[2015-10-16 06:33:45] At Home!←[0m
←[94m[2015-10-16 06:33:45] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-16 06:33:50] No, no fleets to receive!←[0m
←[92m[2015-10-16 06:33:50] Next sortie!: 2015-10-16 06:41:46←[0m
←[94m[2015-10-16 06:33:50] Next action at 2015-10-16 06:40:57←[0m
←[94m[2015-10-16 06:41:26] Checking for return of expedition 5←[0m
←[94m[2015-10-16 06:41:26] Focus on KanColle!←[0m
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[92m[2015-10-16 06:41:33] At Home!←[0m
←[94m[2015-10-16 06:41:33] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-16 06:41:38] No, no fleets to receive!←[0m
←[92m[2015-10-16 06:41:38] Refreshing Home!←[0m
[debug] waiting for supply_main.png to appear
[debug] supply_main.png has appeared.
[log] CLICK on L(375,326)@S(0)[0,0 1366x768]
[debug] waiting for home_side.png to appear
[debug] home_side.png has appeared.
[log] CLICK on L(369,361)@S(0)[0,0 1366x768]
←[92m[2015-10-16 06:41:46] At Home!←[0m
←[94m[2015-10-16 06:41:46] Are there returning expeditions to receive?←[0m
[debug] waiting for senseki_off.png to appear
[debug] senseki_off.png has appeared.
←[94m[2015-10-16 06:41:52] No, no fleets to receive!←[0m
←[94m[2015-10-16 06:41:52] Focus on KanColle!←[0m
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
[log] App.focus Type 74 Electronic Observer 1.6.3 [TL 1.2b](0) #0
←[91m[2015-10-16 06:42:35] Could not find Kancolle homepage after 10 attempts. E
xiting script.←[0m
[info] Exit code: 0
```

loops then activates exit function when gets catbombs going home

**Comment by perryhuynh** [comment]
I made a new formation_line_abreast.png and used similar(0.9) and ran about ~7 sorties now without any issues, I will keep it running and pay attention to it

**Comment by mrmin123** [comment]
@kevin01523 merged in your PR, as well as the fix for the last error you posted, into the 47_catbomb branch.

@perryhuynh good to hear. If line_ahead also works with 0.9, feel free to make a PR and I'll merge after testing locally.

**Comment by perryhuynh** [comment]
Hmm, I got a crash on line_abreast with 0.95 going to test a bit further

**Comment by mrmin123** [comment]
@perryhuynh ok.

Commit b31877706e781ec3466d30c2f1c82adad49bcd34 Contains refresh support for KCV and KCT.

How is the catbomb support treating everyone right now? I feel like this branch is close to being able to merge.

**Comment by kevin01523** [comment]
@mrmin123 on kct try to use the get api link instead of refresh since api link is locked

**Comment by mrmin123** [comment]
@kevin01523 OK. I don't have the codebase in front of me right now but I'll do some testing when I get back home this afternoon.

**Comment by mrmin123** [comment]
@kevin01523 I can't get the Get API link menu option to work. It just takes me to a login page where I can't get rid of this stupid 'Choose your language' overlay, and I can't resize the window or anything...

**Comment by mrmin123** [comment]
I'm going to merge this 47_catbomb into master now, and take care of any additional issues that crop up in a separate ticket. Thanks for all your help @kevin01523 and @perryhuynh !

**Comment by kevin01523** [comment]
@mrmin123 on the option activate cookie hack then select the japanese language then check all checkbox to remember password etc and stay log in as long as kct viewer is not closed it will remember the session hmm try to use tab to close the overlay i know i can close the with the mouse or i click the jp language

http://imgur.com/a/J12UF
http://imgur.com/8Q1Mhv9
