### ISSUE TITLE
Opencv fails to allocate memory

### ISSUE THREAD

**Issue by Danielosama** [mrmin123/kancolle-auto#49]
So today, 3 hours or so after I launched the script, this error popped up "OpenCV fails to allocate memory etc" and the script stopped.
Any ideas to what might cause that?

**Comment by kevin01523** [comment]
more like ubuntu problem. reboot your pc or if your using a vm allocate more memory

**Comment by mrmin123** [comment]
Yea, I don't think that's anything this script can fix. Sikuli/OpenCV/memory issue. Your best bet is to just restart the script...
