### ISSUE TITLE
combat got stuck

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#57]
←[94m[2015-10-17 20:26:39] Checking fleet morale!←[0m
←[92m[2015-10-17 20:26:45] Ships have good morale!←[0m
←[92m[2015-10-17 20:26:48] Commencing sortie!←[0m
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for P(combat_start.png) S: 0.8 T: -29,1 to appear
[debug] P(combat_start.png) S: 0.8 T: -29,1 has appeared.
[log] CLICK on L(908,584)@S(0)[0,0 1366x768]
[debug] waiting for compass.png to appear
[debug] compass.png has appeared.
[debug] waiting for P(compass.png) S: 0.8 T: -29,-36 to appear
[debug] P(compass.png) S: 0.8 T: -29,-36 has appeared.
[log] CLICK on L(614,348)@S(0)[0,0 1366x768]
←[94m[2015-10-17 20:27:14] Spinning compass!←[0m
[debug] waiting for P(formation_line_ahead.png) S: 0.95 to appear
[debug] P(formation_line_ahead.png) S: 0.95 has appeared.
[debug] waiting for P(formation_line_ahead.png) S: 0.95 T: 8,5 to appear
[debug] P(formation_line_ahead.png) S: 0.95 T: 8,5 has appeared.
[log] CLICK on L(762,329)@S(0)[0,0 1366x768]
←[94m[2015-10-17 20:27:28] Selecting fleet formation!←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for P(next.png) S: 0.8 T: -11,-9 to appear
[debug] P(next.png) S: 0.8 T: -11,-9 has appeared.
[log] CLICK on L(1049,561)@S(0)[0,0 1366x768]
←[94m[2015-10-17 20:28:35] Checking fleet condition...←[0m
←[94m[2015-10-17 20:28:44] Light damage: 0; moderate damage: 0; critical damage
 0←[0m
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for P(next.png) S: 0.8 T: 2,-2 to appear
[debug] P(next.png) S: 0.8 T: 2,-2 has appeared.
[log] CLICK on L(1062,568)@S(0)[0,0 1366x768]
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for combat_nextnode.png to appear
[debug] combat_nextnode.png has appeared.
[debug] waiting for P(combat_nextnode.png) S: 0.8 T: 50,30 to appear
[debug] P(combat_nextnode.png) S: 0.8 T: 50,30 has appeared.
[log] CLICK on L(650,403)@S(0)[0,0 1366x768]

the script got unresponsive here for no apparent reason the cursor is next to retreat after day battle

**Comment by mrmin123** [comment]
Are you on the random mouse click branch? It probably has to do with that. The image might need to be adjusted, which I won't have time to do until later.

**Comment by kevin01523** [comment]
yes im on the random click branch ok ill adjust my image to see how it goes

**Comment by mrmin123** [comment]
Closing this ticket as it was probably related to the un-optimized images.
