### ISSUE TITLE
OCR Errors

### ISSUE THREAD

**Issue by wwly23** [mrmin123/kancolle-auto#64]
When the script tries to use OCR for expedition timers and repair timers, I get this error:

[error] script stopped with error in line 298
[error] LookupError ( unknown encoding 'ms932' )
Exception in thread "main" java.lang.IllegalStateException: No match found . . .

I'm using the recommended versions of Sikuli and Python on your installation wiki page. Windows 7 64-bit, KancolleViewer, System Locale set to Japanese if that matters.

http://imgur.com/mMgFtne

**Comment by mrmin123** [comment]
@wwly23 Could you try the fix outlined here?: http://blog.sina.com.cn/s/blog_60966f440100w7y9.html
TL:DR; try running the command `chcp 437` in the command prompt before running the script.

However, even if that works it's not the most ideal fix. I'll look into alternatives once I'm back at my dev machine later. (Ref [1](http://stackoverflow.com/questions/12158747/jython-unknown-enocoding-ms932-on-japanese-system), [2](http://stackoverflow.com/questions/2276200/changing-default-encoding-of-python))

**Comment by wwly23** [comment]
Yes that seems to have done the trick, thanks.

I also found another minor bug. When I start up the script on the command prompt, I get this error ( http://imgur.com/UY0qJ9R ) unless I click on KancolleViewer to bring the window to the foreground before Sikuli executes the script.

**Comment by mrmin123** [comment]
@wwly23 Changing the Program parameter to 'KanColleViewer!' (add the !) fixed the issue on my end. Config has been updated as of ed06604
