### ISSUE TITLE
OCR Bug

### ISSUE THREAD

**Issue by wwly23** [mrmin123/kancolle-auto#65]
http://imgur.com/a/ObHZu

Timer for repair is 10:18:37, but the script is stuck in a loop:
"Got invalid timer (10:1::37) . . . trying again!)
Got invalid timer (10:1::37) . . . trying again!)
Got invalid timer (10:1::37) . . . trying again!)"

I also had a memory leak after leaving the script running for about six hours. I ran out of RAM and the script crashed. It probably has something to do with Sikuli rather than the script, but I thought I'd mention it anyway to see if it's just me.

http://imgur.com/a/NhNVx

**Comment by wwly23** [comment]
-        timer = ''.join(timer)
-        timer = (
-            timer.replace('l', '1').replace('I', '1').replace('[', '1').replace(']', '1')
-            .replace('|', '1').replace('!', '1').replace('O', '0').replace('o', '0')
-            .replace('D', '0').replace('Q', '0').replace('@', '0').replace('S', '5')
-            .replace('s', '5').replace('$', '5').replace('B', '8').replace(' ', '')
            .replace(':', '8')
-        )
-        timer[2] = ':'
-        timer[5] = ':'

Maybe that will fix it? Change colons to 8, then replace 3rd and 6th character with colons.

**Comment by mrmin123** [comment]
@wwly23 Yes, that should work. Until Sikuli throws another fun OCR reading, that is!
