### ISSUE TITLE
 menu_side_expedition.png looks like a file, but not on disk. Assume it's text.

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#70]
2015-11-08 06:52:43] Done resupplying!
[2015-11-08 06:52:43] Focus on KanColle!
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[2015-11-08 06:53:00] Going home with 1 or less sidestep(s)!
[debug] waiting for menu_side_equip.png to appear
[debug] menu_side_equip.png has appeared.
[debug] waiting for menu_side_equip.png to appear
[debug] menu_side_equip.png has appeared.
[debug] waiting for P(menu_side_equip.png) S: 0.8 T: -11,-14 to appear
[debug] P(menu_side_equip.png) S: 0.8 T: -11,-14 has appeared.
[log] CLICK on L(269,377)@S(0)[0,0 1360x768]
[debug] waiting for menu_side_home.png to appear
[debug] menu_side_home.png has appeared.
[debug] waiting for menu_side_home.png to appear
[debug] menu_side_home.png has appeared.
[debug] waiting for P(menu_side_home.png) S: 0.8 T: -11,-28 to appear
[debug] P(menu_side_home.png) S: 0.8 T: -11,-28 has appeared.
[log] CLICK on L(321,361)@S(0)[0,0 1360x768]
[2015-11-08 06:53:15] At Home!
[2015-11-08 06:53:15] Are there returning expeditions to receive?
[2015-11-08 06:53:18] No, no fleets to receive!
[2015-11-08 06:53:22] Navigating to expedition screen with 1 sidestep(s)!
[debug] waiting for menu_side_fleetcomp.png to appear
[debug] menu_side_fleetcomp.png has appeared.
[debug] waiting for menu_side_fleetcomp.png to appear
[debug] menu_side_fleetcomp.png has appeared.
[debug] waiting for P(menu_side_fleetcomp.png) S: 0.8 T: -10,-18 to appear
[debug] P(menu_side_fleetcomp.png) S: 0.8 T: -10,-18 has appeared.
[log] CLICK on L(270,265)@S(0)[0,0 1360x768]
[debug] waiting for menu_side_expedition.png to appear
[error] menu_side_expedition.png looks like a file, but not on disk. Assume it's text.
[error] Region.find(text): text search is currently switched off
[2015-11-08 06:53:33] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: Text search currently switched off
  Line 1671, in file Region.java

[error] script stopped with error in line 307
[error] FindFailed ( Text search currently switched off )
[error] --- Traceback --- error source first
line: module ( function ) statement 
321: util (  wait_and_click )     kc_window.wait(pic, time)
270: util (  rnavigation )     wait_and_click(kc_window, 'menu_side_' + destination + '.png')
20: expedition (  go_expedition )     rnavigation(self.kc_window, 'expedition', 2)
155: main (  expedition_action )     expedition_item.go_expedition()
299: main (  init )     expedition_action('all')
304: main (  init )     refresh_kancolle(e)
[error] --- Traceback --- end --------------

**Comment by mrmin123** [comment]
@kevin01523 Was it actually at the fleetcomp screen? If so, I suspect that an area in `menu_side_home.png` is out of bounds.

**Comment by kevin01523** [comment]
yes it was on the fleet compo screen i noticed that when i updated more errors do occur ill try to reclone the script
