### ISSUE TITLE
finding resupply screen while on repair screen

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#71]
[2015-11-08 16:23:59] At Home!
[2015-11-08 16:23:59] Are there returning expeditions to receive?
[debug] waiting for P(expedition_finish.png) S: 0.8 T: -282,256 to appear
[debug] P(expedition_finish.png) S: 0.8 T: -282,256 has appeared.
[log] CLICK on L(497,416)@S(0)[0,0 1360x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for P(next.png) S: 0.8 T: -523,-41 to appear
[debug] P(next.png) S: 0.8 T: -523,-41 has appeared.
[log] CLICK on L(500,534)@S(0)[0,0 1360x768]
[2015-11-08 16:24:11] Yes, fleet 2 has returned!
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for P(next.png) S: 0.8 T: -369,-374 to appear
[debug] P(next.png) S: 0.8 T: -369,-374 has appeared.
[log] CLICK on L(654,201)@S(0)[0,0 1360x768]
[debug] waiting for menu_main_sortie.png to appear
[debug] menu_main_sortie.png has appeared.
[2015-11-08 16:24:13] Are there returning expeditions to receive?
[2015-11-08 16:24:17] No, no fleets to receive!
[2015-11-08 16:24:17] Lets resupply fleets!
[2015-11-08 16:24:21] Navigating to resupply screen with 1 sidestep(s)!
[debug] waiting for menu_main_repair.png to appear
[debug] menu_main_repair.png has appeared.
[debug] waiting for menu_main_repair.png to appear
[debug] menu_main_repair.png has appeared.
[debug] waiting for P(menu_main_repair.png) S: 0.8 T: -16,-6 to appear
[debug] P(menu_main_repair.png) S: 0.8 T: -16,-6 has appeared.
[log] CLICK on L(367,489)@S(0)[0,0 1360x768]
[debug] waiting for menu_side_resupply.png to appear
[debug] menu_side_resupply.png has appeared.
[debug] waiting for menu_side_resupply.png to appear
[debug] menu_side_resupply.png has appeared.
[debug] waiting for P(menu_side_resupply.png) S: 0.8 T: 5,-17 to appear
[debug] P(menu_side_resupply.png) S: 0.8 T: 5,-17 has appeared.
[log] CLICK on L(287,320)@S(0)[0,0 1360x768]
[debug] waiting for resupply_screen.png to appear
[debug] resupply_screen.png has not appeared.
[2015-11-08 16:25:34] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find resupply_screen.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 344
[error] FindFailed ( can not find resupply_screen.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
116: main (  resupply )     kc_window.wait('resupply_screen.png', WAITLONG)
77: main (  go_home )     resupply()
130: main (  resupply )     go_home()
168: main (  sortie_action )     resupply()
335: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------
kevin@LinuxMint ~/kancolle-auto $

**Comment by kevin01523** [comment]
[2015-11-08 17:02:25] At Home!
[2015-11-08 17:02:25] Are there returning expeditions to receive?
[2015-11-08 17:02:28] No, no fleets to receive!
[2015-11-08 17:02:28] Lets resupply fleets!
[2015-11-08 17:02:32] Navigating to resupply screen with 1 sidestep(s)!
[debug] waiting for menu_main_repair.png to appear
[debug] menu_main_repair.png has appeared.
[debug] waiting for menu_main_repair.png to appear
[debug] menu_main_repair.png has appeared.
[debug] waiting for P(menu_main_repair.png) S: 0.8 T: -17,-13 to appear
[debug] P(menu_main_repair.png) S: 0.8 T: -17,-13 has appeared.
[log] CLICK on L(366,482)@S(0)[0,0 1360x768]
[debug] waiting for menu_side_resupply.png to appear
[debug] menu_side_resupply.png has appeared.
[debug] waiting for menu_side_resupply.png to appear
[debug] menu_side_resupply.png has appeared.
[debug] waiting for P(menu_side_resupply.png) S: 0.8 T: -6,-5 to appear
[debug] P(menu_side_resupply.png) S: 0.8 T: -6,-5 has appeared.
[log] CLICK on L(276,332)@S(0)[0,0 1360x768]
[debug] waiting for resupply_screen.png to appear
[debug] resupply_screen.png has not appeared.
[2015-11-08 17:03:46] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find resupply_screen.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 344
[error] FindFailed ( can not find resupply_screen.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
116: main (  resupply )     kc_window.wait('resupply_screen.png', WAITLONG)
168: main (  sortie_action )     resupply()
335: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------
kevin@LinuxMint ~/kancolle-auto $

**Comment by mrmin123** [comment]
Have you tried increasing SleepModifier to 1, 2, or even 3?

**Comment by kevin01523** [comment]
yes i was using my old config so im sure it was set right

**Comment by mrmin123** [comment]
OK, try 736c9eb . `rnavigation` actually checks to see if it's at the right place, otherwise tries to hit the button again. The one possible flaw the new functionality has right now is with the expedition menu item... if it's random walking and using the top buttons to navigate, if the top expedition button is pressed, then fails the check due to loading, but loads before the top expedition button can be pressed again, the crash might crash because the top expedition button changed to its highlighted state.

But whatever.

This should also address #70, since even if it hits a deadzone trying to get home, it'll attempt the click again before continuing if it's not actually home.

**Comment by mrmin123** [comment]
Dumb mistake in code. Fixed in a0bacee
