### ISSUE TITLE
Automate PvP

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#75]

**Comment by n0k0m3** [comment]
This feature only benefits users who run the script want to powerleveling their ships. And also, the additional exp gained from the PvP is not worthy to waste time in OCR-ing exercises page and finding opponent.

**Comment by mrmin123** [comment]
This is actually already working in branch 75_pvp, and it's a module like Expeditions and Combat that can be turned on and off in the config.

**Comment by wwly23** [comment]
Are you going to implement battle logic to lower the chance of losses like estimating both fleets' strength via some ship type valuation system and maybe avoiding subs for simplicity? It'd be cool!

**Comment by mrmin123** [comment]
@wwly23 I don't know about ship type valuation system (I haven't looked at the game in a while but I don't think the PVP screens show ship types, and if that's the case it would take forever to figure out the ship type via ship portraits)... ship levels would work... sub identification would work based on portrait ID too, but since there's a smaller number of them it should be possible...

I'm wondering what you would actually do if you could ID fleets you'd want to avoid. Not sortie vs them for the purpose of preserving your PvP ratio? Switch fleets (using the new fleet comp save system) depending on the presence of enemy subs/high level ships?

For the record, the current (incredibly crude) implementation just throws Fleet 1 against whatever, which certainly isn't ideal but works in just eking out a few Exp for some ships I want to level.

**Comment by wwly23** [comment]
I was thinking it would be useful for the exercise quests, but I agree that image recognition would be way too slow.
