### ISSUE TITLE
menu_side_resupply.png has not appeared

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#77]
[2015-11-17 19:40:13] Sortie complete!
[2015-11-17 19:40:13] Focus on KanColle!
[log] App.focus Chromium(0) #0
[log] switchApp: Chromium
[2015-11-17 19:40:21] At Home!
[2015-11-17 19:40:21] Checking for returning expeditions!
[2015-11-17 19:40:21] Are there returning expeditions to receive?
[2015-11-17 19:40:24] No, no fleets to receive!
[2015-11-17 19:40:24] Lets resupply fleets!
[2015-11-17 19:40:29] Navigating to resupply screen with 1 sidestep(s)!
[debug] waiting for menu_main_development.png to appear
[debug] menu_main_development.png has appeared.
[debug] waiting for menu_main_development.png to appear
[debug] menu_main_development.png has appeared.
[debug] waiting for P(menu_main_development.png) S: 0.8 T: 33,-30 to appear
[debug] P(menu_main_development.png) S: 0.8 T: 33,-30 has appeared.
[log] CLICK on L(567,484)@S(0)[0,0 1360x768]
[debug] waiting for menu_side_resupply.png to appear
[debug] menu_side_resupply.png has not appeared.
[2015-11-17 19:40:41] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find menu_side_resupply.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 334
[error] FindFailed ( can not find menu_side_resupply.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
402: util (  wait_and_click )     kc_window.wait(pic, time)
336: util (  rnavigation )     wait_and_click(kc_window, final_target)
121: main (  resupply )     rnavigation(kc_window, 'resupply')
179: main (  sortie_action )     resupply()
326: main (  init )     sortie_action()
331: main (  init )     refresh_kancolle(e)
[error] --- Traceback --- end --------------

crashed at home screen
i guess it failed to click something

**Comment by n0k0m3** [comment]
Nah, the most funny part in using this code is YOU MUST NOT CLICK ANYTHING OR YOU WILL MESS UP WITH IT.
1st: Never try to move the mouse (u still can when the code is in sleep mode, or during sortie, but don't try moving it otherwise)
2nd: Never change the windows after u run the code.

**Comment by mrmin123** [comment]
@minh6a that's true with any Sikuli-driven script. I believe most people use a spare computer or a VM to run it.

Thinking about this issue right now I'm not sure why the crash happened in the first place. I've seen it deal with red flagships properly before. Maybe something to do with the click areas again (outside of browser?)
