### ISSUE TITLE
red flasghip crash

### ISSUE THREAD

**Issue by kevin01523** [mrmin123/kancolle-auto#78]
[2015-11-17 21:49:02] Commencing sortie!
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for combat_start.png to appear
[debug] combat_start.png has appeared.
[debug] waiting for P(combat_start.png) S: 0.8 T: -43,0 to appear
[debug] P(combat_start.png) S: 0.8 T: -43,0 has appeared.
[log] CLICK on L(847,597)@S(0)[0,0 1360x768]
[debug] waiting for P(compass.png) S: 0.8 T: -1,-157 to appear
[debug] P(compass.png) S: 0.8 T: -1,-157 has appeared.
[log] CLICK on L(595,241)@S(0)[0,0 1360x768]
[2015-11-17 21:49:30] Spinning compass!
[debug] waiting for P(formation_line_ahead.png) S: 0.95 to appear
[debug] P(formation_line_ahead.png) S: 0.95 has appeared.
[debug] waiting for P(formation_line_ahead.png) S: 0.95 T: 46,6 to appear
[debug] P(formation_line_ahead.png) S: 0.95 T: 46,6 has appeared.
[log] CLICK on L(753,344)@S(0)[0,0 1360x768]
[2015-11-17 21:49:48] Selecting fleet formation!
[2015-11-17 21:50:54] Declining night battle!
[debug] waiting for combat_nb_retreat.png to appear
[debug] combat_nb_retreat.png has appeared.
[debug] waiting for P(combat_nb_retreat.png) S: 0.8 T: 21,-34 to appear
[debug] P(combat_nb_retreat.png) S: 0.8 T: 21,-34 has appeared.
[log] CLICK on L(573,352)@S(0)[0,0 1360x768]
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for P(next.png) S: 0.8 T: -557,-27 to appear
[debug] P(next.png) S: 0.8 T: -557,-27 has appeared.
[log] CLICK on L(456,557)@S(0)[0,0 1360x768]
[2015-11-17 21:51:12] Checking fleet condition...
[2015-11-17 21:51:18] Light damage: 3; moderate damage: 0; critical damage: 1
[debug] waiting for next.png to appear
[debug] next.png has appeared.
[debug] waiting for P(next.png) S: 0.8 T: -442,-63 to appear
[debug] P(next.png) S: 0.8 T: -442,-63 has appeared.
[log] CLICK on L(571,521)@S(0)[0,0 1360x768]
[debug] waiting for combat_flagship_dmg.png to appear
[debug] combat_flagship_dmg.png has appeared.
[debug] waiting for combat_flagship_dmg.png to appear
[debug] combat_flagship_dmg.png has appeared.
[debug] waiting for P(combat_flagship_dmg.png) S: 0.8 T: 3,14 to appear
[debug] P(combat_flagship_dmg.png) S: 0.8 T: 3,14 has appeared.
[log] CLICK on L(1013,579)@S(0)[0,0 1360x768]
[2015-11-17 21:51:45] Ship(s) in condition at or below retreat threshold! Ceasing sortie!
[debug] waiting for combat_retreat.png to appear
[debug] combat_retreat.png has not appeared.
[2015-11-17 21:52:19] Non-catbomb script crash, or catbomb script crash w/ unsupported Viewer!
FindFailed: can not find combat_retreat.png on the screen.
  Line 1574, in file Region.java

[error] script stopped with error in line 389
[error] FindFailed ( can not find combat_retreat.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
402: util (  wait_and_click )     kc_window.wait(pic, time)
177: combat (  go_sortie )     wait_and_click(self.kc_window, 'combat_retreat.png', 30)
173: main (  sortie_action )     combat_item.go_sortie()
370: main (  <module> )     sortie_action()
[error] --- Traceback --- end --------------

script crashes when fs gets taihad on last node

**Comment by mrmin123** [comment]
Script needs to be revised so that it looks for next (next_alt?) OR combat_retreat and proceed accordingly. It's possible that I won't get around to this for a few weeks as I'll be overseas.

**Comment by kevin01523** [comment]
ok no problem well lots to do this 2 weeks event etc
