### ISSUE TITLE
OCR Repair Timer

### ISSUE THREAD

**Issue by wwly23** [mrmin123/kancolle-auto#81]
http://imgur.com/a/sX3uW

'00:14:10' is OCR'd as '00814-810' consistently.
Maybe replace '-' with '' to clean the string of dashes.

Defaulting to bucket when OCR fails consecutively might be a good idea. It doesn't happen often, so losing a bucket once in a long while is not bad at all compared to a hanging script.

**Comment by n0k0m3** [comment]
And also I realized the problem only happen to sub get taiha'd, mostly with Hachi and Goya

**Comment by mrmin123** [comment]
Cool OCR read. Yea, replacing all '-' with '' before it runs through the bulk of the timer read function should fix it. The default to bucket after n failures is a good idea. I'll try to implement it next.
