### ISSUE TITLE
Expand click areas

### ISSUE THREAD

**Issue by mrmin123** [mrmin123/kancolle-auto#88]
Expand click areas for:
- Quest activation
- Completed quest submission
- PvP opponent selection

**Comment by n0k0m3** [comment]
Need expand clicks areas for:
- Ooyodo on quest (can be click on whole screen)
- Expedition return (somehow most of the time it just click on the white notification while the whole screen is available)

**Comment by wwly23** [comment]
Offtopic, but an option to disable/enable quests in config.ini would be useful. Thanks for all the hard work!

**Comment by mrmin123** [comment]
@minh6a Forgot about Ooyodo, yes. I'm pretty sure the expanded click area is incorporated for expedition return, but I'll double check.

@wwly23 Oops, forgot to mention it in the config but if you leave the Quests variable empty in the config it'll be regarded as turning the module off. That said, I'll incorporate a separate Enabled field for it in the next update to keep things consistent.
